### ISSUE TITLE
useQuery is not typing queryKey correctly since 2.8.0

### ISSUE THREAD

**Issue by mmiszy** [tannerlinsley/react-query#1039]
**Describe the bug**
One could expect that values provided as the query key will be typed correctly and would match the arguments passed to the query function, as it used to before 2.8.0.

**To Reproduce**
Use this code with react-query@2.8.0 or newer

```ts
useQuery(['test', 1], (...args) => {
  console.log(args);
  return fetch('https://api.github.com/repos/tannerlinsley/react-query').then((res) => res.json());
});
```
Check the type of `args`.

**Expected behavior**
The type of `args` is `[string, number]` like it used to be before 2.8.0:
<img width="465" alt="Screenshot 2020-09-17 at 15 44 02" src="https://user-images.githubusercontent.com/1338731/93479460-9f859400-f8fc-11ea-8064-dc170c36fe0c.png">

**Current behavior**
The type of `args` is `any` or `[unknown, ...unknown[]]` (TypeScript 3.9.7 vs 4.0.2).

**Comment by boschni** [comment]
Hi @mmiszy ! The type connection between the query key and the query function parameters has been removed because it conflicted with how react-query actually works. The eventual query function parameters can be different from the query key because they can for example be filtered with queryFnParamsFilter or parameters can be added in the case of infinite queries (fetchMoreVariable). The implication of this is that the query function parameters will need to be typed.

When not using this functionality, this should also be possible:
```js
useQuery(['key', filters], () => fetch(filters))
```

**Comment by mmiszy** [comment]
It's a bit disappointing but makes sense. Thanks for the suggestions, we'll use that!

**Comment by omasback** [comment]
That's a bummer. Using the above recommendation, If the query key is `enabled` you'll still have to do an existence check inside the query function, defeating the point of `enabled`

**Comment by mataslib** [comment]
anoying
