### ISSUE TITLE
Infer fetch function argument types from key array

### ISSUE THREAD

**Issue by stephen776** [tannerlinsley/react-query#1087]
If passing an array as query key, all of the values implicitly get passed to the async function as args.

Is there a way to infer the types as such:

```
 const { isLoading, data, error } = useQuery(
    ['myKey', { id: 1 }],
    (key, { id }) => { /* id should be inferred as type number */ }
  );
```
Currently, it seems that id is inferred as type any which doesn't seem corrext

**Comment by boschni** [comment]
The type connection between the query key and the query function parameters has been removed because it conflicts with how react-query actually works. The eventual query function parameters can be different from the query key because they can be filtered or transformed with `queryFnParamsFilter` and parameters can be added in the case of infinite queries (`fetchMoreVariable`). The implication of this is that the query function parameters will need to be typed manually.

When not using this functionality, this should also be possible:
```js
useQuery(['key', filters], () => fetch(filters))
```

**Comment by TkDodo** [comment]
I stumbled upon this today as well. Even if I type my query fetch function explicitly, I will not get a type error if the key doesn't match. To pick up the previous example:

```
 const { isLoading, data, error } = useQuery(
    ['myKey', { id: 1 }],
    fetchFn
  );

function fetchFn(_: string, params: { id: string }) {
    return axios(...)
}
```

I would expect to see a type error here _somewhere_ because in the queryKey, I pass in `id: number`, but in the fetch function, i declare that id should be a `string`...

It seems like there is no correlation whatsoever between the queryFunction and the queryKey on type level

**Comment by boschni** [comment]
There is indeed no correlation on type level because there is also no correlation on runtime level. If they were correlated then they could be linked, but this is not the case due to the dynamic nature of React Query. In my previous comment I explained a bit more about this.

**Comment by tannerlinsley** [comment]
Yep, unfortunately, if you are using a detached function (not inline like @boschni suggested), then you'll have to manually type your params to your function.
