### ISSUE TITLE
infiniteQuery:getFetchMore() - continues to fetch data even if `false` is returned

### ISSUE THREAD

**Issue by pvomacka** [tannerlinsley/react-query#1115]
**Describe the bug**
Prerequisities: Having list of 7 items, fetched page by page, where page has 3 items. 

In case infiniteQuery fetches whole list (containing 3 pages) and then on another page one item from the list is removed. Then after returning back on page with the list, it sends 3 requests where the last one contains `false` as param, as `false` was returned from `getFetchMore()` function, because after second page there is no more data to load. Returning `false` from `getFetchMore()` should stop sending requests. The issue is reproduced in codesandbox.io - link in the steps to reproduce section. 

**To Reproduce**
1. Go to https://codesandbox.io/s/ancient-snow-0pqdp?file=/pages/index.js (Modified example from your documentation)
2. Turn on Developers Console -> Network Tab
3. Scroll down until  'Project 6' is loaded (which is the last item in the list)
4. Click on the link "Go to another page and remove one project"
5. Wait till deleting is completed
6. Click on "Go back and show the list without the last item"
7. Requests with `?page=false` are visible in Developers Console -> Network Tab

**Expected behavior**
After returning `false` from getFetchMore(), no more requests are sent

**Additional context**
Related discussion link: https://github.com/tannerlinsley/react-query/discussions/1114

**Comment by p-siriphanthong** [comment]
I think this problem is not `getFetchMore` problem but it is the refreshing problem.

When `refetch` is called, there are always `n` fetch requests where `n` is the number of pages in the cache.

In your case.

1. Scroll down until 'Project 6' is loaded -> There are 3 pages in the cache.
2. Go to removing page and wait till deleting is completed -> There are only 2 pages left.
3. Go back to list page -> The `refetch` will be called and request fetching data 3 times (number of pages in the cache).

I already create a pull request (#1124) to fix this problem 😄
