### ISSUE TITLE
Some examples from documentation are not working

### ISSUE THREAD

**Issue by aleksandarcrvc** [tannerlinsley/react-query#1143]
**Describe the bug**
Some examples from documentation are not working

**To Reproduce**
1. Go to https://react-query.tanstack.com/docs/examples/simple or https://react-query.tanstack.com/docs/examples/basic
2. See error on Browser preview

**Expected behavior**
It should work and show examples.

**Additional context**
I know that this is on codesandbox but reporting it since it would be really nice that examples work for developers and reputation as well.

**Comment by TkDodo** [comment]
I think this has todo with the latest releases. According to [npm](https://www.npmjs.com/package/react-query), the latest release is `2.23.1`, next would be `2.24.0-next.8` and beta is `2.25.0`.

However, if you open the examples (I had to open them in a private tab, probably due to caching), they try to download `^2.21.2`, which then resolves to `2.25.0` :/

If I try going that range (`^2.21.2`) in https://semver.npmjs.com , it says the latest release to resolve to is `2.23.1`, which seems correct:

<img width="1061" alt="Screenshot 2020-10-07 at 21 06 56" src="https://user-images.githubusercontent.com/1021430/95376237-181ab780-08e1-11eb-8410-c84e330a9da0.png">

So I'm not sure - is this a codesandbox issue trying to resolve the wrong version?

Anyways, as a workaround, you can set the dependency of react-query to `2.23.1` and then it works again.

@tannerlinsley I think it's quite confusing to have next and beta releases in the 2.x range - any chance we could make them be `3.0.0-beta1` or so?

**Comment by tannerlinsley** [comment]
We're working on it. Semantic release is difficult sometimes :)

**Comment by tannerlinsley** [comment]
This should be fixed now.
