### ISSUE TITLE
"useQuery" type signature now require 3 arguments, but in example it is optional

### ISSUE THREAD

**Issue by hitbear518** [tannerlinsley/react-query#128]
export declare function useQuery<QueryKeyType = any>(queryKey: QueryKeyType, queryFn: Query['queryFn'], config: QueryConfig): {
...

**Comment by dennismorello** [comment]
Hi @tannerlinsley, I am having this issue after having upgraded to the latest version.

**Comment by tannerlinsley** [comment]
This is because of a types artifact that leaked into the npm distribution from the typescript branch. The latest version should fix this error.

**Comment by baba43** [comment]
The current defintions from `@types/react-query` aren't correct, are they?

After upgrading to 1.x it seems that the QueryFunction always get the key passed as it's first parameter. Applying this change to my code makes the queries working again, but it can't be compiled by TypeScript because the definitions are wrong.

**Comment by tannerlinsley** [comment]
Types are outdated and not part of this library.

**Comment by baba43** [comment]
@tannerlinsley you really shouldn't think like that.

Your project is really awesome and since most developers in React-land are using TypeScript as of today, I think it should be part of your scope to take care of.

**Comment by tannerlinsley** [comment]
You read that wrong I’m sure. I didn’t say types as a concept are outdated. The specific types for this library are not currently up to date with the latest major release. Very different. The community maintains them and will Need to continue to maintain them until I choose to rewrite in Typescript. Also it’s not part of my scope to take care of because this is an open source library that anyone can use for free. If you become a top tier sponsor, then maybe I would entertain such a demand.

**Comment by baba43** [comment]
Okay, no problem. Then we will wait with the update until the community types are ready.

Thank you can keep up the great work.
