### ISSUE TITLE
isLoading false by default

### ISSUE THREAD

**Issue by benmonro** [tannerlinsley/react-query#144]
It seems to me that isLoading should be true by default.

If you have the following:

```js
const MyComponent = () => {
   const {isLoading, data} = useQuery("todos", fetchTodos);

   if(isLoading) {
        return <Spinner />;
   }
   if(!data) {
        return "You don't have any todos";
   }
   return <div>Your todos: {data}</div>
}
```
Currently in with this code you will see a flash of "you don't have any todos", followed by the spinner, followed by `Your todos: foo`.  We want our UX to be just <Spinner> followed by the data, w/out the flash of empty data content first.

As far as I could tell there's nothing in the api that allows you to set the initial state to 'isLoading' to be true.  Is there any way to accomplish this?

**Comment by danbergelt** [comment]
I'm also interested in seeing a recommended workaround for this.

I'm not sure if setting the default to true is the best course of action though. If you make a manual query, it would load a spinner when no query has been made yet.

**Comment by benmonro** [comment]
Looks like in v1 it's set as the default. Can you confirm @tannerlinsley ?

**Comment by tannerlinsley** [comment]
It will be default in v1 unless using `manual` mode, which will default to success.

**Comment by tannerlinsley** [comment]
And since changing the default would be a breaking change, we can't really change this incrementally in v0.x. You'll have to wait for v1 to get this one. ;)

**Comment by kamranayub** [comment]
I may open a new issue but this wasn't expected when passing a falsy query key. The purpose of `status === 'success'` should be to know when the query has a successful result. If it is set to `success` when manual is true or a falsy query key is passed, it's not an accurate status name because the query hasn't had a successful result.

> `success` if the query has received a response with no errors and is ready to display its data. The corresponding data property on the query is the data received from the successful fetch or if the query is in manual mode and has not been fetched yet `data` is the first initialData supplied to the query on initialization.

The docs are not entirely clear on this because the way I read this was:

- `success` if there's data after the first fetch
- `success` in `manual` mode IF there's `initialData`

But it's actually simply `success` if `manual` which wasn't expected.

I could open a new issue to propose a new status or at least to use `loading` as the default if passing a falsy query key.

**Comment by Vatsal2000** [comment]
I faced this issue when I had to set some initial data. In that case, the status was 'success' by default and isLoading was false. 
In my case, the workaround was to use **isFetching** flag instead of isLoading. isFetching defaults to true and changes to false if the status changes to 'error'.
