### ISSUE TITLE
dehydratedState.queries[0].state.data.pageParams[0] in next js

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [tannerlinsley/react-query#1528]
**Describe the bug**
in next js I want to use prefetchInfiniteQuery and :
Error serializing `.dehydratedState.queries[0].state.data.pageParams[0] in next js 

with prefetchQuery its ok but with prefetchInfiniteQuery has error .

and I check there isn't problem in data.

**Screenshots**

![Screenshot from 2020-12-27 12-01-11](https://user-images.githubusercontent.com/37307562/103166844-5ae29080-483b-11eb-9637-f5ef1aaeeb51.png)

![Screenshot from 2020-12-27 12-02-26](https://user-images.githubusercontent.com/37307562/103166851-66ce5280-483b-11eb-882e-a27c665d5568.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Version: 87

**Additional context**

**Comment by farshidshahmoradi1996** [comment]
I found solution :
but why this happean?
![Screenshot from 2020-12-27 13-02-33](https://user-images.githubusercontent.com/37307562/103167843-eb24d380-4843-11eb-94ed-e81097ba8d26.png)

**Comment by tannerlinsley** [comment]
This is an upstream bug with next js. Normally, undefined is disposed of during serialization.

**Comment by sheikharifulislam** [comment]
> I found solution : but why this happean? ![Screenshot from 2020-12-27 13-02-33](https://user-images.githubusercontent.com/37307562/103167843-eb24d380-4843-11eb-94ed-e81097ba8d26.png)

Thank you for your comments. I was looking for a solution to this problem. After writing the code given in your comment, my problem was solved.

**Comment by sheikharifulislam** [comment]
> This is an upstream bug with next js. Normally, undefined is disposed of during serialization.

So far is there any good solution to this problem ??

**Comment by TkDodo** [comment]
we have something in the pipeline for v5

**Comment by LLukkke** [comment]
The reason for my error is that axios return body obejct contains undefiend, I added an interceptor to make him return only the response data.
Hope it is helpful for you.
<img width="395" alt="image" src="https://user-images.githubusercontent.com/25702295/216609778-5eb16bf6-8f57-4675-b1c4-eb8166373c23.png">

**Comment by sheikharifulislam** [comment]
> we have something in the pipeline for v5

pageParm undefined Is there a solution to this problem at the moment?

**Comment by cross-development** [comment]
Hi! Today I had the same problem with the `useInfiniteQuery` in Next.js SSR. In my case, I used this option - `structuralSharing`. If you pass a function to this prop you can get old and new values. Log the new and old values and you can see why you have `undefined`. So, to solve this problem you should return from this function an object with the next fields:
`{ pageParams: [null], pages: newData.pages }` (or in case you want to pass a page number, instead of null you should put [1] like a first page). The `pageParams` field allows you to pass the first param which doesn't exist on the first request. And newData.pages allows you to keep your infinite scroll working on the client side. 
By the way, if you have a "Show more" button, after getting more data (page 2) you will have the next pageParams: `{ pageParams: [null, 1], pages: newData.pages }` (or `{ pageParams: [1, 2], pages: newData.pages }` in case you passed 1 like the number of the first page).
I hope the solution to this problem will not cause errors in further development))))
