### ISSUE TITLE
setQueryData not re-rendering the React Component

### ISSUE THREAD

**Issue by DaniAkash** [tannerlinsley/react-query#1535]
## Issue:
I'm running `setQueryData` to update query data while also updating the internal state of the component. This causes the component to not re-render after the change in query data

```tsx
const updater = (nextData) => {
    /**
     * Appending new task to the top of the array
     * but react component is not re-rendering...
     */
    queryClient.setQueryData("todos", (oldData) => {
      return [...nextData, ...oldData];
    });
};
```
Inside React component
```tsx
<button onClick={() => {
          updater([
            {
              id: 0,
              title: newTaskText
            }
          ]);
          setNewTaskText("new task");
        }}
      >
        Add
</button>
```

## To Reproduce
Refer the [codesandbox](https://codesandbox.io/s/queryclientsetquerydata-no-re-render-urihc?file=/src/App.tsx:1123-1356)
- Clicking on Add Task will add the new task to query data
- But you need to click add task twice to see it re-render in the UI

**Comment by TkDodo** [comment]
The issue seems to be that useState doesn’t trigger a re-render if the value in the state is the same as the current value in the state. It works just fine if you enter a different text and press the Button.

**Comment by DaniAkash** [comment]
@TkDodo the `queryClient.setQueryData` should trigger the update regardless of `useState` right?

**Comment by TkDodo** [comment]
> @TkDodo the `queryClient.setQueryData` should trigger the update regardless of `useState` right?

yes, it should and it does. if you remove `setNewTaskText` from your example completely, it updates every time you click `Add`.

I'm not really sure why the interaction of local state + setQueryData causes this behaviour 🤔 . Here would be an even more minimal reproduction of the issue: https://codesandbox.io/s/queryclientsetquerydata-no-re-render-forked-0gx3k?file=/src/App.tsx

- click the button once: in the devtools, you will see that data is now `[]`, but on the screen, it's not.
- if you remove the local setState, or set it to a different value, it works

So it seems to only occur if you have local state that is also set to exactly the value that we currently have in the state...

**Comment by DaniAkash** [comment]
Thanks @TkDodo I'm aware that removing `setNewTaskText` or calling it with new data will fix the issue. But this seems to be an edge case if it gets called with the same value. I opened the issue for that scenario only

**Comment by boschni** [comment]
After executing the `onClick` function the component is re-rendered and `useQuery` is returning the new data (`[]`). But it seems like React is discarding this render because the state did not change. After that a notification from the cache comes in, telling `useQuery` to re-render because of the new data, but because `useQuery` thinks it already rendered this data, it does not trigger an additional re-render. This was an optimization to prevent unnecessary renders, but if certain renders are discarded, then we cannot rely on it.

**Comment by DaniAkash** [comment]
Thanks @boschni. I now have a clearer picture of the issue.

**Comment by utkarshgupta137** [comment]
I hope this issue gets fixed soon as it took me quite a bit of time to debug why the components weren't re-rendering.
You can work around this by completely reconstructing the return object.
So this will work:
```
queryClient.setQueryData(queryKey, (oldData) => {
  return {
    ...oldData,
    pages: oldData.pages.map((page) => {
      return {
        ...page,
        playlistItemsList: page.playlistItemsList
          .filter((playlistItem) => {
            return !variables.includes(playlistItem.id);
          })
          .map((playlistItem, i) => {
            playlistItem.snippet.position = i;
            return playlistItem;
          }),
      };
    }),
  };
});
```
But this doesn't:
```
queryClient.setQueryData(queryKey, (oldData) => {
  oldData.pages.forEach((page) => {
    page.playlistItemsList = page.playlistItemsList
      .filter((playlistItem) => {
        return !variables.includes(playlistItem.id);
      })
      .map((playlistItem, i) => {
        playlistItem.snippet.position = i;
        return playlistItem;
      });
  });
  return oldData;
});
```

**Comment by TkDodo** [comment]
@utkarshgupta137  your example has nothing to do with the issue i believe. Please don’t mutate existing cache values but return a new object / array instead. You can also use `immer` if you don’t like the spread syntax.

**Comment by utkarshgupta137** [comment]
Oh. I assumed that an immer like interface was already provided.

**Comment by mleister97** [comment]
For anyone who is facing issues with _setQueryData not re-rendering the React Component_
I was just as desperate and in the same situation as you. What fixed the problem for me was the following: 

**Make sure you really update the data inside query client immutalbe!**

My example:
Note: You do not really need to understand the whole example, just my comment is important for you

```
queryClient.setQueryData([QUERY_KEYS.CUSTOMERS], (old) => ({
   ...(old as Record<string, unknown>),
   data: removeDigitalCheckFromCustomers(...),
}))

const removeDigitalCheckFromCustomers = (...): Customer[] => {
    const customerIndex = customers.findIndex(c => c.id === id)
    if (customerIndex === -1) return customers
    const updatedCustomers = [...customers]
    // THE NEXT LINE DOES NOT CREATE AN IMMUTABLE OBJECT !!!!!!!!!
    updatedCustomers[customerIndex].digitalChecks = { ... }
    return updatedCustomers
}
```

Use instead something like this:
```
updatedCustomers[customerIndex] = {
   ...updatedCustomers[customerIndex],
   digitalChecks: { ... }
   }
```

**Comment by TkDodo** [comment]
@mleister97 please make a PR to the docs if you think we could highlight this more

**Comment by aquibbaig** [comment]
@mleister97 I do not understand what this means 
`Make sure you really update the data inside query client immutable!`

**Comment by jackfiallos** [comment]
thanks guys, this series of posts helped me to fix an issue when deleting an item from a list of infinite items fetched using `useInfiniteQuery`.

Now I'm seeing a weird behaviour that not sure if its related or should be in a different issue and is, after updating the cache using `queryClient.setQueryData` when an item from the list is removed (re-render is triggered correctly), as soon as `refetch` is used, the deleted item is back .. is this possible, any clue what I should look for?

**Comment by TkDodo** [comment]
> as soon as refetch is used, the deleted item is back 

this sounds like the item hasn't really been deleted in the backend if a refetch brings it right back ...

**Comment by jackfiallos** [comment]
I can confirm the backend is working as intented, actually noticed this is happening to other item updates as well, like changing values to properties from true to false or viceversa, that apparently its working, because the state is updated and the changes are reflected in the frontend, but same story, with the refetch, all changes prior to my update come back.

I haven't mentioned this is a RN project with no hydratation, but shouldn't change anything, right?

Seems I need to investigate this further using a new project that I can share.

**Comment by jackfiallos** [comment]
after running some local tests with web vs mobile (using the same base code), noticed the web version was working fine all the time whereas the mobile was having something odd.

for some reason, the api call from the mobile was always re-rendering deleted items (server and from query-cache), axios apparently was doing the requests but the server never recieved the request event, so in the end, decided to add a random value to the url and this did the trick, so now everytime the refetch is triggered, the requests is received by the server and data is refreshed according to last version.

so the question now is if there's any relation between these ends (axios, react-query) and this behaviour?

thanks @TkDodo

**Comment by scottstern** [comment]
@TkDodo im having a similar issue very similar to https://github.com/TanStack/query/issues/1535#issuecomment-752029850

1. We are fetching data from the backend
2. I am storing bulk select state in local state in a provider.

I make the call to `setQueryData` and then immediately make the call to update state and it breaks for the reasons outlined in this issue.

Whats also interesting if i split the functions like so.

```
const makeCallToReactQuery = async () => {
  queryClient.setQueryData(value);
 }
 
 // another module

await makeCallToReactQuery();
setLocalState()

```

It re-renders properly if i await the call to react query OR i wrap the `setLocalState` call in a setTimeout.

Which im not happy about both.

So im wondering if something is architected fundamentally wrong and we should fix that issue instead of forcing this to work.

Thanks!

**Comment by TkDodo** [comment]
> @TkDodo im having a similar issue very similar to https://github.com/TanStack/query/issues/1535#issuecomment-752029850

The reproduction from that time is no longer "broken": It works fine in v4: https://codesandbox.io/s/queryclientsetquerydata-no-re-render-forked-0gx3k?file=/src/App.tsx

My guess is because we now `useSyncExternalStore`.

**Comment by scottstern** [comment]
> > @TkDodo im having a similar issue very similar to [#1535 (comment)](https://github.com/TanStack/query/issues/1535#issuecomment-752029850)
> 
> The reproduction from that time is no longer "broken": It works fine in v4: https://codesandbox.io/s/queryclientsetquerydata-no-re-render-forked-0gx3k?file=/src/App.tsx
> 
> My guess is because we now `useSyncExternalStore`.

Thank you so much for the quick reply and response. Will bump if im still seeing issues.

**Comment by scottstern** [comment]
@TkDodo the upgrade didnt seem to fix my issue. 

I have a virtualized table with items (fetched from react-query) and bulk update state (checkboxes when I store a list of ids in provider state)

When I select an item in the table and then delete that item

1. The cache is updated
2. Then I update the provider state to remove the item from the checked state

But it looks like the provider state update is winning every time, the component is being re-rendered and the item is undefined and breaks the ui. 

The docs say `setQueryData` is synchronous which is why ive been so perplexed.

Like in my previous comment, awaiting on the function that calls setQueryData fixes the issue but feels "dirty".

I fixed it by just guarding in the component. Tried to build a sandbox and repro but couldnt in a test env. 

Let me know if you have any thoughts or ideas.

Thanks

**Comment by codestacx** [comment]
I was facing the same issue in one of my production ready app where i was utilizing react query  a lot. Whenever, I made update with `setQueryData` it update in react query cache but doesn't update the DOM. 

It was a headache for me as I wasn't going to replace the whole logic with global state(redux/recoil/context) and not even calling API again. 

What i did is created a state 

` const [key, setKey] = useState(+new Date());`

and then use this as a key to the parent container from where I was passing down the data to children something like below

`

            <ChatUsers
              key={key}
              hasNextPage={Boolean(hasNextPage)}
              chats={chats}
              chatClick={handleClick}
              loadmore={fetchNextPage}
            />

`

`key` is actually updated when cache is updated and chats is what i am using from react query. This worked for me.

**Comment by scottstern** [comment]
@codestacx thats probably not ideal, youre forcing the key to change which is why the re-render is happening. You might have an immutability issue. Dont know if you wanna share the code in github.

**Comment by brannonvann** [comment]
@scottstern I believe I'm having the same issue outline above or at least similar symptoms. I haven't tried splitting setQueryData to another function that I await but if that were to work, I would also agree with your "dirty" comment.

In my case, I'm calling `queryClient.setQueryData` from inside an `onMutate` just like [This Optimistic Update Example](https://tanstack.com/query/v4/docs/react/guides/optimistic-updates#updating-a-list-of-todos-when-adding-a-new-todo). 

I'm returning a new Array by spreading the old one after modifying it but the new data is not triggering a state change in the component where I have the `useQuery` with the same query I'm setting in the `setQueryData`. 

Even if I trigger a render of the component through other means it's failing to trigger a useEffect which contains the data from `useQuery`. It's as if the was simply modified and returned rather than what I'm actually doing which is returning a new array.

For the time being I'm using `dataUpdatedAt` from the same `useQuery` to trigger a `useEffect` but this is a hack that gives the appearance that it's working correctly until I can figure out another solution.

**Comment by brannonvann** [comment]
Thanks @TkDodo I was witting a new comment where I discovered that. I think that's where I was going wrong. I modified my code to prevent modifying the `old` (from the example) and it's working as expected, for my case.

**Comment by vigenere23** [comment]
Thanks a lot, comment https://github.com/TanStack/query/issues/1535#issuecomment-755220909 really did it for me.

**Comment by bailout00** [comment]
I think there are two seperate issues here. I'm not manipulating the old data in any way, just completely replacing it entirely and I'm seeing the same behavior, whether I use put it in onSuccess or in the mutationFn. 

`const { data: cartItems, dataUpdatedAt } = useGetCart()
    const [cartCount, setCartCount] = useState(0)

    useEffect(() => {
        setCartCount(cartItems?.items ? cartItems.items.length : 0)
    }, [cartItems, dataUpdatedAt])`

cartItems alone will not trigger this, but with dataUpdatedAt, it works fine as mentioned above.

**Comment by sebride4988** [comment]
I hack this problem. just add property that didn't exist.

```typescript
queryClient.setQueryData(
  ['user', 'post'],
  (prev) => {
    const next = {
      user: null,
      post: null,
    };
    return {
      ...next,
      // Properties that didn't originally exist
      updatedAt: new Date().toISOString(),
    };
  },
)
```

That's it. happy programming.
