### ISSUE TITLE
[v3] Concurrent mode broken

### ISSUE THREAD

**Issue by bbenezech** [tannerlinsley/react-query#1536]
Concurrent mode useQuery re-rendering too many times bug

**To Reproduce**
https://codesandbox.io/s/interesting-architecture-g4ojv
Press `+1` a few times quickly and look at the number of renders.

Closely related to #1482

![react-query](https://user-images.githubusercontent.com/26794/103342363-9b374e00-4a89-11eb-9738-a2c3af4ec54d.gif)

**Comment by boschni** [comment]
When I set `staleTime` to `Infinity` there is 1 render when using `useState` and 2 renders when using `useDeferredValue`. I don't know the specifics of `useDeferredValue` but this behavior seems ok to me?

**Comment by bbenezech** [comment]
Sorry I should have been more precise. Render count goes up to a thousand. Press the button twice with some delay between. Might require a few tries.

**Comment by bbenezech** [comment]
Updated codesandbox link, it was using `v3.2.0` instead of latest `react-query`.

I humbly suggest you take your time with this bug, it looks **really** nasty. 😅

**Comment by bbenezech** [comment]
![react-query](https://user-images.githubusercontent.com/26794/103290342-9e7afd00-49e9-11eb-9b19-35b671c7518e.gif)

**Comment by boschni** [comment]
Maybe `useDeferredValue` should be use differently? This does seem to work: https://codesandbox.io/s/infallible-dewdney-9fkv9?file=/src/index.js . I'm not sure what the best practices are for concurrent mode as the feature is still experimental.

**Comment by bbenezech** [comment]
`useDeferredValue` works fine in my example.
But in some circumstances ReactQuery causes a **massive** number of rerenders that will bring real apps to their knees.
I am sure there is a bug in ReactQuery that must be fixed. IMO this is pretty serious.

**Comment by tannerlinsley** [comment]
Let’s keep in mind that CM is experimental still, so while it may be important and of high interest to those testing it out, it’s definitely not a serious issue or high priority. 

I want to set expectations correctly that there is zero obligation for anyone, especially core contributors, to pour hours of work into this issue unless it is something that affects or interests you directly. We will continue to monitor this issue as CM solidifies and better patterns emerge around it.

**Comment by bbenezech** [comment]
@tannerlinsley to be clear when I say "must be fixed", I mean it solely from a "product" pov, as in "the bug comes from us", I do not imply any moral obligation for anyone here ;)
And if I were, it would naturally include myself.

**Comment by tannerlinsley** [comment]
Your totally fine 👍  I triage conversations like this every day, so it’s always safer to set firm expectations, even if they are already being met :)

**Comment by boschni** [comment]
The reason why I'm suggesting that it might be because of how `useDeferredValue` is used, is that when the button is clicked twice in a certain timeframe, the deferred value seems to be alternating each render between the old value (0) and the new value (2). Which means that each render the query key is being changed, which is causing a re-render, which is then causing the query key to change, and so on. I don't know why the deferred value is alternating, but this should be out of the control of RQ. For now I can only guess that having `useDeferredValue` and a suspending `useQuery` on the same level might just not be a good combination.

**Comment by bbenezech** [comment]
Thanks @boschni ! My thoughts in random order: 
- I think this use case (use of deferred value in the component it was created) is perfectly nominal. Maybe it triggers something else complicating the case ?
- I use the deferred value in my key deep in the tree and have the same issue : I get crazy re-renders when I switch key and `useQuery` triggers a suspense. It wasn't happening with `3.2.0`
- If I remove the `useQuery` call or use a stable key, everything goes back to normal
- My uneducated guess is that it **looks** like `useQuery` re-renders with the "previous" key, somehow "invalidating" the work CR is doing, each time it switches to the other branch
- I had a very similar issue (my fault) when I left a component with deprecated lifecycle methods deep in the tree. It looks like React Concurrent can easily be put at some fault.

I think we could either try to revert the behaviour to latest working behaviour (`3.2.0`) by rollbacking/fixing the commit breaking it or we could try to understand further on what is happening inside React concurrent, maybe with some help of someone from react core ?

**Comment by tannerlinsley** [comment]
What's the status here?

**Comment by bbenezech** [comment]
@tannerlinsley https://codesandbox.io/s/wizardly-rubin-tx1hn
No changes AFAICT
Press +1 a few times, you'll get thousands of render very quickly.

**Comment by boschni** [comment]
Think I have narrowed it down to the following pattern: https://codesandbox.io/s/gallant-ritchie-o6wig?file=/src/index.js

Don't know the exact details, but my feeling is that React is rendering the component in multiple trees with different props. Because all trees share a single observer instance, the observer keeps on switching between queries and triggering state updates. This has probably been introduced by: https://github.com/tannerlinsley/react-query/pull/1449.

The main issue is that people expect the state returned from hooks like `useQuery` to immediately reflect the latest situation. Which means that if they pass in a different query key or enable/disable a query, they do not expect the state to be lagging behind. This is a reasonable expectation, but somewhat difficult to reconcile with the "renders should never have side effects" rule.

Currently the hooks are violating this rule because:

1. While rendering for the first time, a query is created in the cache if it didn't exist yet (=side effect).
2. While rendering, the observer options are updated and this triggers side effects like switching query, fetches and updating timers.

Either we'll need to find a clever way to work around the issue, or we'll need to accept that the state can lag behind the options. Will dig into it a bit more.

**Comment by tannerlinsley** [comment]
Interesting advice from @gaearon here about "pure" rendering:

https://github.com/vercel/next.js/issues/21932#issuecomment-774692639
