### ISSUE TITLE
Error state if query is reset while loading

### ISSUE THREAD

**Issue by tcrwt** [tannerlinsley/react-query#1594]
**Describe the bug**
Upon pressing 'reset' on a query while it is already loading, the error state is shown.

**To Reproduce**
1. Open react-query dev tools.
2. Click on a query in the list.
3. In the panel that opens, under 'Actions', click 'Reset'.
4. Ordinary loading behaviour should be seen.
5. Now press 'Reset' twice in quick succession.
6. An error state should be seen.

**Expected behavior**
The component should have stayed in the loading state the whole time.

**Screenshots**
Here's a sandbox: [codesandbox.io/s/i8443](https://codesandbox.io/s/i8443). 

Here's a screenshot:
> ![Jan-07-2021 15-37-05](https://user-images.githubusercontent.com/6892123/103911857-7765af00-50fe-11eb-92ac-55dafb3fc9e9.gif)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: 87.0.4280.88

Let me know if I can help at all!

**Comment by TkDodo** [comment]
I debugged this a bit. It seems that while re-setting, any active fetches will be cancelled, which makes sense. If we reset the first time, the active subscriber will be re-fetched (we can also see the transition to `fetching` in the gif). Now if we are re-fetching and reset at the same time, the ongoing fetch will be cancelled by the reset, leading to a `CancelError` in the process.

The code in question would be here:

https://github.com/tannerlinsley/react-query/blob/361935a12cec6f36d0bd6ba12e84136c405047c5/src/core/query.ts#L228-L230

Passing `silent` to `cancel` will not show cancellation errors:

```diff
  destroy(): void {
    this.clearGcTimeout()
-    this.cancel()
+    this.cancel({ silent: true })
  }
```

This works, but I'm not sure if this is totally the right fix, as it impacts every call to `destroy`. We could also forward the `CancelOptions` to `destroy` and only pass them from `reset`. This would then only impact `reset`:

```diff
-  destroy(): void {
+  destroy(options?: CancelOptions): void {
    this.clearGcTimeout()
    this.cancel(options)
  }

  reset(): void {
-   this.destroy()
+   this.destroy({ silent: true })
    this.setState(this.initialState)
  }
```

I think the first approach is fine, because I don't see that we need errors while we are destroying 🤷 - but I'll leave this for @tannerlinsley to decide - and then you can maybe do a PR and add some tests?

**Comment by tcrwt** [comment]
Thanks for looking into this! Yep, I'd be happy to put up a PR and try to add some tests (though may ask for some pointers as I've not looked at this code before), provided we're agreed this is the way to go.

**Comment by tannerlinsley** [comment]
I think for now, it would be fine to go with @TkDodo's first approach as he also recommended. If we need more control later, we can always add it. Feel free to open a PR and we can start working through it!
