### ISSUE TITLE
TContext is not inferred from onMutate

### ISSUE THREAD

**Issue by jansedlon** [tannerlinsley/react-query#1607]
**Describe the bug**
Type of TContext in `onError` is not inferred from returned value of `onMutate`

**To Reproduce**
Go to [https://codesandbox.io/s/gracious-newton-crlx9?file=/src/App.tsx](https://codesandbox.io/s/gracious-newton-crlx9?file=/src/App.tsx)

**Expected behavior**
`TContext` to be inferred from `onMutate` return value

**React-Query**
 - Version: 3.5.11

**Additional context**
I'm not sure if there's something that I'm missing but the provided CodeSandbox should be almost the same as the one from documentation.. `Optimistic Updates with Typescript`. In React-Query's codesandbox it is inferred, in my code it's not.

**Comment by TkDodo** [comment]
for some reason, you need to add types to `onMutate` so that the types are correctly inferred in `onSuccess` :/

updated example: https://codesandbox.io/s/silly-aryabhata-gnc1h?file=/src/App.tsx

I found this out while making the TS example for the docs, see the PR discussion: https://github.com/tannerlinsley/react-query/pull/1366#discussion_r538179516

**Comment by jansedlon** [comment]
Hmm.. That's really interesting. Typescript knows that type for sure but can't pass it to `TContext`. Anyway, that's much more elegant solution than mine (I was specifying the whole `context` type). Thanks! 👍
