### ISSUE TITLE
Type error with 'message' property

### ISSUE THREAD

**Issue by DoneDeal0** [tannerlinsley/react-query#1616]
**Describe the bug**
When useQuery calls a function that throws an error, typescript refuses to let me write error: error.message to format my returned object.

**To Reproduce**
```javascript
const search = async (id: string) => {
  try {
    const res = await api.post("/search/", id);
    return res.data;
  } catch (err) {
    throw new Error("error.search");
  }
};

const searchUser: UserService["searchUser"] = (id) => {
  const { data, error, isLoading } = useQuery(
    ["search", id],
    () => search(id),
    { enabled: false }
  );
  return {
    user: data && data.data,
    error: error.message, // typescript claims: Property 'message' does not exist on type 'unknown'
    loading: isLoading,
  };
};
```
**Expected behavior**
Being able to write error.message in order to return a specific error message while keeping typescript happy. 

**Desktop (please complete the following information):**
 - OS: iOS]
 - Browser: chrome
 - Version: 22

**Comment by TkDodo** [comment]
since you can throw anything in JavaScript, even (e.g. `throw 5`) and react-query is agnostic about how you fetch your data, we cannot assume anything about the Error type. So it just defaults to unknown. You can do two things:

- provide generics to useQuery:
```
useQuery<MyResultData, Error>(key, queryFn)
```
- make a runtime check with instanceof that will narrow the type:
```
const { error } = useQuery(key, queryFn)
if (error instanceof Error) {
  error.message
}
```

I have used both ways in the past. With axios, I want to specify that I get an `AxiosError` anyways (which is a subclass of Error I think), so I use the first way to type useQuery. If I'm only interested in the "generic" `error.message`, I go for the `instanceof` check, because I need a check anyways (e.g. `if (error)` or `if (status === 'error')`), so I can just as well narrow the type with instanceof.

**Comment by TkDodo** [comment]
I think this also describes it very well: https://stackoverflow.com/questions/45379959/narrowing-down-error-type-in-catch

**Comment by littlee** [comment]
Can I provide generics to global queries onError?

```ts
import { QueryClient, QueryClientProvider } from 'react-query';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false,
      onError: (err) => {
        console.log('global query onError', err.message); // Object is of type 'unknown'. 
      }
    }
  }
});
```
