### ISSUE TITLE
Allow option to transform the response body

### ISSUE THREAD

**Issue by lintuming** [tannerlinsley/react-query#17]
In some case ,the API server will give a internal code in the response body like:
```js
{
   code:"200",
   data:{},
   msg:"xxx"
}
```
It's helpful if we can transform the response body into somthing we want.
```js
useQuery('key', queryFn , {
   transform:res=>{
       if(res.code==="200")return res.data       
   }
})
```

**Comment by tannerlinsley** [comment]
You can do this in your query function, no?

Tanner Linsley

**Comment by tannerlinsley** [comment]
I think unless a very strong use-case for needing this as opposed to doing something in your query function is made, we'll hold off on this.

It's also important to remember that because the query ID is derived from the string and variables, the query function does not need to be stable or memoized. This means you can do inline functions as much as your heart desires:

```js
useQuery('key', () => queryFn().then(res => res.code === '200' ? res.data : null))
```

**Comment by lintuming** [comment]
> I think unless a very strong use-case for needing this as opposed to doing something in your query function is made, we'll hold off on this.
> 
> It's also important to remember that because the query ID is derived from the string and variables, the query function does not need to be stable or memoized. This means you can do inline functions as much as your heart desires:
> 
> ```js
> useQuery('key', () => queryFn().then(res => res.code === '200' ? res.data : null))
> ```

Thx for the answer.
