### ISSUE TITLE
How to handle websocket live data?

### ISSUE THREAD

**Issue by MContagious** [tannerlinsley/react-query#171]
Can you explain or create an example to handle websocket a like live data?

**Comment by tannerlinsley** [comment]
Adding that to the docs was a little premature. I'm still working on the `useStreamQuery` hook, so it'll be a bit before it's available. Essentially it will behave more like an event emitter/handler than a promise-based one. Stay tuned.

**Comment by joserocha3** [comment]
Hi @tannerlinsley, thanks for this awesome library. I am considering switching to this but we will be needing the `useStreamQuery` hook. Has progress been made on this or is there anything I can do to help?

**Comment by joserocha3** [comment]
Hello there @tannerlinsley, any update on `useStreamQuery`. I am still willing to help out if help is needed. Thanks!

**Comment by tannerlinsley** [comment]
After a lot of consideration and playing around with this concept, I don't believe it belongs in this library. I would be happy to help anyone build it for their own use cases, but it will not be making a first-class appearance in React Query for the time being.

**Comment by joserocha3** [comment]
Thanks for considering it @tannerlinsley. 

My specific use case is for GraphQL subscriptions coming from a Hasura instance. Any pointers or direction to help jump start would be great.

**Comment by tannerlinsley** [comment]
I think subscriptions would be treated a lot like an event from a socket. it would be created normally and used to either invalidate queries or mutate the cache with the payload. No need to useQuery at all!

**Comment by dan-klasson** [comment]
> After a lot of consideration and playing around with this concept, I don't believe it belongs in this library. I would be happy to help anyone build it for their own use cases, but it will not be making a first-class appearance in React Query for the time being.

I'd have to disagree with you there. Rolling your own subscription library will be frowned upon by most people in my opinion. Unfortunately, there aren't any good graphql subscription libraries out there, that I know, other than Apollo. People who require subscriptions are going to have a hard time selling the idea of switching from Apollo to React Query. Which is a shame because React Query is clearly the better library.

**Comment by tannerlinsley** [comment]
I hear you that the subscription  library world is super sparse and janky if you ask me. Let me elaborate on a few more things that might help this discussion be more targeted.

Apollo only "supports" subscriptions because they have a unified API on how subscriptions are interpreted (GraphQL) and the expectations behind them. Even so, Apollo (and just GraphQL) subscriptions for that matter still need an implementation layer that adheres to the spec, but actually powers the transactions. This is where there are GQL subscription plugins and layers made in sockets, http polling, grpc, etc.  With that said, React Query doesn't force a spec upon you, and thus we cannot provide first class subscription plugins and implementors like Apollo does. This doesn't mean that it's not possible to use subscriptions (as a general concept) with React Query, but it does mean that you would have a different implementation for every combination of technology, eg. the Nozzle app uses sockets via Pusher and a custom hook that calls `queryCache.invalidateQueries` or `queryCache.setQueryData` from the events received. Once you change the socket implementation, the event shape/interface, or even what you ID your queries with, the entire custom hook changes.

**Comment by tannerlinsley** [comment]
So in essence, there is nothing stopping you from doing this:

```js
React.useEffect(() => {
  const unsub = socket.on('crud', (event) => {
    if (event.id) {
      queryCache.invalidateQueries([event.kind, event.id]) // [todo, 23]
    } else {
      queryCache.invalidateQueries(event.kind) // todo
    }
  })

  return unsub
})

```

**Comment by revskill10** [comment]
Maybe not related to `react-query`, but to answer to @joserocha3 question, as well as adding to @tannerlinsley  comment, here's my custom hook i'm using to use live data from Hasura specifically:

```js
import useClient from "utils/hooks/useClient";
import { useEffect, useState } from "react";
import useQuery from "utils/hooks/useQuery";
import useGql from "utils/hooks/useGql";
import useError from "utils/hooks/useError";
import useRouter from "utils/hooks/useRouter";

const defaultVariables = {
  where: {},
  offset: 0,
  limit: 10,
  order_by: []
};

const useLiveQuery = (
  url: UrlConfig,
  key: string,
  fragment: any,
  variables: any = defaultVariables,
  single: boolean = false,
  onData?: any,
  _context: any = {}
) => {
  const { query: qs } = useRouter({});
  const limit = qs.per_page ? Number(qs.per_page) : 10;
  const { query, subscription } = useGql(key, fragment, single);
  const client = useClient(url);
  const vars = {
    limit,
    ...variables
  };
  const json = useQuery(url, query, vars);
  const [state, setState] = useState(json);
  const [dispatchError] = useError();
  client.writeQuery({
    query: subscription,
    variables: vars,
    data: json
  });

  useEffect(() => {
    const querySubscription = client
      .subscribe({
        query: subscription,
        variables: vars,
        fetchPolicy: "cache-first"
      })
      .subscribe({
        next({ data }: any) {
          // Notify your application with the new arrived data
          if (onData) {
            onData(data)
          }
          client.writeQuery({
            query,
            variables: vars,
            data
          });
          setState(data);
        },
        error(err: any) {
          console.log("hehehe");
          dispatchError(new Error(err));
        }
      });
    return () => {
      querySubscription.unsubscribe();
    };
  }, [vars.where, vars.order_by, vars.limit, vars.offset, vars.distinct_on]);

  return state[key];
};

export default useLiveQuery;
```

The idea remains the same:

- Fetch your data with normal `useQuery`
- Write to the cache
- Use subscription to invalidate the cache.
- Notify the component with new live data if any.

**Comment by joserocha3** [comment]
@revskill10 are you using Apollo as your `client`?

**Comment by lishine** [comment]
@revskill10 would you please elaborate - how you combine Apollo, react-query and Hasura subscriptions and why?

**Comment by revskill10** [comment]
@joserocha3 Yes, i'm using apollo client.

**Comment by gj1118** [comment]
Hey @tannerlinsley - I hope you are doing well. I appreciate and acknowledge your judgement of not adding subscription support , but I will also totally and wholeheartedly appreciate if you can provide a somewhat detailed example of how to use `react-query` with subscriptions. I have spent days and days of removing `Apollo` from the server side and the client side. The code is very minimal and `React-query` just works out of the box. Hence this request. I hope you will understand my predicament and do the needful to help dumb people like me. 

Thank you so much for your time and patience. Apologies for reviving a old thread. 

Thanks

**Comment by PaulKujawa** [comment]
@gj1118 this is probably really bad and in this case I apologise upfront, but maybe [this little function](https://github.com/PaulKujawa/react-query-playground/blob/main/client/src/repositories/books.tsx#L22-L52) I wrote some days ago can give you an idea. It's pushing items received from websocket.io into the beginning of a list cached by react-query. But this scales probably only so much. So shared for what is it worth 🙂 .

**Comment by saeedghasemi72** [comment]
Hi guys, I read comments but i'm don't understand how to use react query with live data in socket .
I use react-query with actioncable for handle socket data, I can't use useMutate and useQuery because that didn't return any data, and I can't use setQueryData because this method not observable and my component didn't get new data. :(
please help me

**Comment by TkDodo** [comment]
have you read:

https://tkdodo.eu/blog/using-web-sockets-with-react-query

**Comment by saeedghasemi72** [comment]
@TkDodo Yeh I Read this blog, and thank you for this awesome articles, but I think that can't help me.
all of my data come from socket therefore invalid query and other solution that related to api call can't help me.
and when I use setQueryData and  data in other side when getQueryData I can't get updated data becuse this not subscription method

**Comment by TkDodo** [comment]
If you don't have a regular rest api endpoint, don't try to integrate it with react query I'd suggest

**Comment by saeedghasemi72** [comment]
@TkDodo Yeah, that's an idea, but I want use a trick, instead setQueryData I want use useQuery with an empty promise function, with this solution I have last data that from socket, what you think?

**Comment by sukalov** [comment]
> It's

the 'little function' is gone :(
