### ISSUE TITLE
placeholderData not applied when query is disabled

### ISSUE THREAD

**Issue by timtnleeProject** [tannerlinsley/react-query#1749]
**Describe the bug**
When there're query dependent, the last query:
1. `placeholderData` not applied until the query is fetching.
2. `isLoading` never triggerd.

**To Reproduce**
online sandbox:
https://codesandbox.io/s/react-query-issue-et8hs?file=/src/index.js

I have two querys: `auth`, `getUserDetail`.
 `getUserDetail` depends on `auth`.

The fetching order will be: `auth` -> `getUserDetail`.

`placeholderData` of `getUserDetail` is set to "placeholder"

1. when `auth` is fetching, the `placeholderData` of `getUserDetail` is `undefined` (BUG ?).
2. when `getUserDetail` is fetching, the `placeholderData` of `getUserDetail` is "placeholder" .
3. `isLoading` of `getUserDetail` is never been `true` (BUG ? I want to make sure this is expect behavior.).

**Expected behavior**
1. `placeholderData` applied at start (isIdle).

**Desktop (please complete the following information):**
 - Device: [PC]
 - OS: [Win10]
 - Browser: [edge(chromium)]

**Additional context**

**Comment by boschni** [comment]
Do we also want to show the placeholder data when a query is not enabled @tannerlinsley?

**Comment by TkDodo** [comment]
> Do we also want to show the placeholder data when a query is not enabled @tannerlinsley?

Good question. Since placeholder data is meant to be “incomplete” data that never goes into the cache, i would say yes. How is initialData handling this case? I think it also works on disabled queries, but I’m not sure it should 🤔 See also here maybe: https://github.com/tannerlinsley/react-query/discussions/1318

**Comment by tannerlinsley** [comment]
Generically, I would expect `placeholderData` to populate and function as expected on disabled queries and `initialData` to not.

**Comment by mwisnicki** [comment]
I also expected placeholderData to be returned in this case.
BTW once you do that you can drop `unknown` from TData when placeholder is set.

**Comment by TkDodo** [comment]
> Generically, I would expect placeholderData to populate and function as expected on disabled queries and initialData to not.

@tannerlinsley since `initialData` is persisted to the cache, we currently apply it when the queryCache entry is created, which also happens for disabled queries. Also, a query can't really be enabled or disabled, only observers can (you can have two observers on the same query, one being enabled and one disabled). So I'm not sure if this would be doable, and it also goes a bit against my understanding of initialData...

> I also expected placeholderData to be returned in this case.

Yes it makes sense. Would you like to take a stab at it?

> BTW once you do that you can drop unknown from TData when placeholder is set.

You likely mean `undefined`, and that is not an easy thing to do, because you can define all options also on the QueryClient as defaults, or via `queryClient.setQueryDefaults` for a specific query. Ignoring this, and only making it work on type level for  `useQuery` directly, you still have the case where you define `placeholderData`, but the query that fetches in the background errors. In this case, the query will go to `error` state and `placeholderData` will no longer be applied, so you're back to `undefined` data. I think only `initialData` can solve this, and we could take a stab at improving the types there.

**Comment by TkDodo** [comment]
could it be as easy as adding `|| status === 'idle'` here after we check for loading state?

https://github.com/tannerlinsley/react-query/blob/69b0c9857c04ab77eb394c416454650ba5963fc9/src/core/queryObserver.ts#L494-L499

🤔

**Comment by TkDodo** [comment]
> IMHO placeholderData should be returned in all cases where there is no valid data. That includes errors.
Such behavior would match basic implementation of of fetching with state hooks.

imo that is what initialData is for. placeholderData moves the loading query directly to success state and we can’t do that in case of error. It would be a substantial change to how placeholderData works

**Comment by mwisnicki** [comment]
Are you sure? How can placeholderData move query to success if it is supposed to be returned while query is executing (therefore no success yet)?

**Comment by TkDodo** [comment]
Well internally, it stays in loading because placeholderData only concerns the observer that uses it. But when placeholderData is supplied, the status on the returned result will be success. This happens here:

https://github.com/tannerlinsley/react-query/blob/a7780444bb0bdd0e7a768c6ebc57e04aea5f7c51/src/core/queryObserver.ts#L533-538

**Comment by mwisnicki** [comment]
Seems very counterintuitive

**Comment by TkDodo** [comment]
What alternative would you suggest? We can’t keep it in loading state with data because loading state implies that you have no data. placeholderData is a "fake" success because it gives you data so that you can fake-it-till-you-make-it on screen. And if the query fails you go to error with no data, because you didn’t make it.

**Comment by mwisnicki** [comment]
I would totally expect that loading state and data are not exclusive.

I'm not really that familiar with this library but back in the day when did a lot of desktop apps every component library would work that way (they would also expose separate property for fetched data if you needed it).

Also that matches basic behavior of state based fetching.

**Comment by mwisnicki** [comment]
Another surprise for me is that data contains body of error response. Not sure if I should file an issue about that or I just expect too much from data prop.

**Comment by mwisnicki** [comment]
Ignore last comment. I was experimenting and left some wrong code.

**Comment by mnpenner** [comment]
I just started using react-query today and this caught me off guard. I figured `placeholderData` would be used even when the query was disabled as well. Glad to see there's an incoming PR.

However, I'm still concerned about bypassing the `isLoading` state. Why is the initial state "success" if it hasn't successfully fetched anything yet?

Here's my use-case:

![image](https://user-images.githubusercontent.com/1112998/128657826-d6d92ef1-88e3-4eff-bc3f-a9226280461f.png)

I've got two drop-downs; the 2nd one depends on the 1st. When you choose a "Twilio Subaccount" it should load the phone numbers for that account. I have the phone number query set to disabled until you choose an account. I also tried using `placeholderData` to initialize the phone numbers to an empty array to simplify my code (so I don't have to check if `data` is undefined or not everywhere). The phone number field also shows a little loading animation when it's in the `isLoading` state.

So what I expect to happen is that whenever the user chooses a new Twilio Subaccount the phone number field goes into the `isLoading` state to hint them that it's still populating, unless they pick an account that's already in the cache then it will quietly load that data and update the list if it's changed.

But the way it is now I lose that loading animation if I use if I use `placeholderData`. Alternatively, I have to litter my code with `?.`, `??` and `?:` to handle the undefined data which is much less legible and will probably scale even worse if I was using anything more complicated than an empty array.

**Comment by TkDodo** [comment]
> However, I'm still concerned about bypassing the isLoading state. Why is the initial state "success" if it hasn't successfully fetched anything yet?

That is per design. `success` means there is data to display, while `loading` should indicate that you have nothing to display, so you need to show a loading spinner.

In your situation you'd likely want to show your little loading animation depending on the `isFetching` flag, which will be true for every outgoing request. Alternatively, you can use the `isPlaceholderData` flag which will be true for as long as react-query is showing the placeholder data.

**Comment by mwisnicki** [comment]
Which properties should is set such that data is **always** set to something (whether it's not loaded yet or load failed) but nothing is cached except the result of successful query?

Which single property says that data was fetched successfully?

**Comment by TkDodo** [comment]
> Which properties should I set such that data is always set to something (whether it's not loaded yet or load failed) but nothing is cached except the result of successful query?

`placeholderData`

> Which single property says that data was fetched successfully?

`isFetched` will be `true` if you have either `data` or an error. `data && !isPlaceholderData` will tell if you if you have data that is not placeholder data, which in turn means it's "real" data.

**Comment by mnpenner** [comment]
I think what I want is `query.isLoading || (query.isFetching && query.isPlaceholderData)` then. It would be nice to have a property for this so we don't have to repeat that logic everywhere. Something like `isLoadingRealData`.

It would also be nice be nice if `data` was still populated even when there's an error if `placeholderData` is set (like https://github.com/tannerlinsley/react-query/issues/1749#issuecomment-892115834). I wouldn't matter to anyone who already has an `if(query.isError)` or `if(query.error)` block because those properties would still be populated, it just helps so that you never need to handle undefined data.

Although it still seems odd to me that `isSuccess` means "has data" not "the query was successful" and `isLoading` means "there's no data" not "we're loading the data".

**Comment by TkDodo** [comment]
> I think what I want is query.isLoading || (query.isFetching && query.isPlaceholderData) then. It would be nice to have a property for this so we don't have to repeat that logic everywhere. Something like isLoadingRealData.

if you have placeholder data, you can't be loading. If isPlaceholderData is true, you are also fetching (unless you disable the query). So I think either using only `isPlaceholderData` or `isFetching` for showing background loading indicators is sufficient.

> It would also be nice be nice if data was still populated even when there's an error if placeholderData is set (like #1749 (comment)). I wouldn't matter to anyone who already has an if(query.isError) or if(query.error) block because those properties would still be populated, it just helps so that you never need to handle undefined data.

if that's what you want, why not use `initialData` ? Or, you can just do:

```
const { data = myPlaceholderData } = useQuery(...)
```

which will make any undefined data be myPlaceholderData instead. 

> Although it still seems odd to me that isSuccess means "has data" not "the query was successful" and isLoading means "there's no data" not "we're loading the data".

A successful query is a query that has data in the cache. How it got there doesn't matter. If you call `queryClient.setQueryData()` and manually prime the cache, it will also be successful. Why should it be loading in that case? It's successful, and potentially in `isFetching` state to indicate a background update. Actually, react-query doesn't even know how the data got in the cache. Could be via `initialData`, could be via `prefetching` or via `setQueryData` or via a different component that called `useQuery` before you and thus fetched data successfully.

**Comment by mwisnicki** [comment]
> > Which properties should I set such that data is always set to something (whether it's not loaded yet or load failed) but nothing is cached except the result of successful query?
> 
> `placeholderData`
> 

But that's not really true, is it? I'll need to retest it but according to other posts here, `data` won't be set in case of error even if there is `placeholderData`.

> > Which single property says that data was fetched successfully?
> 
> `isFetched` will be `true` if you have either `data` or an error. `data && !isPlaceholderData` will tell if you if you have data that is not placeholder data, which in turn means it's "real" data.

Would be nice to have single property for common use case.

**Comment by TkDodo** [comment]
> But that's not really true, is it? I'll need to retest it but according to other posts here, data won't be set in case of an error even if there is placeholderData

Yes, if you have an error, you don't get placeholder data. placeholder data "holds the place" until either real data or a real error comes back from the api request. It's something you can display _instead_ of the loading spinner you would usually display in these cases.

> so I'll actually need something like data ?? placeholderData.

If you just want never undefined, I'd do:

```
const { data = myPlaceholderData } = useQuery(...)
```

basically coercing `undefined` to the placeholder data. I personally don't think it makes much sense though to display it even if there is an error. If that's the case, how do you distinguish it from real data? It looks more like you have some data you want to always no matter what, which again sounds more like initialData to me. But we're going in circles.

I've written a blogpost yesterday about those differences, maybe it helps someone: https://tkdodo.eu/blog/placeholder-and-initial-data-in-react-query

**Comment by mwisnicki** [comment]
The point of always having some data is that I don't have to handle undefined anywhere. Especially with arrays I can do whatever processing as usual without caring whether there is any data. I can also display it without caring about that too. A lot of the time this is good enough. It's the same reason why people use monads.
Iff I want to do something special for errors then I will check if there are any errors.

There is no reason to cache fallback data and also sometimes I might need to know whether data is fallback/default/placeholder or not (e.g. to style it differently) and with initialData that is lost.

**Comment by mnpenner** [comment]
re: https://github.com/tannerlinsley/react-query/issues/1749#issuecomment-895856195

> if you have placeholder data, you can't be loading. If isPlaceholderData is true, you are also fetching (unless you disable the query).

That's the point. There's too many caveats. I don't want my logic to change depending on whether or not I've set the `placeholderData` or disabled the query. I want one flag that works the same everywhere.

```
const { data = myPlaceholderData } = useQuery(...)
```

That might solve my `undefined` data problem nicely actually. Thanks. I don't think it works so well when I want back an object, not destructured vars. (When you use 2 or more queries in 1 component, destructuring gets ugly)

> A successful query is a query that has data in the cache. 

Isn't that inconsistent with what you said https://github.com/tannerlinsley/react-query/issues/1749#issuecomment-894956693? I thought `placeholderData` *doesn't* put data in the cache. That's what [the docs say](https://react-query.tanstack.com/guides/placeholder-query-data). Yet, if you set the `placeholderData` the query will be in "success" state even before the cache is populated.

> If you call `queryClient.setQueryData()` and manually prime the cache, it will also be successful. Why should it be loading in that case?

It wouldn't be `isLoading` because it's not fetching. `isSuccess` makes sense there. Perhaps I should rephrase "the query was successful" to "the query successfully returned non-placeholder data"; whether it's from the cache or a fetch isn't the important bit.

> Actually, react-query doesn't even know how the data got in the cache. Could be via initialData, could be via prefetching or via setQueryData or via a different component that called useQuery before you and thus fetched data successfully.

That all sounds fine. If it got into the cache, `isSuccess` makes sense. But `placeholderData` is not cache data AFAIK.

---

re: https://github.com/tannerlinsley/react-query/issues/1749#issuecomment-896115286

> I personally don't think it makes much sense though to display it even if there is an error. 

We can do both. i.e. display a skeleton page *and* an error message to indicate it's never going to load. But if the `placeholderData` gets wiped, so does our skeleton.

> If that's the case, how do you distinguish it from real data?

However the developer desires. If we're rendering a skeleton or lorem ipsum, it's probably obvious the data isn't real. Plus they should render a spinner (which is why I'd prefer if `isLoading` were `true`)

>  It looks more like you have some data you want to always no matter what, which again sounds more like `initialData` to me.

@mwisnicki said it better; https://github.com/tannerlinsley/react-query/issues/1749#issuecomment-896137668

**Comment by mwisnicki** [comment]
> I think the idea behind going into `success` state directly is so that you can treat it as any other data in your component. If we change that to be in `loading` state, every component breaks that is implemented like:
> 
> ```
> function Component({ someDataThatIsPotentiallyUndefined }) {
>   const { isLoading, data } = useQuery(key, fn, { placeholderData: someDataThatIsPotentiallyUndefined })
> 
>   if (isLoading) return <LoadingSpinner />
> 
>   ... do something with data ...
> }
> ```
> 
> because it would just always show the loading spinner, even if we have defined placeholderData.

Why? When data is loaded, `isLoading = false` and there is no spinner.

> 
> I can get behind the idea of keeping placeholderData in case of error. if the status stays `error`, checking for it will show the error. But it would break the same way if we code our component the other way around:
> 
> ```
> function Component({ someDataThatIsPotentiallyUndefined }) {
>   const { data, error } = useQuery(key, fn, { placeholderData: someDataThatIsPotentiallyUndefined })
> 
>   if (data)  ... do something with data ...
>   if (error) showError
>   
>   return <LoadingSpinner />
> }
> ```

That very much depends on how you define meaning of `data`. If you define it the way I and @mnpenner want it (which IMHO is more intuitive) then this snippet is just bad code.

**Comment by mnpenner** [comment]
> Btw, I think it's the same that `keepPreviousData` is doing. If we go from one page to the next, we keep previous data and show it while we are transitioning to the next page. If that next page fetch errors, why should we keep showing the data from the previous page? It's like a placeholder for the fetch of the next page, until it finishes. Once it's finished, successfully or not, the placeholder vanishes.

I'm on the fence about what the correct behavior for that scenario is. You could either wipe the previous data and reset it back to `placeholderData` if it exists, or keep the previous data. Either way, you'd want to handle the error. I don't think it would be terrible from a UX perspective to leave the previous page of data on the screen and splash an error message over top to say "Failed to load next page" or something of the sort -- wiping the page clean would only create more jitter. Let the developer decide what they want to do; as long as both `error` and `data` are populated they have the choice.

>  If we change that to be in loading state, every component breaks ...

Ya, unfortunately I believe that's true. Both changing the definition of `isLoading` and whether or not `data` is populated with `initialData` when there's an error are potentially backwards-incompatible changes. Unless you guys are planning a v4 soon I think the only way to release this change safely would be with a new config option.

**Comment by TkDodo** [comment]
> Why? When data is loaded, isLoading = false and there is no spinner.

I'm talking about the example where we provide `placeholderData` and the queryInfo returned from `useQuery` would be:

```
{ status: 'loading', data: thePlaceholderData, isPlaceholderData: true, error: undefined }
```

because that's what you are proposing right? Just to be clear, this is what you currently get in that scenario:

```
{ status: 'success', data: thePlaceholderData, isPlaceholderData: true, error: undefined }
```

The difference being that we go to `success` state for this observer, temporarily. If we didn't do that, we would have to stay in `loading` state, in which case my shown snippet that checks for the loading state at first would not render the placeholderData, but the loading spinner.

**Comment by mnpenner** [comment]
I *think* I can 'fix' it like this on my end:

```ts
export function useFixedQuery<TQueryFnData = unknown, TError = unknown, TData = TQueryFnData, TQueryKey extends QueryKey = QueryKey>(queryKey: TQueryKey, queryFn: QueryFunction<TQueryFnData, TQueryKey>, options?: UseQueryOptions<TQueryFnData, TError, TData, TQueryKey>) {
    const query = useQuery(queryKey, queryFn, options)
    if (query.data === undefined && options?.placeholderData !== undefined) {
        query.data = resolveValue(options.placeholderData)
        query.isPlaceholderData = true
    }
    if(query.isSuccess && query.isFetching && query.isPlaceholderData) {
        query.isLoading = true
        query.isSuccess = false
        query.status = 'loading'
    }
    return query
}
```

Hope I'm not missing anything.
