### ISSUE TITLE
What is the idiomatic approach to composing custom hooks with queries performantly?

### ISSUE THREAD

**Issue by tranhl** [tannerlinsley/react-query#183]
I'm currently using `react-query` to move away from using React Redux and Redux Saga to handle data fetching. An example of this is fetching a list of products from an API, and then displaying them in a list:

```js
function useProducts() {
	const {data, status, error} = useProducts('products', fetchProductEntities)
	return {productEntities: data, productList: Object.values(data), status, error}
}
```

My goal is to compose a new custom hook using `useProducts()` to obtain the data of a single product. This is necessary as products are children of other entities, and we optimize the number of HTTP requests required by fetching all products in one request:

```js
function useProduct(id) {
	const {productEntities} = useProducts()
	return productEntities[id]
}
```

The problem with this approach is that any component that calls `useProduct(id)` will re-render when the `'products'` query refetches. Ideally I'd like to optimize this by not re-rendering a component if the product ID doesn't change.

What is the best way to solve this problem using `react-query`? Or is this a consumer facing problem and isn't a part of `react-query`'s use case?

**Comment by tannerlinsley** [comment]
The result will be memoized to the granularity of your refetch rate. Refetching happens due to:
- Window refocus (on by default, you can disable this)
- New instances of a query mounting (on by default, you can disable this)
- Refetch Intervals (optional)
- Manual calls to `queryCache.refetchQueries()`

Incremental Steps you can take to make an asset refetch less:
- Increase the `staleTime` from `0` (the default). This will make it so automatic attempts to refetch are suppressed until the query is marked as stale from the last successful update
- Turn off refetching on mount with `refetchOnMount: false` either globally or per-query
- Turn of window refocusing

Each of these operates at different levels within React Query but with all of them together you should be able to find a good balance for how often to refetch your assets.

Further advice, if you *still* can't find a decent balance, then it's likely time to consider adding an endpoint to your api for individual resources so you can consume and cache them with better granularity.

**Comment by tranhl** [comment]
Thank you so much for the in depth explanation. I'll take all your points into consideration while I try and find a middle ground. I believe this answers the question so I'll be closing the issue.
