### ISSUE TITLE
Change of behaviour with `keepPreviousData` and `initialData` between v2 and v3

### ISSUE THREAD

**Issue by nygardk** [tannerlinsley/react-query#1859]
From my point of view this is a bug, but it could also be something that just happened to work accidentally with v2 but no longer with v3.

I made a minimal example to reproduce the issue:
[Here](https://codesandbox.io/s/focused-bush-bd1qu?file=/src/App.tsx) how it's working with v2.
[Here](https://codesandbox.io/s/friendly-cori-dxiev?file=/src/App.tsx) how it's working with v3.

With v3 that configuration will not effectively change the `data` when toggling between the states. With v2 it works as expected (except that "b initial" state is not shown, but I can remotely understand that due to `keepPreviousData: true`. Unfortunately this change in behaviour broke a feature in our app.

Please let me know if the configuration is valid in the first place. In the actual app we want:
* Provide different initial data for every key. Initial data could also be undefined.
* Keep the previous data (in case the initial data is undefined for a new key).
* Infinitely cache the data for every key. The cached data can be the initial data or loaded data, whichever happens to be available.

If this is not something that you're not even intending to support, I'm also happy to consider a workaround to fix the issue we have.

**Comment by TkDodo** [comment]
v3 looks more correct than v2 😅 .

`initialData` now respects `staleTime`, while in v2, you had to provide an `initialStale` boolean. Since you set staleTime to Infinity, your initialData is considers as always fresh.

if the key changes, I would expect the `initialData` function to be executed again, but this might not happen because of `keepPreviousData`.

The thing is: `initialData` is persisted to the cache, so it is treated "like data that is returned from the api". if you change your v3 example from `initialData` to `placeholderData`, you will see  that:

- it starts with `a initial`
- goes to `a loaded`
- click the button: it stays on `a loaded` because of keepPreviousData
- transitions to `b loaded` after 1 second

which I think is correct and probably more what you want / expect :)

> Keep the previous data (in case the initial data is undefined for a new key).

for this, I think you would need to calculate your initialData up front and set `keepPreviousData` accordingly.

**Comment by nygardk** [comment]
Thanks @TkDodo !

Yes, it seems that using `placeholderData` will result in behaviour that I want 🙂! I'm happy with that as a fix.

However, I'd still argue that either the [v3 behaviour](https://codesandbox.io/s/friendly-cori-dxiev?file=/src/App.tsx) is either incorrect or very counter-intuitive.

```tsx
 const { data, isLoading } = useQuery(
    state,
    async () => {
      await wait(1000);
      return `${state} loaded`;
    },
    {
      keepPreviousData: true,
      initialData: `${state} initial`,
      staleTime: Infinity
    }
);
```
With the configuration above, I would expect `staleTime` to affect separately every key. In other words, if query key is `a` initially, `b` would still have no data and thus it should be stale even if `a` is not. I would definetely expect `b initial` to appear in the sandbox I provided 🙂 . I'm happy to hear a counter argument to this, as I might be thinking wrongly about it 😅 .

**Comment by TkDodo** [comment]
Yeah, i think you’re right. There seems to be an issue somewhere between those 3 options. If you remove `initialData`, it will transition to `b:loaded` correctly once you receive the data.
@tannerlinsley what do you think?

**Comment by SolidZORO** [comment]
ye, same problem. if `keepPreviousData: true`,  `isLoading` doesn't work.

**Comment by cristi-shoreline** [comment]
Not sure if this is an issuer or not, but it seems that with `keepPreviousData: true` it's re-fetching again even it was within the fetch was done within the `refetchInterval`. 🤔

**Comment by garthenweb** [comment]
This unfortunately causes serious issues on my application. I would also consider it a bug as `useQuery` works different with and without an `initialState` if `keepPreviousData` is used. Is there any update on this topic?

The workaround using `placeholderData` also didn't really work for me as it flashes a loading state after hydration from the server.

I checked the code and found this: https://github.com/tannerlinsley/react-query/blob/c3434575a1221a33ed9684f87ef961f7df5adeb4/src/core/query.ts#L480-L512

`dataUpdateCount` is checked here to return the previous state: https://github.com/tannerlinsley/react-query/blob/e42cbc32dfcd9add24cadd06135e42af1dbbc8ad/src/core/queryObserver.ts#L451-L461

If we toggle `dataUpdateCount` in the initial state definition to `hasData ? 1 : 0` this is exactly what I want.

But this test fails after the change: https://github.com/tannerlinsley/react-query/blob/c3434575a1221a33ed9684f87ef961f7df5adeb4/src/react/tests/useQuery.test.tsx#L1463-L1488

Without a `staleTime` the test case makes perfectly sense to me as we expect the initial state to be replaced soon.

But with a `staleTime` this might not be true, we might never see an update again.

I would love to have some feedback on the solution. If this goes into the right direction I am happy to create a PR.

**Comment by guilhermefront** [comment]
> 
> 
> ye, same problem. if `keepPreviousData: true`, `isLoading` doesn't work.

`isLoading` is only true if there's no data, so when you use with keepPreviousData it will never be triggered as data is keeped.

You should use `isFetching` instead

See example comparing both isFetching and isLoading with pagination:
https://codesandbox.io/s/isloading-vs-isfetching-when-using-keeppreviousdata-wpwfw?file=/pages/index.js

**Comment by TkDodo** [comment]
> With the configuration above, I would expect staleTime to affect separately every key. In other words, if query key is a initially, b would still have no data and thus it should be stale even if a is not. I would definetely expect b initial to appear in the sandbox I provided 🙂 . I'm happy to hear a counter argument to this, as I might be thinking wrongly about it 😅 .

so I thought about this some more, and I think it's mainly an unfortunate configuration / misconfiguration. Whatever we do, it might come off as weird in either case: we can only show one data, so we have to decide if `keepPreviousData` or `initialData` takes precedence. judging from the existing test case:

```
 it('should not show initial data from next query if keepPreviousData is set', async () => { 
```

it seems that `keepPreviousData` should take precedence, which it does. since your example uses `keepPreviousData`, i assume that you'd likely only want the `initialData` for the first query key, so if we change that to:

```
initialData: state === "a" ? `${state} initial` : undefined,
```

[sandbox](https://codesandbox.io/s/vigorous-volhard-dj0vy?file=/src/App.tsx:650-710)

it works fine.

> The workaround using placeholderData also didn't really work for me as it flashes a loading state after hydration from the server.

@garthenweb can you provide a codesandbox example for this behaviour in a separate issue, I don't think that we should see a flash of loading state here, especially if using `initialData` does not show that flash ...

---

I'm gonna close this as wontfix because we have two workarounds (conditional initial data or using placeholderData) and priorizing initialData over keepPreviousData does not seem correct.

**Comment by ericbiewener** [comment]
@TkDodo your example of conditional `initialData` is so trivial because the `queryKey` is just a string. For more complex query keys that include variables, the solution becomes substantially more complicated:

```tsx
import { hashQueryKey, QueryKey } from "@tanstack/react-query";
import { useMemo, useRef } from "react";

const useHasQueryKeyChanged = (queryKey: QueryKey) => {
  const originalQueryHash = useMemo(() => hashQueryKey(queryKey), []);
  const hasChanged = useRef(false);
  if (!hasChanged.current) {
    hasChanged.current = originalQueryHash !== hashQueryKey(queryKey);
  }
  return hasChanged.current;
};
```

We want to use RQ's `hashQueryKey` since we want to make sure we are performing the same assessment as RQ on whether the query key has changed.

Not sure if this indicates a feature gap that RQ wants to restore. At the very least I thought this might be helpful for others who come across this issue.

**Comment by garthenweb** [comment]
For the record:

This example demonstrates this issue a bit better: https://codesandbox.io/s/compassionate-mestorf-3hwjl2?file=/src/App.tsx

You can see that the workaround does not work in case the initial state was changed at some point. I still consider this an issue in version 3 of react query. Therefore my team worked around it by setting the state again on mount:

```javascript
const queryClient = useQueryClient();
useEffect(() => {
  queryClient.setQueriesData(key, (state) => state);
}, []);
```

@ericbiewener Potentially this could do the trick for you as well?!

Please note that this comes with a performance overhead, especially if many react query instances with the same key are rendered.

Gladly, when upgrading to v4, this example works as expected. So the case I reported is fixed in the latest version of react query🎉
