### ISSUE TITLE
About Infinite Queries and useInfiniteQuery hook

### ISSUE THREAD

**Issue by tianleiyiji123** [tannerlinsley/react-query#1930]
**Describe the bug**
When I use useInfiniteQuery for pagination loading, everything is fine. But my staleTime is set for 10 seconds. Then the data expires, useInfiniteQuery will request the data again, this time the number of previously loaded pages will load the request at one time

**Expected behavior**
What I want is that when the data expires, it should be loaded from the first page, instead of the previous pagination request together

**Comment by TkDodo** [comment]
This is the current expected behaviour of infinite query. if you have 3 pages loaded on your screen (and thus 3 pages in the cache entry), and that query is stale, and you mount another subscriber, what should be the expected behaviour then please? I don't think we can just show 3 stale pages but only re-load the first one, right? The pages are also _one_ cache entry, so there is little room for different refetching here. Or am I misunderstanding the question?

**Comment by tianleiyiji123** [comment]
> This is the current expected behaviour of infinite query. if you have 3 pages loaded on your screen (and thus 3 pages in the cache entry), and that query is stale, and you mount another subscriber, what should be the expected behaviour then please? I don't think we can just show 3 stale pages but only re-load the first one, right? The pages are also _one_ cache entry, so there is little room for different refetching here. Or am I misunderstanding the question?

Yes, when the cache expires, under Infinite Queries, should only load the first page when entering again, right? Otherwise, if the 3 pages are loaded together, it is not a paging request

**Comment by TkDodo** [comment]
the 3 pages are loaded in sequence. there is only one cache entry, and it contains 3 stale pages. you can:

- remove the entry from the cache. then, when you come back, you have nothing and go to loading state and fetch only the first page (fresh request)
- remove all pages but the first one from the cache, manually. then, when you come back, there would only be one page. but rect-query is not gonna do that (removing data from the cache selectively)
