### ISSUE TITLE
Persisted cache is not immediately cleared by `resetQueries`

### ISSUE THREAD

**Issue by lucaslcode** [tannerlinsley/react-query#1951]
**Describe the bug**
Calling `queryClient.resetQueries()` doesn't immediately clear those queries from local storage. This may also happen with `removeQueries` and `clear`.

**To Reproduce**
1. Use the LocalStorage persistence plugin
2. Make some queries
3. Clear the queries with `resetQueries`
4. Queries are reset in the query cache, but are still present in local storage.

**Expected behavior**
Functions which remove queries should immediately clear them from local storage. 

**Additional context**
In our use case, we reset queries, including sensitive information, on log out, but if the user immediately exits, the data will still be present in local storage (and it could be a public computer).

**Comment by masonlee** [comment]
I found that using `queryClient.getQueryCache().clear();` will clear my localStorage.

**Comment by masonlee** [comment]
I spoke too soon--my solution above does not work; I was only getting lucky from some well-timed page reloads in testing.  My new temporary method for clearing the experimental localStorage cache on user logout is, laughably:
```
localStorage.removeItem("REACT_QUERY_OFFLINE_CACHE");
setLocation("/");
window.location.reload();
```

**Comment by Svish** [comment]
> In our use case, we reset queries, including sensitive information, on log out, but if the user immediately exits, the data will still be present in local storage (and it could be a public computer).

Doesn't fix the issue with `resetQueries`, but as someone who else who also work with somewhat sensitive information, I would highly recommend maybe switching over to `sessionStorage`, rather than `localStorage`. Still not 100% bullet-proof of course, but definitely makes it much less likely for sensitive data to remain on a public computer for too long since it should be cleared out automatically (as long as the user at least closes the browser or something like that).

That said, it would of course _also_ be good if `resetQueries` or some other method/hook was available to clear out stuff completely on logout and things like that.

**Comment by TkDodo** [comment]
could this simply be because of the `throttleTime` that the `webStoragePersistor` accepts?
https://react-query.tanstack.com/plugins/createWebStoragePersistor#options

it defaults to 1 second, so if you clear the cache, it should be cleared from localStorage after one second. can you confirm that this works?
if you need immediate purge, I think clearing it manually is a good approach, or reducing the throttleTime. And, what @Svish said, don't put sensitive information on localStorage :)

**Comment by TkDodo** [comment]
closing with regards to my comment above ⬆️ . I'll reopen if there's anything you think we can / should do.
