### ISSUE TITLE
onSuccess callback in useQuery fires twice

### ISSUE THREAD

**Issue by sshmyg** [tannerlinsley/react-query#1969]
**Describe the bug**
useQuery call one by one for same endpoint but for different components (one component should be child for other and parent should render child only on isLoading === false);

**To Reproduce**
Steps to reproduce the behavior (visit link for details):
https://codesandbox.io/s/vigilant-swartz-ox5p9?file=/src/App.js

**Expected behavior**
onSuccess should be called once.

**Screenshots**
First load
![image](https://user-images.githubusercontent.com/1410608/111136930-e9d38f00-8586-11eb-9123-2d3fee8c9a54.png)

**Desktop (please complete the following information):**
 - OS: mac os 11.1
 - Browser: chrome
 - Version: 89.0.4389.82

**Comment by TkDodo** [comment]
this is very likely because both components are using the same queryKey (`repoData`). each observer is informed when new data is fetched, so I think it goes as follows:

- component 1 mounts, data is fetched, `onSuccess` is called, data is immediately stale.
- now component 2 mounts (conditionally, because component 1 is no longer loading). this triggers a background refetch, because data is stale.
- when the background refetch finishes, both observers of the key `repoData` are informed, and `onSuccess` is triggered for both of them.

to mitigate this, you can:
- create a custom hook with only one `onSuccess` callback
- render both observers at the same time, not conditionally one after the other
- set a small `staleTime` to avoid immediate background updates
- use unique query keys

**Comment by sshmyg** [comment]
@TkDodo  Thanks for the response.
But don't you think onSuccess callback should be uniq and doesn't depend on `queryKey `? 
I found workaround, but it looks pretty much like a bug.
What if I want to have a single cache for different calls but I need separate onSuccess?

**Comment by TkDodo** [comment]
sorry, my bullet list above might not be totally correct. callbacks are unique per observer (=useQuey call), which is why you see them both being executed. if you have the same queryKey, like you do above, and two observers where both have an onSuccess callback, both will be called.

Is this now the behaviour you expect or not?

I updated my comment above. if you render both observers at the same time, react-query will dedupe the request and only call each callback once. if you set a small `staleTime`, mounting the second observer will not result in a background fetch, and thus the second onSuccess will not be called at all (because there is no request).

I think I need to understand what problem you are trying to solve here 🤷

**Comment by sshmyg** [comment]
> sorry, my bullet list above might not be totally correct. callbacks are unique per observer (=useQuey call), which is why you see them both being executed. if you have the same queryKey, like you do above, and two observers where both have an onSuccess callback, both will be called.

No, I would like to have uniq `onSuccess` not depends on `queryKey`. But have an ability to have same cache for same `queryKey`.

`staleTime` - works, if we change it for 2nd response. But also looks like workaround (not obvious, imho).

But I'm trying to understand why onSuccess instance handler depends on queryKey. Why it couldn't be uniq and fires only for appropriate request?

Thanks for the response.

**Comment by TkDodo** [comment]
it is not depending on the queryKey, sorry for the confusion. I changed my initial response and stroke through the "wrong" answers, did you see that?

`onSuccess` depends on the observer. one component can say: I want to use the query, and when fetching is successful, I want to do something, and the other component can say: after fetching, I want to do something else (or nothing at all if there is no `onSuccess` callback).

> staleTime - works, if we change it for 2nd response.

no, staleTime is unique per query. If one observer has 0 and the other has 10, it is still 0. That is why custom hooks are the preferred abstraction - it doesn't make much sense to define different staleTimes per observer on the same query. If you use the ReactQueryDevtools, you can see when a query is stale and when not.

> No, I would like to have uniq onSuccess

to do what exactly please?

**Comment by sshmyg** [comment]
Uniq I meant, fires onSuccess only if current useQuery did request. If some others useQuery instances with same queryKey etc (inside react app) makes request, it doesn't fire any onSuccess from useQuery with same queryKey etc. 

As you see from the codebox, second useQuery triggers onSuccess from 1st useQuery and it own. In my opinion this situation is implicit, and if  it's not a bug, than it should be described in doc.

**Comment by TkDodo** [comment]
> As you see from the codebox, second useQuery triggers onSuccess from 1st useQuery and it own.

I don't think that you can trace back one fetch to a single useQuery instance. fetches happen for various reasons, e.g. window focus. There is no real "origin" of those. When data is fetched, all observers are informed, and all `onSuccess` callbacks are triggered because there is now new data.

if you want to perform side-effects on a per-observer level, maybe a `useEffect` in a component with `[data]` as dependency is what you are looking for?

**Comment by sshmyg** [comment]
@TkDodo `useEffect ` works. But why I need to seeking some others ways, and not use `onSucces`. All you've described works staleTime, useEffect, and some others approaches. 
But question is why onSuccess triggers twice but obviously should just once.

**Comment by TkDodo** [comment]
> But question is why onSuccess triggers twice but obviously should just once.

maybe there are other opinions on this as well, but why should it "obviously" only be called once? You have the reasoning that mounting your component2 "triggers" the fetch, and that's why only the callbacks of component2 should be called. According to the docs:

> This callback will fire any time the query successfully fetches new data.

both observers point to the same query - the same data in the cache. Why should only one be informed that there is now new data and not the other if both observers have an `onSuccess` callback?

I think it would be quite confusing if we decide to call callbacks conditionally. what if 2 observers mount at the same time, which callbacks should be called? who "triggered the fetch", both of them, or only one. same goes for window focus refetching, or refetching when the network disconnects.

**Comment by sshmyg** [comment]
> both observers point to the same query - the same data in the cache. Why should only one be informed that there is now new data and not the other if both observers have an onSuccess callback?

Because it's 2 different instances of useQuery. And it's logically that I want to have an ability to handle success separately, imho.

Not call callbacks conditionally. But only for instance that made a request, not for each instances.
Confusing that thing, that request was made in one place, but onSuccess fires not only there but also in some others places.

**Comment by TkDodo** [comment]
> But only for instance that made a request, not for each instances.

I can only repeat: it's not the instance that is making the request :)

To be honest, I've never used the callbacks for queries - only for mutations, since queries can be made many times, even without user interaction. Imo, if you have code that should happen for one observer, I would not use the callbacks for that. But I still don't know what's the actual problem you're trying to solve. Maybe I'm wrong, but I think this is how the callbacks were intended.

**Comment by sshmyg** [comment]
@TkDodo Thank you

**Comment by bogadrian** [comment]
After carefully reading these comments and after TKDodo helped me understand what happens on Twitter, Thank you very much, this is my take: he wants to grab the data from cache on the Children component use useQuery, because the data is already there from the first onSuccess in the Parent. To not fire a second request on Children which would be a waste somehow. Data is fresh anyway, only the Children render delay. 
to solve this the best option imo is a custom hook for that key. You call the custom hook in Parent and in Children but that way you only have one key and one onSuccess callback  no 2 requests to the server.

**Comment by coadtan** [comment]
Just a random thought. does it work if cacheTime is 0?

**Comment by magbicaleman** [comment]
If you're transitioning between react-query, and redux and thought, "hey, I will just dispatch data update from onSuccess react query callback", you'll find out it will dispatch times the number of observers you have.

For example, if you have 5 observers on the page, you'll dispatch that action 5 times. 

Another observation is if you use a select function option, that data argument for the onSuccess callback will be different.  This is using ReactQuery v3.

**Comment by TkDodo** [comment]
> hey, I will just dispatch an update action with data from onSuccess react query callback

if you're doing that, there is a fundamental misunderstanding in how react-query works, and that is a bigger problem than multiple dispatches. If you are dispatching actions in `onSuccess`, you are "syncing state", thus creating multiple sources of truth (the redux store + the query cache).

> In this case you would be dispatching to an action assuming you had the same data, but in reality the data would be dependent on your select.

TypeScript knows this as types in `onSuccess` are inferred from the result of `select`, but yes, that is also on purpose. Don't sync state, derive it.

**Comment by shaygong** [comment]
@TkDodo I do agree that syncing state is not ideal, but for the sake of smooth transitioning from redux/redux-saga this is very convenient. I want to transition in stages, 1st one is just making sure everything works with react-query, afterwards removing the 2nd state (redux). So is there a hack or something to trigger an action or whatever once "reach query is fetching remotely" only once other than OnSuccess mentioned above?

**Comment by TkDodo** [comment]
useEffect

**Comment by TkDodo** [comment]
But even a gradual migration from redux to react query doesn't need to be done with state syncing. You have access to the queryClient in sagas, so you can get data from there. In components, you can pass dats from react-query to selectors and combine that with custom hooks...

**Comment by shaygong** [comment]
Unless I'm missing something, useEffect with a dependency of the data (or query) still triggers multiple times.
As for the migration, The main point is removing the saga so I don't want to use react-query in there, but since our app is huge, lots of containers using data from the store and relying on actions get called, my simple first task is to create a custom react query hook and call in somewhere inside a specific tab or tabs in my app and use directly it's data, but others places should be synced with this data and currently my only option is to sync it to the store until I remove one by one to use the data from the query (or my custom hook using that query rather).

**Comment by TkDodo** [comment]
> Unless I'm missing something, useEffect with a dependency of the data (or query) still triggers multiple times.

yes, true. If you want it to only happen once, you'd need to dispatch from within the queryFn.

**Comment by alvin883** [comment]
Interesting read, I've been using react-query for a long time but I just learned this behaviour today.

I was having component A & B that just happen to be mounted in the same page (because certain condition is met) and both calling `useQuery` with the same queryKey, but `useQuery` on component B is conditionally disabled, both having their own unique `onSuccess` handler and was thinking that it's a bug because `onSuccess` on component B still got called even if it's `enabled: false`.

Perhaps it's not that clear on the useQuery docs section? but I don't know how to improve it to make sure user understand this exact behaviour, or probably it's useful to just refer them to read this issue instead, because it was helpful for me to understand the whole thing by reading all the explanation from @TkDodo

Thank you so much!

**Comment by TkDodo** [comment]
> because onSuccess on component B still got called even if it's enabled: false.

we're discussing to change this behaviour here:

- https://github.com/TanStack/query/issues/4827

**Comment by ChanhyukPark-Tech** [comment]
I totally agree @TkDodo opinion

>- component 1 mounts, data is fetched, onSuccess is called, data is immediately stale.
>- now component 2 mounts (conditionally, because component 1 is no longer loading). this triggers a background refetch, because data is stale.

key point is `because data is stale.`

This is a natural and natural phenomenon. 

If you don't like this phenomenon, you can specify even a little `staleTime.` in [QueryClient](https://tanstack.com/query/v4/docs/react/reference/QueryClient)


Basically, it's because of the state `batch update of react`, because the state of `isLoading` changes sequentially, and the child is conditionally rendered😁
