### ISSUE TITLE
refetch of useQuery isn't working correctly. 

### ISSUE THREAD

**Issue by S-Nakib** [tannerlinsley/react-query#1980]
**refetch of useQuery isn't working correctly. *
I am using `refetch` on a button click. enabled is false. 
1. The stale time is set to `Infinity`. But on each click, the data is fetched from the database though `isStale` is `false`. 
<br/>
2. If I set the stale time to `0`, then it fetches data on each click. But `isLoading` is `false` after the first fetch. But from the documentation, I think if the cache is invalid, then `isLoading` is supposed to be `true`. 

**To Reproduce**
Use `useQuery` with `enabled:false` where the refetch happens on a button click.

I am using react-query 3.12.1

**Comment by TkDodo** [comment]
two misconceptions here:

1) `refetch` does a hard-refetch, same as `queryClient.refetchQueries()`. it bypasses the stale-data-check, and also the enabled check. This is on purpose to allow for imperatively and lazily fetching of the query. This is described here: https://react-query.tanstack.com/guides/disabling-queries

2) `staleTime: 0` is the default, and isLoading is correctly false after the first refetch. isLoading represents a state where there is no data to show and you can and probably should show a loading spinner instead. After that, you have data in the cache, and react-query will do "background refetches" on stale data. so the state of the query is "success", not "loading", because you can show the data that you get from the cache. Additionally `isFetching` will be true. This is _always_ true when a request is going out.

> But from the documentation, I think if the cache is invalid, then `isLoading` is supposed to be `true`.

Can you point me to the docs where it says so, because that is _not correct_  :)

**Comment by S-Nakib** [comment]
Thanks a lot for your response. 
1. It would be more clear if it was mentioned in the docs that `refetch` bypasses stale-data-check.
2. My bad. On the [doc](https://react-query.tanstack.com/reference/useQuery) it is said 

> loading if the query is in a "hard" loading state. This means there is no cached data and the query is currently fetching

I thought `no cached data` means `staled cache`.

**Comment by TkDodo** [comment]
> It would be more clear if it was mentioned in the docs that refetch bypasses stale-data-check.

feel free to amend that info on the [useQuery API reference](https://react-query.tanstack.com/reference/useQuery) where that function is described. It currently says:

> A function to manually refetch the query

I think that implies that it will always refetch if this function is called, no matter what. it also bypasses the `enabled` flag. It doesn't hurt to mention it though.

**Comment by HiteshDatt** [comment]
if someone wants to refetch from network only if data is not stale then a workaround I used is this,

`
const { data, isLoading, refetch } = useQuery({
    queryKey: queryKey,
    queryFn: () => fetchData(),
    enabled: false,
    staleTime: 1000 * 60 * 5, // 5 mins
  });

const queryClient = useQueryClient();

if (!queryClient.getQueryData(queryKey)) {
     // refetch only if not found in cache
     refetch();
}
`

**Comment by Oner-T** [comment]
@HiteshDatt 
Hi

`if (!queryClient.getQueryData(queryKey)) {
     // refetch only if not found in cache
     refetch();
}`
Can you explain me what is "queryKey" here ? I pass my queryKey array in the useQuery but it doesn't work

**Comment by xzegga** [comment]
spend three days with the same problem, finaly I found the solution, I wrote an article explaining the problem, you can take a look here:

[The Bug That Steals Your Weekend: When TanStack Query Lies to You (And the Culprit is Invisible) - 4 minutes read](https://www.linkedin.com/pulse/bug-steals-your-weekend-when-tanstack-query-lies-you-ra%C3%BAl-escamilla-0jlne/)

I hope it helps other to overcome this nighmare

**Comment by TkDodo** [comment]
> when TanStack Query Lies to You

You’re framing this like it’s react-query’s problem but it’s just an async state manager that has nothing to do with data fetching. You can log in the `queryFn` and as soon as that happens, its job is done.
