### ISSUE TITLE
onError is not called if retry is enabled

### ISSUE THREAD

**Issue by dlindenkreuz** [tannerlinsley/react-query#1990]
The `onError` callback of `useQuery` is never called if `retry` is set to `true`. Might be related to #1927.

**To Reproduce**
https://codesandbox.io/s/silly-jones-hwqj0?file=/src/index.js
Set `retry` to false to see `onError` in action.

**Expected behavior**
My use case requires me to individually respond to different server errors. In most cases, I need to retry the request, while for certain server errors I need to stop and perform an action (plus report to the user).

A workaround would be to handle the errors in the `retry(failureCount, error)` callback, but that would be misuse. IMHO, side effects should live in the onError / onSuccess etc. callbacks.

I do see a valid use case to only call onError when all retries have failed. However, since we're looking at infinite retries here, there must be a way to react to "intermediate" errors.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 86

**Comment by TkDodo** [comment]
Yes so right now, the query only transitions to error state when the retries are done. As you can see in your example, your query is in loading state the whole time. onError is only called when the query also goes to error state.

if you want to turn reties off on fatal errors, you can achieve that with a custom retry function - no local state needed. If you've stopped the retry on a fatal error, you can also act upon it in onError.

**Comment by dlindenkreuz** [comment]
> If you've stopped the retry on a fatal error, you can also act upon it in onError.

Good point!

> no local state needed

Given the codesandbox from my example, how would I update the UI to present the error without any local state? Afaik the object returned by `useQuery` does not provide a field with the current `retry` value.

Also, I'm afraid my example was lacking one important case: How can I act upon non-fatal errors that don't stop the retry loop?

Using your suggestions, I split my scenario up into `retry` and `onError`:

```typescript
retry: (failureCount, err) => {
  // obviously pseudo code
  if (err.message === "Hardcore failure") {
    // stop retrying on fatal error, report in onError
    return false
  } else if (err.message === "Rate limit exceeded") {
    // keep retrying, don't report
    return true
  } else {
    reportMinorError(err) // 👈 side effect seems wrong here
    // also keep retrying
    return true
  }
},
onError: (err) => {
  reportFatalError(err)
}
```

What would you recommend for the highlighted line / performing a side effect for minor errors inside `retry`?

**Comment by TkDodo** [comment]
> Given the codesandbox from my example, how would I update the UI to present the error without any local state? Afaik the object returned by useQuery does not provide a field with the current retry value.

you can get the failureCount, but not the actual errors. Retries are kinda „internal“. I don’t think there is a good way to perform a side-effect for an error _and_ retry it at the same time.

I think the idea is: if you retry an error, you are kind of discarding / ignoring the error, because you will get a new response anyhow.

maybe it’s okay to perform side effects in the retry function, or we’d need a new onRetryError callback, or expose the retryError field on the query result... 🤔

**Comment by dlindenkreuz** [comment]
> or we’d need a new onRetryError callback

Seems like the most idiomatic way to me.

**Comment by angus-kablamo** [comment]
Is it just me or is there only ever 1 attempt at loading the query, even if you modify retryDelay and retry?

**Comment by shamilovtim** [comment]
Using default QueryClient settings and on a failed fetch throwing `throw new Error("abcdefg")`  we are not seeing any retry logic from React Query. Is it supposed to exist by default? Something seems very broken.

**Comment by TkDodo** [comment]
@shamilovtim how does your `queryFn` look like? is it an `async` function? react-query expects a failed or a resolved Promise to be returned. `async` functions transform thrown Errors into failed promises. If you don't have an async function, but use promise chaining with `.then` - don't throw errors - return `Promise.reject(new Error("abcdefg"))`

but I am just guessing here...

**Comment by shamilovtim** [comment]
Actually @TkDodo I was mistaken. What's happening is that the default retry duration is *way* too fast by default, and so because it retries so quickly, it hits onError almost instantly and doesn't make it look like RQ is retrying. My suggestion: tone down the default so it doesn't feel so busted. Also the code on the site is weird:

`attemptIndex => Math.min(1000 * 2 ** attemptIndex, 30000)` 
At `attemptIndex=0` this means retry at 0 (instant retry). I can't imagine a case where users would want to retry instantaneously. I went with something like the following:

`retryDelay: attemptIndex => Math.max(2000 * 2 * attemptIndex, 4000)`

At 0 this uses 4 seconds, but otherwise it will always be above 4000, and thus will use the next largest number in the future.

**Comment by TkDodo** [comment]
>> or we’d need a new onRetryError callback

>Seems like the most idiomatic way to me.

The more I think about it, this is also something you can solve in the queryFn itself, or with an interceptor if you're using axios:

```
const fetchTodos = async () => {
  try {
    axios.get('todos')
  } catch (e) {
    if (isMinorError(e)) {
      reportMinorError(e)
    }
    throw e // will make sure that react-query keeps retrying
  }
}
```

> My suggestion: tone down the default so it doesn't feel so busted.

I think there are plenty good uses where you want the first retry to happen instantly. Sometimes, a request takes some seconds before it errors because the backend is slow or lets it time out for some reason, and then you can just instantly try again. Waiting 4 seconds seems like a very long time, but if that fits your case, that's why react-query is customizable to your needs :)
