### ISSUE TITLE
useQuery with a dependent query causes an extra re-render.

### ISSUE THREAD

**Issue by OndeVai** [tannerlinsley/react-query#2001]
**Describe the bug**
I have a "main/detail" scenario where I load a list of items with one useQuery and then load a detail item with a second useQuery, after the fist list item is selected in a dropdown list. (The scenario is illustrated with this sandbox: https://codesandbox.io/s/dependent-query-example-qmfkk?file=/src/DependentQueryExample.js).

After selecting an item in the list, I'm setting a state variable for the ID of the selected item and, since the detail-related useQuery depends on that state value, it fires and returns the detail.

Also, please note, I have **turned off** React StrictMode.

After selecting the item in the list, I would expect 2 renders:
1) One after the selected list id changes, since I'm setting that state in the change handler
2) One after the dependent useQuery changes because it's refetching/updating the detail data based on step 1)

However I'm getting 3 renders:
1) One after the selected list id changes, since I'm setting that state in the change handler
2) Nothing has apparently changed?
3) One after the dependent useQuery changes because it's refetching/updating the detail data based on step 1)

**To Reproduce**
1. Go to https://codesandbox.io/s/dependent-query-example-qmfkk?file=/src/DependentQueryExample.js, and open the console in CodeSandboox
2. Select "first/second/third" in the select list
3. Scroll down to the console in CodeSandbox to see the console statements logged after each re-render
4. See the output:
```
list changed? false selectedListId changed? true detail changed? false isLoadingDetail changed? true onChange changed? false 
list changed? false selectedListId changed? false detail changed? false isLoadingDetail changed? false onChange changed? false
list changed? false selectedListId changed? false detail changed? true isLoadingDetail changed? true onChange changed? false 
```

**Expected behavior**
As mentioned, I'd expect to see only 2 renders:
```
list changed? false selectedListId changed? true detail changed? false isLoadingDetail changed? true onChange changed? false 
list changed? false selectedListId changed? false detail changed? true isLoadingDetail changed? true onChange changed? false 
```

**Comment by dusty** [comment]
I would suspect that isFetching is causing the re-render.  Since you aren't using isFetching, you could change the notifyOnChangeProps to 'tracked'.  This should stop the 3rd render.

I just recently read this article from Dominik that you may like.  https://tkdodo.eu/blog/react-query-render-optimizations

**Comment by OndeVai** [comment]
Hey @dusty, thanks for he articles --great reads. 
I tried setting notifyOnChangeProps to 'tracked', along with outputting the "isFetching" value. However, still getting the extra render https://codesandbox.io/s/dependent-query-example-forked-edbmh?file=/src/DependentQueryExample.js

**Comment by TkDodo** [comment]
Thanks for linking my article @dusty :)

side note: The first rule of tracked queries: if you use a field, it will be tracked. so if you destructure `isFetching` just to console.log it, you will re-render on every isFetching transition because of it ;)

but that is not the case here. From what I am seeing, we are getting 3 re-renders instead of 2 because:

1. `setState` of the `selectedListId`
2. changing the `useQuery` options triggers a _microtask_, thus scheduling another re-render
3. transition from `loading` to `success` status when we have data

number 2 is likely the culprit that we don't want to see. I don't have enough knowledge about why we are scheduling this, I'm sure @boschni knows. It might be that you've discovered a bug - I would also only expect 2 re-renders here, especially because the queryInfo is identical between 1 and 2.

**Comment by OndeVai** [comment]
Yeah, I was just logging isFetching for visibility, but it did not change the number of renders in my example. Glad to know you guys are digging into the issue (and that I'm not (completely) losing my mind :))

**Comment by boschni** [comment]
It renders three times because:

1. The setState
2. useQuery indicating its state has changed (idle -> loading)
3. useQuery indicating its state has changed (loading -> success)

I don't remember the exact reason, but I think React wouldn't display the correct state in some situations without the notification.

**Comment by TkDodo** [comment]
Hm, in the example above, we can see `status: 'loading'` directly after the `setState`, and the re-render from number 2 has exactly the same information.. 🤔

**Comment by boschni** [comment]
Yes it optimistically indicates it is loading, but the loading only really starts when React commits the rendering tree.

**Comment by TkDodo** [comment]
Okay, then we’ve established that this is indeed the expected behavior 👍
