### ISSUE TITLE
Setting `manual = true` on useQuery is ignored for `refetchAllOnWindowFocus = true`

### ISSUE THREAD

**Issue by yss14** [tannerlinsley/react-query#206]
The problem described [here](https://github.com/tannerlinsley/react-query/issues/161) still exists if `refetchAllOnWindowFocus` option is enabled.
Or is this intended behavior? I would guess that setting `manual:true` would required a manual call of `refetch` to retrigger the query.

The [codesandbox](https://codesandbox.io/s/crazy-bassi-i9kw7) from the referenced issue shows this problem if you update `react-query` to `1.0.16` and click some times between the emulated browser window and the code.

![demo_reactquery_issue](https://user-images.githubusercontent.com/4346842/76083224-65325600-5fad-11ea-92f7-ea91aaa2e2a8.gif)

**Comment by tannerlinsley** [comment]
Yeah... I feel like this is a bug. It should be if *all* `useQuery` instances are defined as manual, then the query should be skipped. This is tough though, since the manual configuration isn't stored in the cache, but at the instance level with the useBaseQuery hook.

**Comment by yss14** [comment]
>  It should be if all useQuery instances are defined as manual, then the query should be skipped.
Why? If I set `manual:true` I would expect that the query is only triggered if and only if `refetch` is called. Otherwise this could lead to situations where a query is defined but not ready yet and than is triggered by some window focus event.

**Comment by tannerlinsley** [comment]
Architecturally, it's possible for 2 instances to subscribe and power the same query in the cache, but since `manual` is configured and enforced at the hook-level, one of the instances could have manual and the other could not:

```js
useQuery('todos', getTodos)

// somewhere else...

useQuery('todos', getTodos, { manual: true })
```

This situation *should* result in the query being refetched on window focus, since there is at the very least one instance of the query which is not manual. If both were manual, then the query *should not* be refetched on window focus.

This may not be how it works today, but I believe we should get it to this point.

**Comment by tannerlinsley** [comment]
Would you like to work on this PR?

**Comment by yss14** [comment]
I'm pleased to be ask contributing to `react-query`. But I guess I first have to get familiar with the code base and functionality, since I'm pretty new to this project and currently doing my first steps with `react-query`. I will let you know ;)
For now I'm just disabling `refetchAllOnWindowFocus` since I don't need it.

**Comment by tannerlinsley** [comment]
Sounds good.
