### ISSUE TITLE
V2 doc search hyperlinks lead to 404

### ISSUE THREAD

**Issue by dmbarry86** [tannerlinsley/react-query#2136]
**Describe the bug**
If I use the search in V2 docs and try to click one of the search results it gives me a 404. I've tried a couple of search terms and they all seem to result in broken links.

**To Reproduce**
See screnshot

**Expected behavior**
Takes me to a valid link in the doc

**Screenshots**
Clicking this
![image](https://user-images.githubusercontent.com/8976377/115030489-0da82e80-9ebf-11eb-8993-07ac923923e9.png)

Results in this
![image](https://user-images.githubusercontent.com/8976377/115030701-4b0cbc00-9ebf-11eb-96ff-7acd4c1452a7.png)

**Comment by TkDodo** [comment]
we've had this so many times already:

https://github.com/tannerlinsley/react-query/issues/1968
https://github.com/tannerlinsley/react-query/issues/2013
https://github.com/tannerlinsley/react-query/issues/1420

The reason is always the same and out of our hands:

https://github.com/tannerlinsley/react-query/issues/1420#issuecomment-745008257

> Search unfortunately will not work until algolia docsearch supports multiple subdomains .
