### ISSUE TITLE
Invalidation during a fetch does not trigger refetch.

### ISSUE THREAD

**Issue by acornellier** [tannerlinsley/react-query#2154]
**Describe the bug**
Calling `invalidateQueries('query')` while a fetch for `'query'` is currently in progress does not trigger a refetch.

I have reproduced the example below. `/api/getData` has an artificial 1 second delay, while `/api/setData` is immediate. Pressing `Save` while "Invalidate before saving" is checked does the following
1. invalidates the query, triggering `/api/getData`
2. calls `/api/setData`
3. invalidates the query again

The second invalidation will not trigger a refetch, so the data will be out of date.

**To Reproduce**
1. Go to https://codesandbox.io/s/wizardly-monad-vf760?file=/pages/index.js
2. Ensure "Invalidate before saving" is checked
3. Enter a value in the input
4. Press Save
5. Wait 1 second
6. Note that the value in the input box is not updated

**Expected behavior**
The previous fetch should perhaps be discarded, and a new fetch should definitely be triggered either right away or after the previous completes.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 3.13.10

**Comment by TkDodo** [comment]
I think all you need to do is to `await` the first invalidation (line 39). otherwise, you'll just have a quite ordinary race condition:

```
await queryClient.invalidateQueries(`/api/getData`);
```

invalidateQueries just marks the query as stale, and stale queries are refetched. so if you mark it as stale again while it is already refetching, it doesn't do anything.

when updating values, it is also good practice to cancel all ongoing interfering requests with `queryClient.cancelQueries('/api/getData')` . This is especially important for optimistic updates, which is why the examples do it that way - and also a good reason to use `useMutation` for when you want to update data on the server :)

so if you add `cancelQueries` before the update, the first invalidation will be cancelled, then the update happens, then the second invalidation will run again and refetch again after the update.

hope that helps.

**Comment by testerez** [comment]
Using `await` as you suggest is not always possible because the update could be triggered by another hook mounted, re-focus on the page...
Would it make sense to cancel queries by default when `invalidateQueries` is called? I believe it would be a safer default.

**Comment by TkDodo** [comment]
> Using await as you suggest is not always possible because the update could be triggered by another hook mounted, re-focus on the page...

which is why the second suggestion was to call `cancelQueries` before you mutate.

> Would it make sense to cancel queries by default when invalidateQueries is called? I believe it would be a safer default.

i don't think so. invalidateQueries doesn't necessarily trigger a re-fetch. it marks queries as stale, and refetches active queries only. further, as we've seen, if a fetch is already in progress, invalidateQueries does basically nothing.

what you want is to cancel outgoing queries _before_ you are making updates, _not_ before invalidateQueries is called.

**Comment by swingthrough** [comment]
> what you want is to cancel outgoing queries _before_ you are making updates, _not_ before invalidateQueries is called.

Does that mean calling `cancelQueries` in `onMutate`, and then calling `invalidateQueries` for that same key in `onSettled`? Would that be okay?
