### ISSUE TITLE
Infinite render loop when conditionally rendering component with retry disabled

### ISSUE THREAD

**Issue by jonlambert** [tannerlinsley/react-query#2173]
**Describe the bug**

This bug has been a difficult one to nail down but I think I've worked out the conditions that trigger it. 

When all of the following things are true:

1. The query has retrying disabled
2. The query throws an error
3. The query hook is then used in a component which is conditionally rendered in it's parent based on it's loading status

...an infinite render loop is created, resulting in a page crash.

It's been a long day so it could totally be me failing to see an obvious failure of logic here, happy to be corrected if so!

**To Reproduce**
I've put together [a simple reproduction in CodeSandbox](https://codesandbox.io/s/quizzical-sammet-5pzdq?file=/src/App.js). Uncomment the `<ConditionalThing />` component to see the problem in action.

**Expected behavior**
For the request to fail once, and consumer components to be rendered once with the error populated.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome, safari
 - Version: 90.0.4430.85, 14.0.3

**Smartphone (please complete the following information):**
n/a

**Comment by jonlambert** [comment]
Looks like adding `retryOnMount: false` is needed to prevent this. This may have been obvious to others, please feel free to close this issue if so. But it seems quite unexpected and the bang is big 😅

**Comment by TkDodo** [comment]
thank you for the reproduction 👍 

so I can consistently get this to infinitely re-render, even with 3 retries. It just takes longer. The only time where I think this really stopped was when I changed some code, but I think this is codesandbox reloading related. If you say "open in new window", you'll see that it infinitely loads.

here is what's happening:

- we first render `ConditionalThing`, it triggers a query and returns `loading`
- after it goes to error state, it will render `Thing`
- `Thing` mounts and calls the hook again. The hook sees it's in error state, so it starts fetching again. Since we have no data, it goes to a hard `loading` state.
- Now `ConditionalThing` renders again, as it's subscribed to the same query key. but because we are `loading`, it now _unmounts_ `Thing`.
--> we are basically back to step 1

it can be easily worked around by only mounting `Thing` if we really have data, _not_ if we are merely `!loading`, because that includes error states.

Hope that helps :)

**Comment by jonlambert** [comment]
Thanks for your thoughtful reply, @TkDodo. Makes a lot of sense. 🙂
