### ISSUE TITLE
Timing Issue when using cacheTime 0

### ISSUE THREAD

**Issue by alakae** [tannerlinsley/react-query#2236]
**Describe the bug**

Thanks for this awesome library! In case this is not a bug, but rather an unintended use of React Query please let me know.

I have written a higher order component which displays a loading indicator while a set of queries are loading (see below). The idea is that the `WrappedComponent` only gets rendered when all data has been completely loaded. In our App we use `cacheTime: 0` as we want the data to be reloaded on every route change. The loading indicator should be displayed in this case.

```
export const withQueries = (
    WrappedComponent,
    queries,
) => (props) => {
    const queryResults = queries.map(q => q());
    const isLoading = queryResults.some(r => r.isLoading);
    const error = queryResults.find(r => r.error)?.error;
    if (error) {
        return ("Error");
    }
    if (isLoading) {
        return "loading...";
    }
    return (
        <WrappedComponent {...props}/>
    );
};
```

I have noticed that when navigating from a component that uses queries `useA, useB` to a view that uses a subset of those queries `isLoading` is false in the HOC. But a subsequent call to the same query in the `WrappedComponent` receives no data. The issue does not appear when the set of queries are disjunct or `cacheTime` is set to the default value.

**To Reproduce**
1. Go to ['this code sandbox](https://codesandbox.io/s/nervous-bhabha-ot0vc)'
2. Click on 'Sandwiches' (Sandwiches view uses two queries)
3. Click on 'Tacos' to navigate back (Tacos view only uses one of those two)

**Expected behavior**
Expect `isLoading` to be true when checking in the HOC.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: tested on Chrome and Safari
 - Version: Safari 14, Chrome 90

**Comment by TkDodo** [comment]
My guess is that if you do `cacheTime: 0`, the loaded queries will be removed from the cache as soon as the last observer unmounts, which happens on route change. Sorry to say, I think this looks like a strange pattern to solve a different problem. calling hooks in an "array" style like this might lead to a violation of the rules of hooks if different amount of hooks are called in different render cycles. You can:

- [useQueries](https://react-query.tanstack.com/reference/useQueries) for that
- use [prefetching](https://react-query.tanstack.com/guides/prefetching) to prefetch a query so that it is guaranteed to have data when you come to the route.

> In our App we use cacheTime: 0 as we want the data to be reloaded on every route change.

I also don't quite understand this. By default, when you change a route, react-query will give you the stale data from the cache _and_ trigger a refetch in the background. Very often, this is a better ux than deleting the data from the cache with `cacheTime: 0` and then showing a loading spinner in these cases ....

**Comment by ironmanvim** [comment]
@alakae 
Execution sequence:
`CacheTime: 0`
- So what's happening is when you go to the route tacos. There is no cache available for the query. So the query will run normal.
- Next, routing to Sandwiches will also run normal. because there is no cache for sandwiches too.
- Next, when you go back to the tacos. When the first query is hit. The cache is still not empty. So, react is rendering the Tacos. After rendering the tacos You can observe the blink of tacos data. Then the garbage collection process happened. As per the observation the garbage collection call is next in the event loop after the render. (Here the garbage collection call is immediate).
- So, Tacos is rendered then after the next event loop is called. garbage collection happened. the data became empty. tacos.map is not handled. So, The error popped.
	
`cacheTime: 1000 (something else)`
- Here, when you go back to Tacos. The cache is there. Tacos rendered properly. Here the garbage collection will not happen. because we got the cache before the cacheTime is over.

**The way the event loop works created this problem. And not a bug in react query.**

There is no need for setting `cacheTime` to `0`. you can set it to `100`, `200`, `500`... It won't damage your usecase.

**Comment by alakae** [comment]
Thank you @ironmanvim for the explanation. We have increased the cache time as you suggested and it’s working fine.
