### ISSUE TITLE
Number as query key fails with message "Missing queryFn"

### ISSUE THREAD

**Issue by christianeide** [tannerlinsley/react-query#2316]
**Describe the bug**
Im upgrading from v2 to v3 and run into some problems. It turns out that we have previously used IDs (numbers) as query keys for react-query. Any id/number that are supplied to react-query directly fails with the error message `Missing queryFn`.

If will work if I wrap the number in an array, but not just supplied as you would do with a single string.
`let queryKey = 12345` will not work
`let querykey = [12345]` will work

**To Reproduce**
1. Open this codesandbox https://codesandbox.io/s/reactqueryid-o96mp
2. I have only changed the query key to a number
3. See error in console

**Expected behavior**
I would ether expect that numbers would work the same way as a string would. If not then I would expect a different error message that better explains the issue, now it took me quite some time to figure out what was causing the error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 90.0.4430.212

**Additional context**
Happens in v3, not in v2

**Comment by TkDodo** [comment]
Okay so the error you are getting is because the `queryFn` cannot be found for that key. That seems to be because the key is not recognized as a valid key, which is done by checking for a string or an array:

https://github.com/tannerlinsley/react-query/blob/4083c1ef8a8734d2680a4e5f031c7958c18ee176/src/core/utils.ts#L393-L395

`useQuery` has a couple of overloads, and without that check, it's hard to find out which "version" of useQuery is called. For example, it is totally legit to leave out the queryFn, because it has been provided as a default.

What seems to work is to use the object syntax, where every property is already uniquely identified:

```
  const { isLoading, error, data, isFetching } = useQuery({
    queryKey: 1,
    queryFn: () =>
      fetch(
        "https://api.github.com/repos/tannerlinsley/react-query"
      ).then((res) => res.json())
  });
```

I still wouldn't do that, because it seems to be more by accident that this works. The docs as well as the typescript types clearly state that the queryKey has to be either a string, or an an array.
