### ISSUE TITLE
queryClient.setQueryData does not support queryKeyHashFn

### ISSUE THREAD

**Issue by amiroous** [tannerlinsley/react-query#2352]
**Describe the bug**
Currently if we use `queryKeyHashFn` to customize the has key, in `useQuery` hook, it will result a string key. However when we want to update the client (cached) data for that key using `queryClient.setQueryData`, it does not support `queryKeyHashFn` and always updates the key as an array which is causing a key mismatched.

**To Reproduce**
1. Create a query with `useQuery(['a', 'b', 'c'], getFunction, { useQuery: () => ['e'] })`;
2. After mutation, try to update the cached data for that query `queryClient.setQueryData(['e'], updatedObject)` or `queryClient.setQueryData('e' updatedObject)`

**Expected behavior**
The data, associated to that query should be updated and replace the old data, but as the key is mismatched, you will see 2 query on the devtool. 

React Query Version: `3.16.0`

**Comment by TkDodo** [comment]
I think the confusion here is that you'd like to update the query based on the serialized key / the result of the `queryHashFn`, which is not what is happening. You always need to update by the actual _key_. In your example, it would still be `['a', 'b', 'c']`.

As an example, if I use the standard hash function, and my key is `['todos', 5]`, I _cannot_ update the query by passing a `string` as the query key, even though that's the serialized / hashed version of it. Hope that makes sense.

**Comment by amiroous** [comment]
> I think the confusion here is that you'd like to update the query based on the serialized key / the result of the `queryHashFn`, which is not what is happening. You always need to update by the actual _key_. In your example, it would still be `['a', 'b', 'c']`.
> 
> As an example, if I use the standard hash function, and my key is `['todos', 5]`, I _cannot_ update the query by passing a `string` as the query key, even though that's the serialized / hashed version of it. Hope that makes sense.

Thanks @TkDodo , I'm aware of the array and string and thats why in (2) I included both cases with string and with array.
The issue is if we have an option to customize the hashed key for main query, it seems we should have same on the client query too, otherwise we have to maintain 2 different way of dealing with same query.

**Comment by amiroous** [comment]
> Can you please create a codesandbox because I still fail to see the issue here :/

It seems it was same issue in older versions which at some point was fixed but now is back again.
Please refer to this issue and its sandbox for the context only https://github.com/tannerlinsley/react-query/issues/1343

**Comment by TkDodo** [comment]
I executed the sandbox from that issue and updated it to the latest react-query version, I cannot reproduce the issue mentioned. Here it is: https://codesandbox.io/s/queryclientsetdata-does-not-use-custom-hash-function-forked-6q8fg?file=/src/App.tsx

**Comment by vjuux** [comment]
Hi folks, I believe i'm experiencing a similar misunderstanding. Assuming I have a key as `[{ name: 'test' }, 123]` and a custom key hashing function like 

```javascript
function queryKeyHashFn(queryKey) {
   return queryKey.map(value => value.name ?? value);
}
```

when interacting with the cache I would have to use something like `queryClient.setQueriesData([{ name: 'test' }], { exact: false })` instead of `queryClient.setQueriesData(['test'], { exact: false })`.
@amiroous is this what you've tried to achieve?

**Comment by TkDodo** [comment]
@vjuux I think there is a misunderstanding about what the `queryHashFn` does. It takes your QueryKey as input and creates a hash (string) out of it, so the signature is:

https://github.com/tannerlinsley/react-query/blob/4083c1ef8a8734d2680a4e5f031c7958c18ee176/src/core/utils.ts#L263

Your function doesn't return a `string`, so it doesn't qualify.

Also, the result of that function is used to internally use the QueryKey as the key of the queryCache, which is just an object - So we need a string to use it as the key to this object.

At no point are you using that stringified version your code, but you can see how it's stringified e.g. in the devtools. The default implementation is mostly `JSON.stringify`, except that objects are sorted to have a consistent ordering.

If you were to use the stringified version, that would mean that with the default implemenation, given a query:

```
useQuery(['todos', 1], () => fetchTodo(1))
```

you would need to call `setQueryData("[\"todos\", 1"])` - basically pass a string to it. But you don't, because you don't _input_ the result of the queryKeyHashFn to anything. You pass an array to it, and react-query internally calls the hashFn before it looks it up in the internal object.

**Comment by amiroous** [comment]
@vjuux Its related but not same issue.
@TkDodo I totally understand that its stratifying the key under the hood, what I'm saying is if we have ability to define an array of multiple primitives, the `setQueryData` should also be able to refer that query with same format as an array.
Most of the cases we use array as key, it's because we are passing some dynamic arguments to the query (eg. ['1', {userName: 'Abc', age: 23}].
I think its a good feature to be added as otherwise `setQueryData` would not be useful for queries with arrayed keys.

**Comment by TkDodo** [comment]
> I think its a good feature to be added as otherwise setQueryData would not be useful for queries with arrayed keys.

i don’t understand that at all because I’m using setQueryData with array keys all the time without issues. 

Let’s maybe take a step back: why are you overriding the hash fn in the first place? Which problem are you trying to solve by doing that?

**Comment by amiroous** [comment]
@TkDodo Sorry if it's not clear. I'm not overriding the hash
Here is the case,
1. When I'm using `useQuery`, the queryFn I have is expecting some more data to be passed to it. therefore I'm doing something like `useQuery([QUERY_KEY, GRAPHQL_CLIENT, USER_ID], myQueryFn, {myQueryKeyHashFn, ...options});` and then the `myQueryFn` is reading/extracting `GRAPHQL_CLIENT` and the `USER_ID` and using them under the hood.
Please note that I'm also using `myQueryKeyHashFn` to make that complex array `[QUERY_KEY, GRAPHQL_CLIENT, USER_ID]` to a simple string like `CUSTOM_QUERY_KEY`.
2. After successful mutation, I like to call `setQueryData` and I like to be able to use `CUSTOM_QUERY_KEY` as the passed key.

The issue is by doing so, the query is not matched with the initial one and therefore it's not updating the main query client data.

**Comment by TkDodo** [comment]
The query key is passed as it is (as array) to the query fn - why would you need the hashFn to pass variables?
One of the use cases for implementing the hashFn is if you have something non-serializable in the key that you want to serialize

**Comment by amiroous** [comment]
I need hashFn to make the complex array key to a simple string as the key, that way my `myQueryFn` still can use those variables (GRAPHQL_CLIENT, USER_ID) and the key itself (due to the usage of `myQueryKeyHashFn`) should be a simple string. Basically I need to use hashFn to normalize my complex arrayed key to a simple string.

**Comment by KurtGokhan** [comment]
@TkDodo  sorry for reviving this. I can understand the issue, as I am also facing the same issue. I can open a new issue if you want.

Basically, I am trying to ignore part of the `queryKey` when hashing it. I can do that for `useQuery` but not for methods like `setQueryData`.

See this [example in StackBlitz](https://stackblitz.com/edit/tanstack-query-2352?file=src%2Findex.jsx).

If you pass the `queryKeyHashFn` to the query-client (line 19 in StackBlitz example), it works as expected.

The issue is not so critical. And it is not like there aren't any workarounds. But this is a matter of correctness, and it seems to be a gap in the API of methods like `setQueryData`.

**Comment by TkDodo** [comment]
@KurtGokhan what you'd want in this case is to set the hashFn globally, either in `defaultOptions` when creating the queryClient, or with `queryClient.setQueryDefaults` for a sub-set of matching keys.

**Comment by KurtGokhan** [comment]
Thanks. As I said, there are workarounds, and they are not too inconvenient. But this is still a missing capability of `setQueryData` and similar methods. Just saying.

**Comment by paul-sachs** [comment]
We've also run into this exact issue. You end up creating a function something like:

```tsx
function getQueryData(key) {
  queryClient.setQueryDefaults(["key-prefix"], {
    queryKeyHashFn: customHashFn,
  });
  return queryClient.getQueryData(key)
}
```

This is a little clunky looking since it modifies the defaults on every call. This could be more cleanly solved with a custom QueryClient but that all seems kinda clunky to just avoid some option params on `getQueryData` and `setQueryData`

**Comment by TkDodo** [comment]
The idea with custom key hashing is really that you apply it globally to e.g. hash non json-serializable values. Doing that on a per-key basis isn't a good idea imo

**Comment by paul-sachs** [comment]
@TkDodo I understand and that makes sense, though currently this is allowed by the options of `useQuery`. Perhaps if it's a footgun, we should at least flag it in the docs somewhere?
