### ISSUE TITLE
Same query in nested component makes api call fall into loop

### ISSUE THREAD

**Issue by karthik-hr** [tannerlinsley/react-query#2357]
**Describe the bug**
Conditional rendering (isFetching, isLoading) of Component that has same react query hook makes api calls fall into loop.

**To Reproduce**
```
import React from 'react';
import { useQuery, QueryObserverResult } from 'react-query';

// useUser.ts
const useUser = (id?: string | number): QueryObserverResult<{ userID: number }> => {
	return useQuery(
		['query-candidate', id],
		async () => {
			return new Promise((resolve) => {
				setTimeout(() => {
					console.log(id);
					resolve({ userID: parseInt(id) });
				}, 2000);
			});
		},
		{ enabled: !!id },
	);
};

// ChildComponent.tsx
const ChildComponent = ({ id }: { id?: string | number }) => {
	const { data } = useUser(id);
	return <>{data?.userID}</>;
};


// User.tsx
const User: React.FC = () => {
	const id = '123';
	const { data, isLoading, isFetching } = useUser(id);

	// makes problem
	const child = <ChildComponent id={id} />;

	// Works fine
	// const child = <ChildComponent id={data?.userID} />;

	return isLoading || isFetching ? <>Loading</> : child;
};

export default User;
```

**Comment by TkDodo** [comment]
This is expected, here is what's happening under the hood with the default settings:

1. you mount the `user` component, it will initiate the fetch
1. once you get the data back, you mount `ChildComponent`
1. because the `staleTime` defaults to `zero` and `refetchOnMount` is `true`, the mount of the `ChildComponent` triggers a background refetch
1. now all observers are informed about that (`User` and `ChildComponent`), with `isFetching` set to `true`
1. now you _unmount_ `ChildComponent` because of `isFetching`
1. when the background update finishes, you mount it again - go back to point 3.

There are a couple of things you can do to avoid this:

- don't unmount `ChildCompnent` whenever you are `isFetching`. That's the best thing you can do - only show a loading spinner if you have no `data`.
- tinker with the settings - either set a higher `staleTime` or disable `refetchOnMount` to avoid the background updates. setting `staleTime` seems better.
