### ISSUE TITLE
Resetting a hydrated query results in reset to hydrated state

### ISSUE THREAD

**Issue by DerJacques** [tannerlinsley/react-query#2419]
The `queryClient.resetQueries` method allows consumers to reset the state of a set of queries.
Unfortunately, I believe that this behaves in an unexpected way when working with (de-) hydrated state.

From [the documentation](https://react-query.tanstack.com/reference/QueryClient#queryclientresetqueries):
> If a query has initialData, the query's data will be reset to that.

It looks like `initialData` for hydrated queries is the hydrated data, not the data that the query was initialized with _before_ it was dehydrated.

I understand that this may potentially be controversial, but from a consumers perspective I would expect the `resetQueries` method to reset back to the very initial state.

**To Reproduce**
I created an example here: https://codesandbox.io/s/reset-queries-forked-n56iy?file=/src/App.tsx
As you can see, clicking the "Reset" button doesn't change anything about the hydrated query's state.

**Expected behavior**
I would expect the query's data to be reset to `undefined`, its state set to `"idle"`, etc.

**Comment by TkDodo** [comment]
When hydrating, a new Query is created for the empty query client. When creating a new Query, the data passed to it is considered the initialData - this seems to be expected.

> It looks like initialData for hydrated queries is the hydrated data, not the data that the query was initialized with before it was dehydrated.

If the query is _created with_ the hydrated data because it does not exist yet, like you do in the example with:

```
const queryClient = new QueryClient();
hydrate(queryClient, dehydratedState);
```

then yes, the hydrated data is the initial data. There is no "state before" that because the query does not exist.

However, if there is a state before, like when you do:

```
const queryClient = new QueryClient();

queryClient.setQueryData(["hydrated"], "some data");

hydrate(queryClient, dehydratedState);
```

then the hydration only sets the data on the already existing query (conditionally, if the hydrated data is newer then the already present data), and resetting will get the query back to the "state before". Hope that makes sense.

**Comment by DerJacques** [comment]
Hi @TkDodo Thank you for your thorough reply.
What you write absolutely makes sense.

I guess what I would love to be able to do is just be able to reset a query's data (in practice making it `undefined`) and resetting its loading states, independent of any initial data it may have had at some point.

But I understand how that would probably be more of a new feature than a bugfix (assuming the current behaviour is the expected behaviour), so I'll close this issue.

Thanks again for the helpful reply and the idea on how to circumvent the problem.
