### ISSUE TITLE
Cache never expires

### ISSUE THREAD

**Issue by jpgarcia** [tannerlinsley/react-query#2420]
**Describe the bug**
Not sure if I'm missing something but it seems that `cacheTime` is ignored when a component that uses `useQuery` has been un-mounted and new one is mounted using the same `queryKey`

**To Reproduce**
I have created a sample to show the unexpected behavior @ https://codesandbox.io/s/infallible-fast-5f4tf

1. Navigate to the root `/` to display the list of characters
2. Click on a character to navigate to **Character Summary** page. 
3. Wait for at least 3 seconds to expire the cache
4. Click on **More Details** link

**Expected behavior**
As we are waiting for the cache to be expired, the  **Character More Details**  view should display the **loading...** control instead of the **fetching...**

The only way cache is being expired is:

1. Click **Home** from the **Character Summary** or **Character More Details** 
2. Wait at least 3 seconds to expire the cache
3. Click on a character to navigate to **Character Summary** page. 

After doing this you will see the **loading...** component as expected

**Comment by jpgarcia** [comment]
Hi @TkDodo! Did you have a chance to check the code sandbox example? 
I'm not sure if I'm doing something wrong or it is actually a bug.
Thank you!

**Comment by TkDodo** [comment]
`cacheTime` only "kicks in" as soon as your query transitions to `inactive`, which is, as soon as your last observer unmounts. It's used to garbage collect inactive queries. In your case, your query never goes to inactive - you have an active observer, and then go directly to a different page. If you go `Home` again and wait 3 seconds, the query will be garbage collected correctly. I'd suggest to always use the `<ReactQueryDevtools />` so that you can see in which state your queries are in and what is in the cache.
