### ISSUE TITLE
Long stale time doesn't behave as expected 

### ISSUE THREAD

**Issue by carpben** [tannerlinsley/react-query#2486]
**Describe the bug**

Creating query with a huge cache and stale time is ingored. Request happens anyway and data is considered stale in dev tools. 

**To Reproduce**

```
export const ALL_THEMES_KEY = 'themes';
export const ONE_YEAR = 1000 * 60 * 60 * 24 * 365;

export const themeQueryParams: QueryParams = {
    queryKey: ALL_THEMES_KEY,
    queryFn: () => fetchFunction({ endPoint:ALL_THEMES_KEY }),
    config: {
        staleTime: ONE_YEAR,
        cacheTime: ONE_YEAR,
        suspense: true,
    },
};
```

use this queryParams with `queryClient.preFertch` earlier and `useQuery` later in the .

**Expected behavior**
network request only sent on the initial query. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13496178/126619875-54e11a40-4981-4ea4-8cad-fecfc5547f08.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac 11.4
 - Browser: [e.g. chrome, safari] Chrome 
 - Version: [e.g. 22] 91

**Comment by TkDodo** [comment]
If your query shows up as `stale`, your staleTime is likely not picked up. It should be shown as `fresh` in the devtools.

I don't think that passing `config` is correct. Since v3, we are using a collapsed config, please see the migration guide: https://react-query.tanstack.com/guides/migrating-to-react-query-3#the-object-syntax-for-usequery-now-uses-a-collapsed-config

If this doesn't work, please provide a codesandbox reproduction so that I can take a closer look.

**Comment by carpben** [comment]
@TkDodo This does indeed solve the problem.

**Comment by carpben** [comment]
@TkDodo , Is this new signature true to `clientQuery.prefetch(params)` as well?

**Comment by TkDodo** [comment]
For `queryClient.prefetchQuery`, yes
