### ISSUE TITLE
Calling queryClient.setDefaultOptions does not trigger re-render

### ISSUE THREAD

**Issue by serhii-yakymuk** [tannerlinsley/react-query#2514]
**Describe the bug**
Changing defaultOptions in queryClient instance is not triggering re-render of React tree.
In my case, I'm trying to change default option of `enabled` from `false` to `true` in useEffect.
Unfortunately, queries remain idle until something else triggers a re-render of a component.

**To Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/s/shy-morning-uyhbu?file=/src/index.js)
2. Observe that `Example` component does not re-render after default options change - query remains idle

**Expected behavior**
Components that have `useQuery` are re-rendered after options change  

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 92

**Comment by TkDodo** [comment]
I’m not sure if setDefaultOptions should trigger a re-render. An easy workaround would be to keep the enabled boolean in react local state, which would trigger a re-render of the whole subtree.

**Comment by serhii-yakymuk** [comment]
@TkDodo Yes, that's what I'm currently doing to resolve this issue, thanks :)
If that is an intended behavior - feel free to close this issue.
Maybe it;s worth mentioning this behavior in the [docs](https://react-query.tanstack.com/reference/QueryClient#queryclientsetdefaultoptions)

**Comment by TkDodo** [comment]
Not sure if it’s intended or not, I think we could technically inform observers about that change. @tannerlinsley ?

**Comment by TkDodo** [comment]
Thought about this, and I don't think that setting defaultOptions _should_ inform observers. I think it would lead to unnecessary renders in many situations, e.g. if I have a certain config, like `staleTime`, explicitly set on my query, and we update the defaultOptions. The query wouldn't care that the default options change because it uses its own option.

I think the solution to keep those options in state and trigger a re-render with it is the better one.
