### ISSUE TITLE
Unmounting a component in a useMutation onSuccess

### ISSUE THREAD

**Issue by joecritch** [tannerlinsley/react-query#252]
React's warning "_Can't perform a React state update on an unmounted component_." occurs whenever an unmounted is triggered from a useMutation onSuccess callback.

I have made a test case here: https://codesandbox.io/s/flamboyant-robinson-hrzmo (click the button, and the warning will show in the console).

Interestingly, if it is refactored to use `await mutate()`, no warning occurs.

(Forgive me if I have missed an anti-pattern in my consumer code, but I don't think so?)

**Comment by tannerlinsley** [comment]
This is slightly problematic because you are using a side effect from useQuery to unmount the component instance that useQuery is attached to. So after you have unmounted the query, useQuery attempts to continue with its lifecycle and thus you get a setState/dispatch on a component that has been unmounted. Other than setting a timeout, I'm not sure if there is a way to solve this within React Query

**Comment by tannerlinsley** [comment]
Here's an example: https://codesandbox.io/s/serverless-wildflower-vd7xt
