### ISSUE TITLE
Incorrect documentation for useQuery's API

### ISSUE THREAD

**Issue by TriStarGod** [tannerlinsley/react-query#2533]
**Describe the bug**
There are some use cases where the developer may want reactive results for `useMutation` and there is no corresponding useQuery's `queryFn`. The API documentation found at https://react-query.tanstack.com/reference/useQuery mention

> `queryFn: (context: QueryFunctionContext) => Promise<TData>`
> 
>     Required, but only if no default query function has been defined See Default Query Function for more information.
>     The function that the query will use to request data.
>     Receives a QueryFunctionContext object with the following variables:
>         queryKey: EnsuredQueryKey: the queryKey, guaranteed to be an Array
>     Must return a promise that will either resolve data or throw an error.

thus I was worried I couldn't call `useQuery` without an `queryFn`. However, upon testing, it worked with no visible issues. Now my remaining issue is to set `{ exact: false }` with `useQuery`

**To Reproduce**
An example of my use case is outlined in the [codesandbox](https://codesandbox.io/s/react-query-reactive-mutation-results-txcz9?file=/src/index.js) example

**Expected behavior**
Further elaborate documentation or replace with Optional

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser: [e.g. chrome, safari] Firefox
 - Version: [e.g. 22] 90

**Additional context**
N/A

**Comment by TkDodo** [comment]
your example returns you the data from the cache, which it has because you put it there manually. It then does a background refetch, which fails, you can see this in the console where it says: `Missing queryFn`. So the docs are correct on this - you shouldn't `useQuery` without a queryFn - it doesn't make much sense.

If you just want to make the data from useMutation available in your app without having a corresponding query, you can just as well put it in react context, or any other global client state manager.

**Comment by TkDodo** [comment]
>  I was using Zustand before for caching both query and mutation results.

It's definitely not needed for query results, because `useQuery` can just give you your data wherever you need it. Copying it somewhere else would be mostly unnecessary state-syncing.

For mutations, I usually have a corresponding query (update a todo - write the result back to the todos query) so that avoids the problem for mutations.

>Is there a reason why mutation only reactive results can't cached / accessed but query ones can?

for this, we have an open issue: https://github.com/tannerlinsley/react-query/issues/2304
