### ISSUE TITLE
Typing destructed useQuery props return true/false instead of boolean?

### ISSUE THREAD

**Issue by rnnyrk** [tannerlinsley/react-query#2543]
**Describe the bug**
Because I want to restructure data, or for whatever reason, I want to destruct the props and data separately from the `useQuery`. Although the typing of props do not contain a boolean, instead they return true/false?

**To Reproduce**
1. Create a `useQuery`
2. Destruct the `data` and `props` separately 

**Expected behavior**
The typing of props should contain boolean instead of true/false

**Screenshots**
<img width="1287" alt="Screenshot 2021-08-05 at 17 17 43" src="https://user-images.githubusercontent.com/4519142/128375620-9ee13b7e-ab72-44cf-942e-b36772fa841e.png">

<img width="1756" alt="Screenshot 2021-08-05 at 17 17 36" src="https://user-images.githubusercontent.com/4519142/128375597-a12638e7-66bb-40e5-9fc8-4e9b39c95a0f.png">

**Comment by TkDodo** [comment]
Please reproduce the issue in codesandbox. The status flags can be used as a discriminated union so this is on purpose and I’ve never seen / had any issues with it

**Comment by rnnyrk** [comment]
@TkDodo Thanks for your reply. Here is the same issue in CodeSandbox: https://codesandbox.io/s/stupefied-river-r0cp3?file=/src/Tasks.tsx

**Comment by TkDodo** [comment]
the problem seems to be something else here:

- you type `useQuery` by passing a generic (`useQuery<{ getTasksByUser: UserTask[] }`)
- but your actual hook is typed to return a `UseQueryResult<UserTask[] | undefined>` (btw, `undefined` is unnecessary here, because react-query will always add `undefined` to the union type)

I don't think it just works to destruct `data` and then change the type to that, I think that's where the error comes from. Various solutions to this problem:

1) Don't type the hook, let the result be inferred: [sandbox](https://codesandbox.io/s/optimistic-bhabha-o198l?file=/src/Tasks.tsx)
2) use the `select` option to perform data transformations (in combination with typing the `queryFn` rather than passing a generic to the hook: [sandbox](https://codesandbox.io/s/xenodochial-ptolemy-jufsz?file=/src/Tasks.tsx)

I would prefer a combination of the two, which would look like this: [sandbox](https://codesandbox.io/s/hardcore-heisenberg-8zcox?file=/src/Tasks.tsx).  I think it's the least amount of ts code to write, which is good in this case, and the select options is very idiomatic react-query.

Hope that these approaches can solve the problem for you.

**Comment by rnnyrk** [comment]
@TkDodo Thanks for the suggestions. First time really using `react-query` after moving from Redux, so still have to get used to the complete API with all the options and best practices. Rewrote my calls to using the `select` instead of destructing and using `UseQueryResult` as a return type instead of the generic.
