### ISSUE TITLE
Fetch function runs when enabled is set to false

### ISSUE THREAD

**Issue by carpben** [tannerlinsley/react-query#2566]
**Describe the bug**
Fetch function runs when enabled is set to false via clientQuery.setQueryDefaults and query initiated via prefetch. 

**To Reproduce**
```ts
queryClient.setQueryDefaults(QUERY_KEY, {
    queryFn: async () => {
        console.log('${QUERY_KEY} req called');
        const data = await diyGet({
            pathSuffix: getFetchUrl(),
        });

        return (data as { results: PageElementData[] }).results;
    },
    enabled: false,
});

queryClient.prefetch(QUERY_KEY)
```

**Expected behavior**
Should not run. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13496178/129158098-3d5b01ad-2ab7-4e05-8710-adc4e9557723.png)
![image](https://user-images.githubusercontent.com/13496178/129158251-db74c478-5862-4126-bff6-dccd846fc26b.png)
![image](https://user-images.githubusercontent.com/13496178/129158473-a1656886-70ce-4df1-80b4-fbe42abbfc6a.png)

**Comment by TkDodo** [comment]
I don't think prefetching is tied to `enabled`. Enabled just makes sure that when you create an observer, e.g. via `useQuery`, that this observer will not trigger a fetch even though it normally would. If you manually trigger a fetch via prefetching, or e.g. via `queryClient.refetchQueries()`, or by calling `refetch()` returned from `useQuery`, it will still fetch.

So I'd say this works "as expected"

**Comment by carpben** [comment]
Interesting. Personally, I wouldn't expect a property named `enabled` to only apply for observer triggering. 

After a short search, it is not how `enabled` is introduced in the documentation (https://react-query.tanstack.com/guides/dependent-queries), and not how it is understood by the community (https://stackoverflow.com/questions/63397534/conditionally-calling-an-api-using-react-query-hook).

**Comment by TkDodo** [comment]
hm, let's take the example from the docs:

```
 const { isIdle, data: projects } = useQuery(
   ['projects', userId],
   getProjectsByUser,
   {
     // The query will not execute until the userId exists
     enabled: !!userId,
   }
 )
```

the query in this component will definitely not execute as long as `userId` is falsy. What happens is, and you can see this in the react-query devtools as well, is that a cache entry is created from the key `['projects', undefined]`, which will not have any data and will remain in idle state.

if you now call `queryClient.prefetchQueries(['projects', 5], getProjectsByUser)` for user 5, we will create a new cache entry for the key `['projects', 5]` and put the data there. After all, that's what pre-fetching is for: To create a cache entry even _before_ we have any active observers, so that if we then mount a component later that uses this query, we'll have the data readily available.

Can you maybe elaborate what use-case you have where you have a disabled query, and want to prefetch it, but the prefetch shouldn't do anything because of enabled?

**Comment by carpben** [comment]
I understand you point. I understand why `enabled` was meant to be used in `useQuery`. 

my use case is to disable all queries for a certain key until a certain condition is met, and writing the logic in one centralized place (without having to write the logic in each of the query consumers - `useQuery` or `queryClient.refetch`). I tried using 
```


`clientQuery.setQueryDefaults({})
It's not about a specific use-case, it's about what I or others who use my code would expect. Let's leave t
```ts
queryClient.setQueryDefaults(QUERY_KEY, {
   ...
   enabled: false 
};
```
and 
```ts
queryClient.setQueryDefaults(QUERY_KEY, {
   ...
    get enabled() {
        return isQueryReady();
    },
});
```
Both worked well for `useQuery` but not for `queryClient.prefetch` or `queryClient.refetch`. 

So I guess I have two things to say: 
1. If the default is set to disabled I would not expect prefetch or refetch to execute. The `enabled` isn't ideal. 
2. What is the React-Query way to conditionally trigger a query in a centralized way?

**Comment by TkDodo** [comment]
since all methods like `prefetchQueries` or `refetchQueries` are imperative, meaning they will only execute once you call them explicitly, the best way would probably be to wrap them in an if statement and just not call them when you are not ready? The condition itself can be abstracted away so that you can re-use it both for the enabled option as well as other guards

**Comment by verekia** [comment]
@TkDodo Is there any way to not have those inactive `['projects', undefined]` entries in the cache? It feels like there should be a way to not register them at all if some condition is not met, since we cannot call the hook conditionally because it's against the rules of hooks.

What I ended up doing it is my own wrapper that assigns some special key for those inactive queries, like :
```jsx
const useQueryWrapper = (key, fn, options) =>
  useQuery(
    options?.enabled ?? true ? key : 'inactive-query',
    fn,
    options
  )
```

This way it's a bit less confusing in RQ Devtools, all these kinds of inactive queries are simply saved in the `inactive-query` key. But this is not an elegant workaround. Any insight on how to do this better would be appreciated.

**Comment by TkDodo** [comment]
Latest version ships with an improvement in the devtools that marks queries where all observers are disabled as `disabled` to make it less confusing
