### ISSUE TITLE
useQuery typedefs throw errors when using passed functions for onSuccess

### ISSUE THREAD

**Issue by shamilovtim** [tannerlinsley/react-query#2588]
**Describe the bug**
useQuery onSuccess typedefs are inflexible and only accept a function definition such that
`(QueryReturn:queryReturn) => void` however any function can be passed to onSuccess, for example one could pass the following function to onSuccess:

`const capitalize = (str: string) => str.toUpperCase()`
useQuery(..., { onSuccess: capitalize });

if you were to try to use the typed `data` from this query it would be `any` because `capitalize` has broken its inference

**Comment by TkDodo** [comment]
not sure what you mean. Usually, it would be good to provide a codesandbox reproduction. I did that for you, and it shows that it works well: https://codesandbox.io/s/react-query-onsuccess-typings-x4m1w

note that `onSuccess`  takes as input what your `queryFn` returns. So this `captialize` will only work for `onSuccess` if your `queryFn` returns a `Promise<string>`. Since you haven't provided that code (haven't provided much really), I can't say why it doesn't work in your case....

**Comment by shamilovtim** [comment]
Yeah this was our mistake. The param in onSuccess was supposed to be the response return but our typedef didn't reflect it due to some tangled business logic. We would've expected a type error to happen, but instead we got broken inference.
