### ISSUE TITLE
useQuery executes request with false in key array

### ISSUE THREAD

**Issue by denisborovikov** [tannerlinsley/react-query#259]
According to the [docs](https://github.com/tannerlinsley/react-query#pass-a-query-key-array-with-a-falsy-item), if an array contains falsy items, the request won't execute, but it does.

https://codesandbox.io/s/delicate-feather-cr8c5

**Comment by tannerlinsley** [comment]
The docs have been updated to remove the deprecated option to supply falsey items in the key. This can no longer be supported since query keys like `['todos', pageIndex]` need to work, even when passed a `null` or `0` as `pageIndex`. You'll need to use a short circuit or function to do this now: `shouldFetch && ['todos', pageIndex]`
