### ISSUE TITLE
Some labels in the devtools are unreadable

### ISSUE THREAD

**Issue by colepeters** [tannerlinsley/react-query#2595]
**Describe the bug**
Some of the labels in the devtools are unreadable — they use white text on a very light grey background. I understand I could customize the styling, but I think this text should be accessible by default.

**To Reproduce**
1. Include the devtools in your app
2. Open the devtools

**Expected behavior**
The text should be readable

**Screenshots**
![image](https://user-images.githubusercontent.com/1713932/130486648-bba6475c-c8b5-4742-801b-11da55782bb4.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 92.0.4515.131

**Additional context**
I've just started using this library over the past 2 days, and I'm loving it! Super appreciate all the work that's gone into this. Thank you!

**Comment by TkDodo** [comment]
Must be something with your global styles interfering here, because that’s not how the devtools look in an isolated app, e.g. our examples. It should look like this:
![5B3B4B8F-7CC0-419B-AA80-2D9155B69A50](https://user-images.githubusercontent.com/1021430/130502231-7fa15722-35a9-4ff5-b386-d79fb84edfc4.jpeg)

**Comment by colepeters** [comment]
Yikes, sorry about that! I did inspect the offending elements to see if we had any collisions, and none came up, but something must have slipped past me. Thanks and sorry for the noise!
