### ISSUE TITLE
isLoadingError doesn't work as expected

### ISSUE THREAD

**Issue by mhesham32** [tannerlinsley/react-query#2666]
**Describe the bug**
`isLoadingError` is supposed to be as mentioned in the docs 
```
Will be `true` if the query failed while fetching for the first time.
```
but it doesn't give true back until it finished all the retries which take a long time

**To Reproduce**

```js
function queryFn() {
   return  Promise.reject(new Error('error'))
}

const {isLoadingError} = useQuery('key', queryFn);
console.log(isLoadingError)
// false
// false
//false
// true
```
I think it should be the opposite of this it should be false after all tries are done and true while trying at least that is what I understand from the Docs

**Expected behavior**
```js
//true
// true
//true
// false
```

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [chrome,]
 - Version: [93]

**Comment by TkDodo** [comment]
> but it doesn't give true back until it finished all the retries which take a long time

that is expected. retries are an "internal" process, which doesn't change the state of the query on purpose. Imagine making a request, which fails, so it gets retried, and then it succeeds. If the query would transition to `error` state in between, the user would likely get shown an error screen. But the whole idea of automatic retries is to hide that from the user and make the process transparent.

If you want to get information about failed retries, have a look at the returned `failureCount: number` field. It should increase by one for each retry. `isLoadingError` is only there to distinguish between errors that happen on the first load and  "background errors", because in those cases, it might be better to show stale data instead of the error.
