### ISSUE TITLE
Query status resets to "loading" when refetching query that has never succeeded

### ISSUE THREAD

**Issue by esseb** [tannerlinsley/react-query#2673]
**Describe the bug**
When a successful query (with status "success") is being refetched its status remains as "success".

If a query has never succeeded, however, its status resets from "error" to "loading" whenever data is being refetched. I would have expected a similar behavior to a successful query.

This is also a problem during initial rendering in SSR. If a prefetched query fails, the status becomes "loading" when the server renders the React app.

**To Reproduce**
I made a reduced testcase on https://codesandbox.io/s/react-query-error-loading-status-bug-dxmhi

The testcase itself (with steps to reproduce) can be viewed directly on https://dxmhi.sse.codesandbox.io/

**Expected behavior**
Status "error" should not reset to "loading" when React Query attempts to refetch the query.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**React Query version:**
v3.23.2

**Additional context**
The same issue was identified by @rvil in https://github.com/tannerlinsley/react-query/discussions/1208#discussioncomment-181742

The [documentation](https://react-query.tanstack.com/reference/useQuery) says status is
> `loading` if the query is in a "hard" loading state.
> This means there is no cached data and the query is currently fetching, eg `isFetching === true`"

The way the documentation is written could indicate the behavior I see is intentional since it only refers to cached data, but I would argue it is such non-obvious behavior, especially during SSR, that it should be considered a bug.

The same bug was reported and fixed [back in 2020](https://github.com/tannerlinsley/react-query/issues/529). There is no associated PR so I was unable to find the original fix, or verify that the fix ever made it into a release.

**Comment by TkDodo** [comment]
hmm, I'm not sure if the behaviour isn't really intentional as you also mentioned. Considering that if you have an erroneous query, and you mount a new observer, which would trigger a re-fetch, you would currently get a loading state, whereas you're proposing to give the user an `error` state with potential `isFetching: true` ?

also, how would this work with error boundaries please? I think the expectation with error boundaries is that you never get `status: 'error'` because the boundary handles them all...

**Comment by esseb** [comment]
> whereas you're proposing to give the user an `error` state with potential `isFetching: true` ?
Correct, that is what I am proposing.

> also, how would this work with error boundaries please? I think the expectation with error boundaries is that you never get status: 'error' because the boundary handles them all...
Are you referring to the case when query client (or the individual useQuery call) is configured with `{ suspense: true }` as described on https://react-query.tanstack.com/guides/suspense ?

**Comment by TkDodo** [comment]
> Are you referring to the case when the query client (or the individual useQuery call) is configured with { suspense: true } as described on https://react-query.tanstack.com/guides/suspense ?

you can use error boundaries _without_ suspense by setting `useErrorBoundary: true` on any query, in which cases fetching errors will be caught and re-thrown during the next render cycle, so that the error boundary can pick it up.


> Expected behavior
Status "error" should not reset to "loading" when React Query attempts to refetch the query.

Btw, the status does reset to `loading`, but the `error` will still be there if you want to display it instead. You will have:

```
status: 'loading',
data: undefined,
error: 'myError'
```

so it would just depends on how you do status checking / what you check for

**Comment by esseb** [comment]
For this particular page on my website `useErrorBoundary: true` is not appropriate to use as I perform other queries in the same component and I want to render the page based on the result of the two queries when the two queries have settled.

> Btw, the status does reset to loading, but the error will still be there if you want to display it instead.

This does not appear to be the case during SSR. In the browser it is true, however.

**Comment by TkDodo** [comment]
I wasn’t suggesting that you’d use error boundaries - i was asking how the proposed change would work if someone were to use error boundaries, because I don’t think it would work well together. 

> This does not appear to be the case during SS

right, because only successful queries are included in hydration afaik

**Comment by esseb** [comment]
> i was asking how the proposed change would work if someone were to use error boundaries, because I don’t think it would work well together

Ah, I misunderstood. I can test tomorrow and investigate.

**Comment by TkDodo** [comment]
> This does not appear to be the case during SSR. I suspect the error object is not included in the hydrated state.
>
>In the browser the error object is present in the useQuery result, however.

On another note, doesn't [this comment](https://github.com/tannerlinsley/react-query/discussions/1208#discussioncomment-109723) show some ways to include errors in the hydration process? The "issue" seems to most likely be around `Error` objects not being serializable out of the box. That being said, react-query doesn't now what is _inside_ the Error - it could also _not_ be an `Error` instance, theoretically ... so the solution provided in that comment seems like a good alternative, does it not?

**Comment by esseb** [comment]
I found that comment originally because I was trying to figure out why errors were not included in the hydrated state 🙂. I forgot to include it in the codesandbox testcase.

I've updated the testcase on https://codesandbox.io/s/react-query-error-loading-status-bug-dxmhi + https://dxmhi.sse.codesandbox.io/ to use `shouldDehydrateQuery: () => true` now to ensure errors are included in the hydrated state. Same result as in my original report. SSR renders the full page loading spinner, and the loading spinner is rendered each time the viewport regains focus.

Trying to test the `useErrorBoundary: true` case now to see if my proposed fix causes any issues if that is enabled.

**Comment by TkDodo** [comment]
the erroneous query is now dehydrated, you can see it in the page source:

```
{"state":{"dataUpdateCount":0,"dataUpdatedAt":0,"error":{"status":404,"name":"MyError"},"errorUpdateCount":1,"errorUpdatedAt":1632130687740,"fetchFailureCount":1,"fetchMeta":null,"isFetching":false,"isInvalidated":false,"isPaused":false,"status":"error"},"queryKey":"fwe","queryHash":"[\"fwe\"]"}]}}
```

> SSR renders the full page loading spinner, and the loading spinner is rendered each time the viewport regains focus.

this is because you choose to do so by checking:

```
  if (fwsResult.isLoading || fweResult.isLoading) {
    return <p>Full page loading spinner</p>;
  }
```

yes, the erroneous query will transition to `loading` state because it has no data yet, this is expected. You can perform your check differently, say, by doing:

```
const fwsHasDataOrError = fwsResult.data || fwsResult.error
const fweHasDataOrError = fweResult.data || fweResult.error
if (!fwsHasDataOrError || !fweHasDataOrError) {
    return <p>Full page loading spinner</p>;
}
```

That would give you the result that you'd like to see.

I also have a blog post on the status checking topic and how it influences ux: https://tkdodo.eu/blog/status-checks-in-react-query

**Comment by esseb** [comment]
Yeah, I was already doing a check like that before deciding to try `isLoading` instead when I noticed the documentation saying it only was true for the initial load.

It would be nice if I could relying on `isLoading` even for requests that have failed, it feels very odd that it behaves differently for errors.

**Comment by TkDodo** [comment]
this is becoming a philosophical discussion about what `isLoading` should be. It currently means: a request is happening and `data` is undefined. Yes, this is also true if you previously had an error. But I'm not comfortable changing that definition because it would mean a breaking change for many use-cases, for example:

- display loading spinner
- display error, with a `refetch` button
- user clicks refetch
- request goes out, but _nothing_ happens visually, because we are still in `error` state and show the error.
--> we currently get the loading spinner here, and this is the desired behaviour most of the time imo.

**Comment by esseb** [comment]
The difference is maybe between the two types of errors. I consider 404 and 500 to be successful errors, no amount of refetching should make that result become successful (unless the server gets fixed I guess). A network error, however, is an actual error where refething is useful.

I don't have a good suggestion on how to handle this in the react query api :/

**Comment by TkDodo** [comment]
> The difference is maybe between the two types of errors. I consider 404 and 500 to be successful errors, no amount of refetching should make that result become successful (unless the server gets fixed I guess). A network error, however, is an actual error where refething is useful.

the best way to map that mental model to react-query is by returning successful responses (resolved promises), for those status codes That way, you'll get your `errors` and your `data` mixed up in the `data` property, and the `error` property will only ever be filled with other types of errors, like network errors.

**Comment by esseb** [comment]
> the best way to map that mental model to react-query is by returning successful responses (resolved promises), for those status codes

I think I'll go with that solution. Thank you for your help 🙂.
