### ISSUE TITLE
Active queries not refetched after calling invalidateQueries with refetchActive set to true

### ISSUE THREAD

**Issue by szszoke** [tannerlinsley/react-query#2728]
**Describe the bug**
Active queries not refetched after calling `invalidateQueries` with `refetchActive` set to `true`.

**To Reproduce**
1. Go to https://codesandbox.io/s/jovial-neumann-36wqj
2. Open your browser's developer tools and go to the `Network` tab
2. Click on the `invalidate` button repeatedly
3. Observe that no HTTP request is made each time after pressing the `invalidate` button.

**Expected behavior**
Active queries are refetched after calling `invalidateQueries` with `refetchActive` set to `true`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 92

**Additional context**

The provided CodeSandbox is a fork of the simple example from here: https://react-query.tanstack.com/examples/simple

I updated `react-query` to the latest version.

I also added an `invalidate` button. When this button is clicked it calls `invalidateQueries` on the query client with `refetchActive` set to `true`.

**Comment by TkDodo** [comment]
The problem seems to be that you are combining various boolean flags passed to `invalidateQueries`. I'm not a fan of this boolean api because it can create impossible states and is not easy to reason about, but changing that would be a breaking change.

I've traced the issue back to `fetching: true`, because that means "exclude non-fetching queries", or, in other words: "only include queries that are fetching". That filter doesn't make much sense here, but the `QueryFilters` interface is the same everywhere.

[The docs](https://react-query.tanstack.com/guides/filters) also mention that:

> fetching?: boolean
When set to true it will match queries that are currently fetching.
When set to false it will match queries that are not fetching.

you're setting it to true, so it will _only_ match queries that are currently fetching. To simply include all queries, independent of their fetching state, just leave that flag to `undefined` (don't pass it in at all).

Removing `fetching: true` from your filters make the refetching work as expected.

**Comment by szszoke** [comment]
I made a wrong assumption then. I assumed that `active`, `inactive` and `fetching` would work as an `or` predicate and by setting all three of them to `true` I could include queries from those three states.

**Comment by szszoke** [comment]
Thanks for clearing this up @TkDodo!

Not passing the filter flag resolved the issue both in the minimal example and in the original application where the issue was found.
