### ISSUE TITLE
Types no longer inferred correctly

### ISSUE THREAD

**Issue by jamesots-tq** [tannerlinsley/react-query#2753]
In version 3.24.0 and earlier, I can call useQuery like this, without needing to specify the generic types:

```ts
export function useGetThing(
  id: string | undefined,
  options?: UseQueryOptions<Thing | undefined>
): QueryObserverResult<Thing | undefined> {
  return useQuery(
    ['key', text],
    () => (id === undefined ? undefined : api.getThing(id)),
    options
  );
}
```

I often do this so that I can have a call to `useGetThing(id, {enabled: Boolean(id)})`, and have it only call the api when the id is not undefined - usually as it's the result of a previous query. I can't call api.getThing with an undefined id, so I have the check in the query function and have it return undefined when the query is not enabled. (Of course, this doesn't get called when the query is disabled, but it keeps TypeScript happy).

However, since 3.24.1, I have to include the type in the useQuery call: `useQuery<Thing | undefined>(...)`, otherwise it complains that 'Thing | undefined is not assignable to Thing'.

(I imagine there may be better ways to write my useGetThing function, but nevertheless, this still appears to be a regression).

**Comment by TkDodo** [comment]
hm, weird. it boils down to `options`. If those are removed, it works fine. I did some stuff around there so it seems to be a regression, sorry for that.

> I imagine there may be better ways to write my useGetThing function

In the meantime: what I'm usually doing is rejecting the promise instead of including `undefined` as a valid return value. I guess since you disable the query, it's a this should never happen scenario anyways, so this should work:

```
export function useGetThing(
  id: string | undefined,
  options?: UseQueryOptions<Thing | undefined>
): QueryObserverResult<Thing | undefined> {
  return useQuery(
    ['key', text],
    () => (id === undefined ? Promise.reject(new Error("no id provided")) : api.getThing(id)),
    options
  );
}
```

**Comment by TkDodo** [comment]
I think because we've made options more strict now, if you pass options in, but then use the `(key, fn, options)` syntax, you'll get the error now, and that is correct. `options` allow all options, so you could also pass in `queryKey` or even `queryFn` to your custom hook. But those fields don't do anything if you use that syntax, so we've removed them. If you omit them as well, it will work:

```
options?: Omit<UseQueryOptions<Thing | undefined>, "queryKey" | "queryFn">
```

it will also make it impossible for users of `useGetThing` to pass in an option that doesn't do anything, which is generally a good thing.

alternatively, you can use the object syntax:

```
export function useGetThing(
  id: string | undefined,
  options?: UseQueryOptions<Thing | undefined>
) {
  return useQuery<Thing | undefined>({
    queryKey: ["key", id],
    queryFn: () => (id === undefined ? undefined : api.getThing(id))),
    ...options
  });
}
```

and then you can decide if you spread `options` first or last, and depending on that, `queryKey / queryFn` will do something or not. But I think it's generally not so nice if a function allows for parameters that then have no effect at all...

**Comment by jamesots-tq** [comment]
I hadn't thought of returning a rejected promise — that works really nicely. I actually spotted a couple of places where someone had got the types wrong before, but the new types pick it up, so I'm happy with this now :)
