### ISSUE TITLE
failureCount doesn't increment after failed refetch

### ISSUE THREAD

**Issue by itayganor** [tannerlinsley/react-query#2754]
**Describe the bug**
The value of `query.failureCount` doesn't increment if a `query.refetch()` fails.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-query-failurecount-doesnt-could-refetch-eqqbf
2. After `Loading...`, you'll see `Error #1` which is good - because it's the first time the query fails.
3. Click `Refetch`. 
4. After `Loading...` you'll see `Error #1` which is bad - it's the *second time* the query fails.

The console shows that `failureCount` is being reset every time a new fetch attempt is made.
![image](https://user-images.githubusercontent.com/6430313/135614134-d6ccfd8e-4253-47ab-80d1-ddd7d5a9ad94.png)

**Expected behavior**
Since there was no "success" state in between the errors, `failureCount` should be incremented by one.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 94
 - Version: 3.24.5

**Comment by TkDodo** [comment]
I think the docs are a bit light on that topic. `failureCount` is actually the internal failure count for retries. It is also passed to the `retry` function. With 3 retries, if they are all failing, your component will re-render in between with a new failure count (but still with `loading` state!). It will then go to `4` (1 initial fetch + 3 retries) eventually, and then the query is rendered in `error` state.

if you then re-fetch, `failureCount` will go back to 0. Otherwise, retry mechanism relying on `failureCount` wouldn't work. So it's essentially the failure count for a single fetch operation. Hope that makes sense.

**Comment by TkDodo** [comment]
please contribute to the docs if you think they could be more explicit in that regard, but I'm closing the issue because I'm pretty certain this works as expected.

**Comment by itayganor** [comment]
I see why it's helpful for the retry mechanism, but the reason for exposing it to the user (via the `query` object) isn't clear.

At first, I thought of `failureCount` to be the counter for failed fetch attempts. Like something I could rely on when displaying different components to the users. I wanted to create a generic query error component that lets you refetch the query, but the *refetch* button will be hidden if there were more than 5 retries.

Since `failureCount` was accessible, I thought this was its meaning. As you described, it is used for an internal mechanism. And so the obvious question is - should it be exposed? Can you find a use case for `failureCount` as a value outside of the internal logic of React Query?

**Comment by TkDodo** [comment]
> Can you find a use case for failureCount as a value outside of the internal logic of React Query?

It is considered a good ux to show some indicator if something takes longer as expected. Viktor describes it here pretty well:

https://twitter.com/vponamariov/status/1386331353025814532

![Screenshot 2021-10-04 at 18 08 41](https://user-images.githubusercontent.com/1021430/135885982-64de2dd3-d1d7-4c37-a10d-773ad966277a.png)

you can achieve that because your component will re-render with a different `failureCount`, even though the status is still `loading`...

**Comment by itayganor** [comment]
Nice, I loved the example.
What would be, then, the best way to track the total failure count for a query?

**Comment by TkDodo** [comment]
> What would be, then, the best way to track the total failure count for a query?

increment a counter on the onError callback. But what would be the use-case for that?
