### ISSUE TITLE
refetchInterval type breaks utility for inferring query options

### ISSUE THREAD

**Issue by nkalpak** [tannerlinsley/react-query#2759]
**Describe the bug**
I have a utility type for inferring query options which takes the return type of a function and passes it to the `UseQueryOptions` generic. This utility type was working fine prior to v25, but now errors with `Object literal may only specify known properties, and 'queryKey' does not exist in type 'readonly unknown[]'`.

**To Reproduce**
[CodeSandbox with v25](https://codesandbox.io/s/react-query-issue-v25-ybp93?file=/src/App.tsx) - will error
[CodeSandbox with v24.6](https://codesandbox.io/s/react-query-issue-v24-6-3lgg6?file=/src/App.tsx) - won't error

**Expected behavior**
I believe the utility type should work as it did previously. I've gotten it to work by passing `string[]` as the `QueryKey` generic parameter to `UseQueryOptions`, but then `queryKey` only accepts a string array and errors whenever a string is passed. [Here's a CodeSandbox with that behavior.](https://codesandbox.io/s/react-query-issue-v25-partial-fix-kwlix)

**Comment by TkDodo** [comment]
interesting. the root of the error seems to be:

```
Types of property 'refetchInterval' are incompatible.
        Type 'number | false | ((data: User[] | undefined, query: Query<User[], Error, User[], QueryKey>) => number | false) | undefined' is not assignable to type 'number | false | ((data: User[] | undefined, query: Query<User[], Error, User[], string[]>) => number | false) | undefined'.
          Type '(data: User[] | undefined, query: Query<User[], Error, User[], QueryKey>) => number | false' is not assignable to type 'number | false | ((data: User[] | undefined, query: Query<User[], Error, User[], string[]>) => number | false) | undefined'.
            Type '(data: User[] | undefined, query: Query<User[], Error, User[], QueryKey>) => number | false' is not assignable to type '(data: User[] | undefined, query: Query<User[], Error, User[], string[]>) => number | false'.
              Types of parameters 'query' and 'query' are incompatible.
                Type 'Query<User[], Error, User[], string[]>' is not assignable to type 'Query<User[], Error, User[], QueryKey>'.
```

emphasis on:

```
Type 'Query<User[], Error, User[], string[]>' is not assignable to type 'Query<User[], Error, User[], QueryKey>'.
```

The problem with generic wrappers around useQuery is that you'd actually need to specifiy all 4 generics, while your version only supplies two. That means, for example, that the `select` option won't work: using `select` also errors on your v24 sandbox: https://codesandbox.io/s/react-query-issue-v24-6-forked-vgsu5?file=/src/App.tsx

You would also likely want to `omit` QueryKey and QueryFn from your options, because when consumers pass it, it will be overwritten with what you have set internally, so the options make no sense to pass in from the outside.

I currently see no quick fix apart from specifying all 4 generics, but I will keep looking.

**Comment by nghiepit** [comment]
Same issue, after upgrade to v25 my app has broken.

**Comment by nkalpak** [comment]
> interesting. the root of the error seems to be:
> 
> ```
> Types of property 'refetchInterval' are incompatible.
>         Type 'number | false | ((data: User[] | undefined, query: Query<User[], Error, User[], QueryKey>) => number | false) | undefined' is not assignable to type 'number | false | ((data: User[] | undefined, query: Query<User[], Error, User[], string[]>) => number | false) | undefined'.
>           Type '(data: User[] | undefined, query: Query<User[], Error, User[], QueryKey>) => number | false' is not assignable to type 'number | false | ((data: User[] | undefined, query: Query<User[], Error, User[], string[]>) => number | false) | undefined'.
>             Type '(data: User[] | undefined, query: Query<User[], Error, User[], QueryKey>) => number | false' is not assignable to type '(data: User[] | undefined, query: Query<User[], Error, User[], string[]>) => number | false'.
>               Types of parameters 'query' and 'query' are incompatible.
>                 Type 'Query<User[], Error, User[], string[]>' is not assignable to type 'Query<User[], Error, User[], QueryKey>'.
> ```
> 
> emphasis on:
> 
> ```
> Type 'Query<User[], Error, User[], string[]>' is not assignable to type 'Query<User[], Error, User[], QueryKey>'.
> ```
> 
> The problem with generic wrappers around useQuery is that you'd actually need to specifiy all 4 generics, while your version only supplies two. That means, for example, that the `select` option won't work: using `select` also errors on your v24 sandbox: https://codesandbox.io/s/react-query-issue-v24-6-forked-vgsu5?file=/src/App.tsx
> 
> You would also likely want to `omit` QueryKey and QueryFn from your options, because when consumers pass it, it will be overwritten with what you have set internally, so the options make no sense to pass in from the outside.
> 
> I currently see no quick fix apart from specifying all 4 generics, but I will keep looking.

It seems like currently the fix for me is to pass `any` as the fourth generic parameter to `UseQueryOptions` and omit `queryKey` and `queryFn` for good measure. Doing this will match the behavior of `v24.6`'s `queryKey` without breaking any of the type safety in the options (i.e. `queryKeyHashFn` and `refetchInterval` correctly infer the type of the `queryKey` that has been passed).

```ts
import * as ReactQuery from 'react-query';

type GenericFn = (...args: any[]) => any;
type UnwrapPromise<T> = T extends Promise<infer U> ? U : T;

type InferQueryOptions<T extends GenericFn> = Omit<
  ReactQuery.UseQueryOptions<
    UnwrapPromise<ReturnType<T>>,
    AxiosError,
    UnwrapPromise<ReturnType<T>>,
    any
  >,
  'queryFn' | 'queryKey'
>;

// With the above, query key ["users", () => 1, 1, { a: "b" }, [1]] passes,
// as well as "users" which matches the behavior of v24.6
```

**Comment by TkDodo** [comment]
that seems like a good workaround, because you're not expecting the consumers of that hook to pass in a query key anyhow. I came up with something similar: https://codesandbox.io/s/react-query-issue-v25-partial-fix-forked-cib46?file=/src/App.tsx

This version with also work with `select`. I don't think all the levels of indirection are worth it tbh. For example, in my solution, the type `T` could just as well be `User[]`. The hook is `useUsers`, it's tied to the return type of `getUsers` anyhow.

**Comment by nkalpak** [comment]
> that seems like a good workaround, because you're not expecting the consumers of that hook to pass in a query key anyhow. I came up with something similar: https://codesandbox.io/s/react-query-issue-v25-partial-fix-forked-cib46?file=/src/App.tsx
> 
> This version with also work with `select`. I don't think all the levels of indirection are worth it tbh. For example, in my solution, the type `T` could just as well be `User[]`. The hook is `useUsers`, it's tied to the return type of `getUsers` anyhow.

Yeah, the idea with `InferQueryOptions` was to be a low friction way to pass some common options (`onSuccess`, `onError`) from outside and have them be typed, so I think I can live with `select` not being typed when using `InferQueryOptions` as it falls into that remaining 10% of use cases that `InferQueryOptions` doesn't have to solve.

**Comment by TkDodo** [comment]
Got it. Of course it depends on your use-case, I think it's generally not ideal to allow _all_ query options for a custom hook. For example, you could do `useUsers({ staleTime: 5000 })` in one component and `useUsers({ staleTime: 1000 })` in another one. This is usually a setting that you only want to set _once_ per query key, because having different value here can't have any effect, as there is only one cache entry.
Not saying you have to change it, just from am interface design perspective, I think it's usually better to just allow certain options, e.g. with the `Pick` util, but YMMV.

As for the issue, do you think we can close it?

**Comment by nkalpak** [comment]
> Got it. Of course it depends on your use-case, I think it's generally not ideal to allow _all_ query options for a custom hook. For example, you could do `useUsers({ staleTime: 5000 })` in one component and `useUsers({ staleTime: 1000 })` in another one. This is usually a setting that you only want to set _once_ per query key, because having different value here can't have any effect, as there is only one cache entry. Not saying you have to change it, just from am interface design perspective, I think it's usually better to just allow certain options, e.g. with the `Pick` util, but YMMV.
> 
> As for the issue, do you think we can close it?

> Not saying you have to change it, just from am interface design perspective, **I think it's usually better to just allow certain options**

I think you're right, I'll probably try out using `Pick` and see how that goes.

As for the issue, I believe it can be closed, thanks for your time!
