### ISSUE TITLE
[feature request] support other thenable http libraries like superagent

### ISSUE THREAD

**Issue by probablyup** [tannerlinsley/react-query#282]
Currently the internals of `react-query` make some assumptions about the "fetch" call being supplied, specifically that it adheres to the browser fetch API design. This isn't directly called out in the docs though (I think) and the library could support more thenable data fetching paradigms without opening too many cans of worms...

A few things for example:

1. The `cancel` method that's called could be configurable (for superagent it's `abort`)
2. The response data key could be configurable (for superagent it's `response.body`, not `response.data`)

Curious to get your thoughts on this.

**Comment by tannerlinsley** [comment]
There are no internals of React Query that rely on fetch. The only requirement is a promise with the *optional* `cancel` method attached to it, which you can have do whatever you want.

**Comment by probablyup** [comment]
I think you're misunderstanding what I'm saying. I'm not saying it relies on fetch, just that it expects the thenable to use the same API as browser fetch in terms of cancellation, how the response object looks, etc. With a few configurable tweaks it could be made to work with more thenable APIs.

**Comment by tannerlinsley** [comment]
Ah. Honestly, I didn't design it to work with any particular standard on purpose, so that's purely convenience. But the idea is that as long as your library is capable of returning a promise with the `cancel` method (that can proxy to whatever other cancellation strategy you like), then it will work. I am open to suggestions to make this more flexible, but with a disclaimer that I don't want to add any vendor-specific optimizations unless they are clearly the 80%+ use case.

**Comment by cherniavskii** [comment]
Just wanted to note, that `fetch` promise doesn't have a `cancel` method.
So in terms of cancellation it doesn't match any of the fetching libraries

**Comment by tannerlinsley** [comment]
Well... there you have it!

**Comment by tannerlinsley** [comment]
Happy to reopen or convert to a discussion for further... discussion!
