### ISSUE TITLE
infinite loop refetch when call window.alert inside request

### ISSUE THREAD

**Issue by SvyatoslavPozhydaev** [tannerlinsley/react-query#2868]
**Describe the bug**
Since `refetchOnWindowFocus` is set to true by default, then if you call window.alert inside a request or somewhere else, you get an infinite loop

**To Reproduce**
```
useQuery('key', () =>
  fetch('some url')
    .then(response => response.json())
    .catch(error => {
       alert(error);
    })
)
```

**Comment by McLovin77** [comment]
It makes sense that it created an infinite loop in your case, because what is happening is that:
1. Component mounts and useQuery called.
2. useQuery fires the queryFn (with refetchOnWindowFocus true by default).
2. queryFn calls window.alert, which causes blur on window (by blur I mean the opposite of focus 👀).
3. That blur (from step 2) is then dismissed when you click on the button on the alert prompt, which then causes another window focus (as in you are now focusing back on the screen and not on the alert prompt), and we go back to step 2.

What I suggest (And I'm sorry if it might sound too obvious to you) is not to use alerts in the queryFn, but in the onSuccess, onSettled or onMutate.

**Comment by TkDodo** [comment]
I agree with @McLovin77 , but I don't think that the situation would be better with the callbacks. Yes, generally, it is better to put side-effects like showing alerts there, however, with the default staleTime of 0, you would still get _another_ refetch because of the focus event.

You can:

1. turn off `refetchOnWindowFocus` to avoid the refetch altogether
1. set a higher `staleTime`, because only stale queries will be refetched
1. _not_ use `window.alert` but a toast library like [react-hot-toast](https://react-hot-toast.com/)
1. tweak the [FocusManager](https://react-query.tanstack.com/reference/focusManager) to your needs.

I would go with number 3 :)

**Comment by s-r-x** [comment]
facing the same issue. i have a little abstraction over useMutation, that relies on window.confirm. it looks something like this

```ts
onMutate() {                                                                                                                      
      if (args.confirm) {                                                                                         
        const confirmed = window.confirm("");
        if (!confirmed) throw new ConfirmError();
      }
    },
```
was able to fix it with these lines
```ts 
onMutate() {                                                                                                                      
      if (args.confirm) {
        focusManager.setFocused(false);                                                        
        const confirmed = window.confirm("");
        setTimeout(() => focusManager.setFocused(undefined));
        if (!confirmed) throw new ConfirmError();
      }
    },
```

hope it helps
