### ISSUE TITLE
useInfiniteQuery misses some response data when making few requests at the same time

### ISSUE THREAD

**Issue by faradaytrs** [tannerlinsley/react-query#2883]
**Describe the bug**
useInfiniteQuery misses some response data when making few requests at the same time
I use useInfiniteQuery hook for fetching data for virtual scrolling. 
When uses scrolls too fast, useQuery will dispatch the second request when the first request is not finished yet. 
After both requests are completed, one of the requests data is missing.

**To Reproduce**
1. Fetch pages with useInfiniteQuery's fetchNextPage({pageParam: page})
2. If your requests are slow enough it's very likely when you will encounter a situation when two requests are made in the same time.
3. After both requests are completed, check the resulting data.

**Expected behavior**
I expect both requests data to present in useQuery cache.

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: Microsoft Edge
 - Version: 95

**Comment by prateek3255** [comment]
@faradaytrs Can you also share a reproducible codesandbox to help demonstrate the issue?

**Comment by TkDodo** [comment]
`fetchNextPage`, per default, cancels any outgoing other refetches. You can change that by passing `cancelRefetch: false` to `fetchNextPage.

However, usually with infinite queries, you can't fetch more than one page because that's all there is in the ui. Consider:

- you have an infinite list, and you start by showing 20 items
- user scrolls to the bottom, you load 20 more
- right now, the user can't scroll further to the bottom, because they are already at the bottom
- only after the next 20 items are loaded, you can scroll further to the bottom to trigger _another_ refetch, but at that time, the previous fetch has already completed.

If your scenario deviates, as stated above, please provide a codesandbox reproduction.

**Comment by faradaytrs** [comment]
@TkDodo The issue indeed was cancelRefetch: false
About UI, we understand that, but in this page we wanted user ability to scroll to the page bottom directly. Maybe it was bad idea.
Thank you guys for your help.
