### ISSUE TITLE
retry doesn't stop during the internet is disconnected

### ISSUE THREAD

**Issue by buglessir** [tannerlinsley/react-query#2900]
I'm using version: `3.25.1`

Please consider this example:

```
const URL = 'https://randomuser.me/api/?results=5&inc=name';

const Example = () => {
  const { error, data, isLoading, refetch } = useQuery('test', () =>
    fetch(URL).then(response => response.json()), {
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
    retry: 1
  });

  if (isLoading) return <span>Loading...</span>

  if (error) return <span>Error: {error.message} <button onClick={refetch}>retry</button></span>

  return (
    <div>
      <ul>
        {
          data.results.map((item, key) => <li key={key}>{item.name.first} {item.name.last}</li>)
        }
      </ul>
      <button onClick={refetch}>Refetch</button>
    </div>
  )
}
```

After use the offline mode by DevTools > Network > Throttling, this component doesn't show the loading or even never stop fetching. It's expected to stop fetching and shows the error after once trying...

But after setting this config: `retry: false` code works correct and shows the error and retrying button.

**Comment by TkDodo** [comment]
retries are an internal mechanism, and currently, react-query stops retrying if you are offline. You can observe the `failureCount` returned by `useQuery` to see if a failure has been detected.

I'm seeing it more of an issue that calling `refetch` shouldn't even start fetching if you are currently offline. Right now, it starts the fetch, but then retries "pause" when offline. What it should most likely do is mark the query as `stale` so that it will be refetched once the user comes back online.

But any change in this regard would be a breaking change, so we'll have to discuss this for the next major version.

related:
- https://github.com/tannerlinsley/react-query/issues/2361
- https://github.com/tannerlinsley/react-query/issues/2179

**Comment by TkDodo** [comment]
we will be tracking this issue and related ones here from now on:
- https://github.com/tannerlinsley/react-query/issues/2927

The plan is to work on this for the next major version, because it will contain breaking changes. Your feedback would be appreciated.
