### ISSUE TITLE
integrate react-query-devtools in multi app

### ISSUE THREAD

**Issue by sirtakidancers** [tannerlinsley/react-query#2907]
**Describe the bug**
for an application with a micro-fronted approach, it is impossible to integrate devtools without duplication

**To Reproduce**
https://codesandbox.io/s/practical-carson-uybdb?file=/src/index.js

didn’t find implementation to combine several applications in one devtools, can you have a solution?

**Comment by sirtakidancers** [comment]
in real project code, react-query-provider can be in different git repositories

**Comment by TkDodo** [comment]
what would be the expected outcome here please? Since they all have different query caches, they can't be combined. Under the hood, the devtools just call `useQueryClient()` to get ahold of the data.

You can position them differently, or you can use the `ReactQueryDevtoolsPanel` to render it e.g. within your microfrontend.

**Comment by sirtakidancers** [comment]
After a little digging, I realized that ReactQueryDevtoolsPanel can be placed not necessarily in the root provider and it will output all requests from child and external providers on the page, this solves my problem :)
