### ISSUE TITLE
[React Native] Android back button

### ISSUE THREAD

**Issue by anatooly** [tannerlinsley/react-query#3041]
useQuery and all other hooks lost data after reinitialize application that close on Android hardware button back or swipe method for Samsung Galaxy. For iOS this problem too some time on dev mode when app refreshing.

1. Open app
2. const { data } = useQuery()
3. data return response object
4. Back button close app
5. Open app
6. const { data } = useQuery()
7. data return undefined

when exit app — unmount, after secondary start nothing help focusManager, refetch, useFocusEffect,... restart code
only hard force close app and new open. Background mode for app work fine.

**To Reproduce**
Open app for some first screen, fetch data
Hardware back button that close app
Open app
data fethching & response correct but const { data } = useQuery() return undefined and render all empty

**Screenshots**
![image](https://user-images.githubusercontent.com/317380/144229657-a742f2bf-b33b-49bb-936d-3a73d35f68e9.png)

**Smartphone (please complete the following information):**
Samsung Galaxy A30, 20e, Android emulator Nexus
iOS sumulator

Andorid 11 / ios 12

**Comment by TkDodo** [comment]
I would definitely need more information than that please, because I don't have ios simulator so I can't reproduce this.

what would help is if you'd show the states that the query is in in each step. not just the `data`, but also `status`, `error` etc. Also, what happens when you click close button in the react app? Is the component unmounting? Is it staying active in the background?
also, what kind of configs are you using? just the defaults / staleTime / cacheTime etc ...

**Comment by anatooly** [comment]
Sorry find problem on axios lib, that use for fethhing query
