### ISSUE TITLE
How to use useInfiniteQuery with custom props

### ISSUE THREAD

**Issue by sbogdaniuk** [tannerlinsley/react-query#307]
Let's picture situation where we have filters with infinite scroll data view.

So I have have code like this:
```javascript
// api
const queryPosts = async (props = {}) => {
  const { sort, page } = props
  const res = await axios.get(`/posts?sort=${sort}&page=${page}`)
  return {
    items: res.data,
    page,
  }
}

// Posts
const [sort, setSort] = React.useState('views')
const payload = useInfiniteQuery(
  ['infinite-posts', { sort, page: 1 }],
  queryPosts,
  {
    getFetchMore: lastGroup => {
      const { items, group } = lastGroup
      if (items.length) {
        return { page: page + 1, sort }
      }
      return false
    }
  }
)
```

At first it triggers correct, but when I call `() => fetchMore()` `sort` is disappeared, and page remains as initial.

Maybe I'm doing something wrong?

**Comment by AvraamMavridis** [comment]
Unfortunately I have the same issue, is not clear from the docs how to use it :(

**Comment by tannerlinsley** [comment]
The issue here is that you are not mapping up your query key to your query function's arguments properly. Each item in the query key is passed to the query function, including `infinite-posts` in your case. The next issue is that you're not accounting that the result from `getFetchMore` is passed as an *optional* parameter to your query function, which is why on the first request, you must provide a default value.

```js
async function queryPosts (key, sort, page = 1) {
  // key === 'infinite-posts'
  // sort will always be there from the query-key
  // page information won't be there on the first request
  // which is why is has a defualt value of 1, but it will be
  // there on subsequent requests
  const res = await axios.get(`/posts?sort=${sort}&page=${page}`)

  return {
    items: res.data,
    page,
  }
}

const queryInfo = useInfiniteQuery(['infinite-posts', sort], queryPosts, {
  getFetchMore: ({ items, page }) => {
    if (items.length) {
      return page + 1 // This will be sent as the LAST parameter to your query function
    }

    return false
  },
})
```

**Comment by AvraamMavridis** [comment]
@tannerlinsley what is the proper way to update the `sort` in your example? are the `queryPost` automatically updated when `sort` changes?

**Comment by tannerlinsley** [comment]
Yep! You can update it however you'd like (via state, props, etc). Since it's part of the query key, it will automatically trigger a new refetch when it changes.

**Comment by AvraamMavridis** [comment]
@tannerlinsley thx a lot for the help. I loved the lib, seems like the missing abstraction for the hooks + fetching.

**Comment by tannerlinsley** [comment]
:) You're welcome! Thanks for using it! You should consider writing a blog post on that thought. It sounds like a great prompt: "React Query: The missing abstraction for hooks and data fetching"

**Comment by sbogdaniuk** [comment]
@tannerlinsley thanks it works.

One more question:
Is there a possibility to change in `queryPosts (key, sort, page = 1)` second parameter via `fetchMore`?
As I can see `fetchMore` changing only third parameter

**Comment by tannerlinsley** [comment]
You would have to do that override in the query function itself and use an optional override sort if it's there from the fetchMore

**Comment by ralrom** [comment]
Hello, I think this could be better documented. I also had trouble using `useInfiniteQuery` with an additional parameter until I found this issue.

**Comment by qkreltms** [comment]
I absolute agree with @ralrom 's ideas

**Comment by rsarai** [comment]
For anyone facing a facet of this issue, the following worked for me:
```javascript
async function queryPosts (queryKey, pageParam = 1) {
  const sort = queryKey[1];  // queryKey[0] is the original query key 'infinite-posts'
  const res = await axios.get(`/posts?sort=${sort}&page=${pageParam}`)

  return {
    items: res.data,
    page,
  }
}

const queryInfo = useInfiniteQuery(['infinite-posts', sort], queryPosts, {
  getFetchMore: ({ items, page }) => {
    if (items.length) {
      return page + 1 // This will be sent as the LAST parameter to your query function
    }

    return false
  },
})
```

**Comment by Alecell** [comment]
@rsarai maybe this isn't a good way to to send the props to the service since it forces we to write the API request with some boilerplate args, breaking the re-usability of that service outside of `react-query` and as I see on the docs neither the [useInfiniteQuery](https://react-query.tanstack.com/reference/useInfiniteQuery) or [useQuery](https://react-query.tanstack.com/reference/useQuery) accepts `getFetchMore` method on react-query v3.

But as I found [here](https://github.com/tannerlinsley/react-query/issues/1644#issuecomment-761534757), on the migration guide have a [really useful doc](https://react-query.tanstack.com/guides/migrating-to-react-query-3#infinite-query-page-params-are-now-passed-via-queryfunctioncontextpageparam) about `useInfiniteQuery` args. 

Basically we just need to call the service through a function like this:
```js
// Old
 useInfiniteQuery(['posts'], (_key, pageParam = 0) => fetchPosts(pageParam))
 
 // New
 useInfiniteQuery(['posts'], ({ pageParam = 0 }) => fetchPosts(pageParam))
```

with this we can treat the `pageParams` isolated from the service and, sending an object to `fetchNextPage` we get the new props of the function, it becomes really useful if we create a custom hook as below. But is good to say, I have to work on a more readable way to write this, but at least IMO this is better than change the way we write our services here. 

```js
 const useMyRequest = (param1, param2) => {
  useInfiniteQuery(
    'posts', 
    ({ pageParam = 0 }) => {
      const obj = {
        param1: pageParams.param1 || param1,
        param2: pageParams.param2 || param2
      }
      
      fetchPosts(obj.param1, obj.param2)
    }
  )
}
```

BTW I don't know if this is a good practice on `react-query`, @tannerlinsley could you tell us if it is?

**Comment by rsarai** [comment]
hey @Alecell, greetings, noticed we share the same timezone. You are 100% correct about the `getFetchMore`, on my project I'm actually using `getNextPageParam` (:see_no_evil:). 

I was trying to go for [different types of query keys](https://react-query.tanstack.com/guides/query-keys#array-keys). I'm also new to `react-query` so I'm happy to hear other comments.

**Comment by mnadeem** [comment]
Following worked for me

````
export const getLookupDefsSorted = async ({queryKey, pageParam = 0}) => {
  const sortBy = queryKey[1];  // queryKey[0] is the original query key 'infiniteLookupDefs'
  const sortDirection = queryKey[2]; 
  const url = `${URL_LOOKUP_DEF}/?pageNumber=${pageParam}&pageSize=${LOOKUP_DEF_PAGE_SIZE}&sortBy=${encodeURIComponent(sortBy)}&sortDirection=${encodeURIComponent(sortDirection)}`;
  const res = await axios.get(url)
  return res.data
}

export const useInfiniteQueryLookupDefsSorted = (sortBy, sortDirection) => {
  return useInfiniteQuery([QUERY_NAME_LOOKUP_DEFS_INFINITE, sortBy, sortDirection], getLookupDefsSorted, {
      getNextPageParam: (lastPage, allPages) => lastPage.last ? null : lastPage.number + 1,
      staleTime: 5 * 60 * 1000, // 5 minutes
  });
}
````

**Comment by kasongoyo** [comment]
What worked for me

```
export const useGetProducts = (filters: GetProductsQueryParamsType) =>
  useInfiniteQuery({
    queryKey: productKeys.listStoreProducts(filters),
    queryFn: async ({ pageParam = 1 }) => getProducts({ ...filters, page: pageParam }),
    getNextPageParam: (lastPage) => {
      const newPage = lastPage.page + 1
      const numPages = Math.ceil(lastPage.total / lastPage.take)
      if (newPage <= numPages) {
        return newPage
      } else {
        return lastPage.page
      }
    }
  });
```

Request

```
export async function getProducts({page, ...otherParams}) {
  return axiosInstance
    .get(`/products`, { params: {page, ...otherParams} })
    .then(normalizeResponse)
    .catch(normalizeError);
}
```
