### ISSUE TITLE
Type checking the idle status is required but it can't be there

### ISSUE THREAD

**Issue by Istanful** [tannerlinsley/react-query#3079]
**Describe the bug**
When using `useQuery` with `enabled: true`, typescript forces me to check for the idle status even though it will never be returned.

**To Reproduce**
1. Utilise the `useQuery` hook to perform any query. Omit the `enabled` option.
2. Guard for the `loading` and `error` statuses.
3. Below the guards, access a field on the data property.
4. TypeScript will not compile.

**Expected behavior**
Since the enabled flag is defaulted to true, the result should be considered "hot", and the idle status should not be considered possible.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 95.0b12 (64-bit)

**Additional context**
I believe the problem can be fixed by having a discriminated union type based on if the `enabled` option is passed or not. Of course this would require some complex typing, some refactoring and maybe some breaking changes.

**Comment by TkDodo** [comment]
While this might be true in the majority of cases, it is technically not true, e.g. in the following scenario:

- you mount your enabled query, it goes to `loading` state
- you `cancel` the query via `queryClient.cancelQueries` before it finishes loading (e.g. by performing a mutation that does an optimistic update)
- this query cancellation will reset the query to its previous state, which in the case of a hard loading state would be the `idle` state.

also, a discriminated union based on props we pass in is very hard to implement. There are many ways to set query options, starting from the global settings (`defaultOptions`) over per-key settings (`queryClient.setQueryDefaults`) to per-observer options that you are describing.

with suspense, you can't be in loading state. With initialData, you _really_ can't be in idle state (I think). All of this gets complicated very fast, and we already have 4 generics on useQuery.

The best way is imo actually to _not_ exhaustively match on status, but to just do:

```
const { data, error } = useQuery(..)

if (data) renderTheData
if (error) renderTheError

renderTheLoadingSpinner
```

this will of course also show data in case of background errors, so you have to compromise on what you want to render first. relevant read: https://tkdodo.eu/blog/status-checks-in-react-query

**Comment by Istanful** [comment]
Thank you for the explanation! I agree that it might not be feasible then. Checking for data first is probably a better solution, as that is what I'm looking for anyways.

It is nice to have all these features of react-query, but I do think it would be nice if one could utilise a smaller subset of the features - and thus this "correct" typing. Have you thought about exposing a simpler method? One that only has these three states for example?

Anyhow. Feel free to close the issue. 😄

**Comment by TkDodo** [comment]
The main use-case for `idle` is disabled queries (via the `enabled` option). Without it, you have no way of calling `useQuery` and defer the data fetching. I don't think that would be usable.

I have thought about _removing_ the `idle` state altogether, and it would be possible in v4, as we have a new `fetchingStatus`, which is a sub-state. But it would mean that disabled queries would go to `state: loading`, `fetchStatus: idle` (instead of `state: idle`, `fetchStatus: idle`) and I think this would be very breaking, as many people would then show a loading spinner.

**Comment by Istanful** [comment]
I think that could be a nice route to go, but very breaking for sure. I don't know the extent of people using the idle status, but I'd guess the majority does not. Having it be opt-in through the fetchStatus seems like a good compromise. At least at first glance.

**Comment by TkDodo** [comment]
@Istanful Yes, we _might_ even go that route - will discuss with others some more :) For example, if you are offline and a new query mounts, with v4 (unless you change the network mode), you will be in `state: loading, fetchStatus: paused`, so yeah, you can't really rely on "state" alone anyhow. And this change would kind of fit in here as well. will think some more 🤔

**Comment by Istanful** [comment]
Yeah that is a shame. :/ I feel like it would quite convenient to be able to rely solely on `state`. Especially since you can't do `result.data` in typescript without first checking the status. If the `state` can not single handedly tell me if `data` is there or not, I would have to create some custom type guards instead.

In my mind the scenario you are describing above is actually loading. Why would the `fetchStatus` be paused in that instance?

A complex problem to solve no doubt. 😅

**Comment by TkDodo** [comment]
>  I feel like it would quite convenient to be able to rely solely on state

This goes a bit against your previous idea to have the state be ideally only loading / success / error, which doesn't cover all the possible cases by far :)

> Why would the fetchStatus be paused in that instance?

In v4, we introduced a new network mode, which defaults to `online`, which means you need internet connection to fire off the query.
If you start a new query and we detect that you are offline, we are instantly pausing (not firing off the fetch), whereas in v3, we fired off the request and only paused retries.
This was troublesome because a) without retries, you would go to error state (not wanted) and b) with retries, users wouldn't really know that the query is paused because `isFetching` was always `true` and it seemed like an infinite fetching.

With the new solution (status: loading, fetchStatus: paused), you have the option to still display the spinner, or to tell the user that the query is paused because you are offline.

**Comment by TkDodo** [comment]
> If the state can not single handedly tell me if data is there or not

That would still be the case. In loading state, you never have data, in success state, you always have data. In error state, you might have stale data (if you were successful once before) or no data (if it errored immediately)

**Comment by Istanful** [comment]
> This goes a bit against your previous idea to have the state be ideally only loading / success / error, which doesn't cover all the possible cases by far :)
Haha you're right! :P Addendum: I would also like fewer statuses where possible. xD

> With the new solution (status: loading, fetchStatus: paused), you have the option to still display the spinner, or to tell the user that the query is paused because you are offline.

Ah ok. Then I understand. :)

> That would still be the case. In loading state, you never have data, in success state, you always have data. In error state, you might have stale data (if you were successful once before) or no data (if it errored immediately)

Ok. That's great :)
