### ISSUE TITLE
react-query status in react-native

### ISSUE THREAD

**Issue by nawfalhaddi** [tannerlinsley/react-query#3126]
### Describe the bug

I have created a new react native project and I have added react-query-native-devtools plugin on flipper to see what's going on, and I notice the following behaviors:  

- all data stays fresh and it never goes to stale status.
- data state  doesn't change to an inactive state when I change the screen 
- if the URL is changed and you save it, it causes a rerender for the screen but the data doesn't update.

### Your Example Website or App

https://github.com/nawfalhaddi/react-query-fetching-issue

### Steps to reproduce

1. Go to home page
2. Navigate to any other page 
3. Check the status of queries

### Expected behavior

As a user, I expect the following:

- my data should go to stale once it's loaded.
- Whenever I leave the screen it should go to inactive status.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/38982483/147203440-ec4d152c-d68b-401d-b59f-745538b6a32a.png)

### Platform

- OS: [iOS, Android]
- Browser: [React Native]
- Version: [0.66.4]

### Additional context

I think when we use react-navigation and we move to another screen react query doesn't detect that the previous page was unmounted.

**Comment by TkDodo** [comment]
please provide instructions on how to start this reproduction in a way that someone who has never done anything with react-native can do that (which would be true for me, no clue what to do after cloning the repo).

From what I can tell in the source code:

- You are [creating](https://github.com/nawfalhaddi/react-query-fetching-issue/blob/243eb09eb590c630a455a5e646d95b28bdb4f702/App.tsx#L11) the `new QueryClient` _inside_ the `App`, which will give you a new QueryClient + new Cache whenever `App` re-renders. This might not be a problem, but it might also be one. Please move it _out_ of the App, like in the official examples.
-  > I think when we use react-navigation and we move to another screen react query doesn't detect that the previous page was unmounted.
That seems true, because with react-navigation, the old screen doesn't really unmount - it just gets visually hidden. Looking at the [react-navigation docs](https://reactnavigation.org/docs/navigation-lifecycle/), when you navigate from one component to the other, it doesn't unmount. React Query relies on effects and subscriptions to cleanup. Basically, if you visually hide something, but it stays mounted in the App, react-query treats it as visible. The react-navigation docs have an example on how to listen to the focus event. I think you can also just use the `enabled` option to disable a query depending on the state returned from the [useIsFocused hook](https://reactnavigation.org/docs/use-is-focused).
- for refetching on window focus, follow the [guides in the react-query docs](https://react-query.tanstack.com/react-native#refetch-on-app-focus).
- > if the URL is changed and you save it, it causes a rerender for the screen but the data doesn't update.
not sure exactly what that means. Since your [queryKey is static](https://github.com/nawfalhaddi/react-query-fetching-issue/blob/243eb09eb590c630a455a5e646d95b28bdb4f702/src/components/Home.tsx#L12-L19) (`['Homepage']`), there won't be any refetches when arguments change. if your fetch has dependencies and you expect refetches when one of those dependencies changes, you need to put those _into_ the query key.

**Comment by nawfalhaddi** [comment]
Instructions to reproduce: 
1- Setup the environment for react-native  following official doc: https://reactnative.dev/docs/environment-setup
2- Download and install Flipper: https://fbflipper.com/
3- Inside flipper add new plugin : flipper-plugin-react-query-native-devtools
4- in the project, open the terminal and run the following command: 
     ```yarn install && cd ios && pod install --repo-update && cd .. ```
5- then to start the project run: ```yarn ios
6- Go to home page
7- Navigate to any other page
8- Check the status of queries

**Comment by TkDodo** [comment]
sorry, this isn't working for me (at all).

1. I did `npm install -g expo-cli`, but then what? Instructions are for creating a new repo ...
2. downloaded flipper, cannot open it:
> "Flipper” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.
3. cannot do because of 2.
4. `pod` command doesn't exist. some googling showed I need to `brew install cocoapods`. Oh well, this took some time...
5. did that, an ios simulator opens and stays open, but the terminal command errors with:

> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MyApp.xcworkspace.

lots of things on the console then, followed by:

> ** BUILD FAILED **
The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/[...]/Library/Developer/Xcode/DerivedData/MyApp-abuavhwijqdlwzdcuayurvelxffj/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-C8AC78B0264D0F9F6F6D630E.sh
(1 failure)

---

sorry to say that this is not a good way to reproduce anything. Is there no better way like a codesandbox for react-native? What about something like https://snack.expo.dev/ ?

**Comment by arnaudbzn** [comment]
@nawfalhaddi Not sure if it's your issue but to refetch a query on screen focus with React Navigation I use this hook:
https://react-query.tanstack.com/react-native#refresh-on-screen-focus

**Comment by nawfalhaddi** [comment]
@arnaudbzn  I found a better approach for my case as @TkDodo  suggested to me, I have added useIsFocused from react-navigation to enable the query whenever we focus on the screen and it gets disabled whenever we leave it :
here is an example: 

`
import { useIsFocused } from '@react-navigation/native';

const isFocused = useIsFocused();

const {
              data,
	      isError,
              isLoading,
	      refetch,
	} = useQuery('addresses' ,{ enabled: isFocused });
`

**Comment by nawfalhaddi** [comment]
@TkDodo I really appreciate your efforts, I know when it comes to react-native it requires some time to settle the environment. 
unfortunately,  https://snack.expo.dev/  doesn't have debugging tools to show query status. 
I closed this issue since we can control the query status manually using  ```useIsFocused ``` from react-navigation as mentioned above.
