### ISSUE TITLE
NextJS, queryClient.prefetchInfiniteQuery - getNextPageParam() doesnt set the pageParams

### ISSUE THREAD

**Issue by lotusjohn** [tannerlinsley/react-query#3149]
### Describe the bug

Either im missing something or it doesnt work to use getNextPageParam() when using prefetchInfiniteQuery in NextJs getServerSideProps. I've read about some upstream issues with Next and undefined values trying to be serialised but 
I expected getNextPageParam to set the pageParam value, and not be undefined.
It does get set when i setQueryData() afterwards. 

```
export async function getServerSideProps() {
  const queryClient = new QueryClient();
  await Promise.all([
    queryClient.**prefetchInfiniteQuery**('key', fetchFn, {
      **getNextPageParam: (lastPage, pages) => lastPage.pagingMetadata**,
    }),
    queryClient.prefetchQuery('key2', fetchFn2, {
    }),
  ]);

  //https://github.com/tannerlinsley/react-query/issues/1528

  console.log("##1 ", _dehydrate.queries[0].state.data.pageParams[0]);

  queryClient.setQueryData(API_QUERY_KEY_FEED, (oldData) => ({
    ...oldData,
    pageParams: [oldData.pages[0].pagingMetadata],
  }));

  console.log("##2 ", _dehydrate.queries[0].state.data.pageParams[0]);

  return {
    props: {
      dehydratedState:  dehydrate(queryClient),
    },
  };
}

```

Logs:
```
##1  undefined
##2  { start: 10, offset: 20 }
```

### Your Example Website or App

na

### Steps to reproduce

Create a next app with react query and use queryClient.prefetchInfiniteQuery() in getServerSideProps() and pass in getNextPageParam in the options. 
Check if theres any value in the pageParams key. 

### Expected behavior

Expect both console.logs to contain the value:
```
##1  { start: 10, offset: 20 }
##2  { start: 10, offset: 20 }
```
instead of the first log being undefined. 

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/33894408/147693206-52c71087-4ced-43a3-b427-7028f20c757c.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: Version 96.0.4664.110 (Official Build) (x86_64)

NextJS 12.0.7
React query: 3.34.7

**Comment by TkDodo** [comment]
It is indeed expected that for the first page, the next page params are `undefined`, because they are usually derived from the _previous_ page - which doesn't exist for the first page.

You can see that in the [load more / infinite scroll example](https://react-query.tanstack.com/examples/load-more-infinite-scroll): Inspect the `pageParams` of the first page in the devtools to see that it is undefined.

`{ start: 10, offset: 20 }` would be the nextPageParams for the _second_ page.

I don't think that we can or should make sure that we never have `undefined` values anywhere, and as #1528 states, this seems to be a next.js issue.There is a long discussion over at next.js about whether undefined should be included or not: https://github.com/vercel/next.js/discussions/11209 and it also shows some workarounds (like stringify+serialize)

**Comment by lotusjohn** [comment]
Ah right, thanks for the explanation and pointing in the right direction. 
My mistake was thinking that the last entry in the pageParams[] was what was used when `fetchNextPage`.

**Comment by cross-development** [comment]
Hi! Today I had the same problem with the `useInfiniteQuery` in Next.js SSR. In my case, I used this option - `structuralSharing`. If you pass a function to this prop you can get old and new values. Log the new and old values and you can see why you have `undefined`. So, to solve this problem you should return from this function an object with the next fields:
`{ pageParams: [null], pages: newData.pages }` (or in case you want to pass a page number, instead of null you should put [1] like a first page). The `pageParams` field allows you to pass the first param which doesn't exist on the first request. And newData.pages allows you to keep your infinite scroll working on the client side. 
By the way, if you have a "Show more" button, after getting more data (page 2) you will have the next pageParams: `{ pageParams: [null, 1], pages: newData.pages }` (or `{ pageParams: [1, 2], pages: newData.pages }` in case you passed 1 like the number of the first page).
I hope the solution to this problem will not cause errors in further development))))

**Comment by TkDodo** [comment]
fyi, this will be fixed in v5:

- https://github.com/TanStack/query/discussions/4854
