### ISSUE TITLE
Enabled option not respected for useInfiniteQuery

### ISSUE THREAD

**Issue by patsantos** [tannerlinsley/react-query#3166]
### Describe the bug

The `enabled` option for [`useInfiniteQuery`](https://react-query.tanstack.com/reference/useInfiniteQuery) is not respected. When setting it to `false` the query still executes. This is necessary for [dependent queries](https://react-query.tanstack.com/guides/dependent-queries) where the `useInfiniteQuery` instance must be called after another query resolves.

### Your minimal, reproducible example

https://codesandbox.io/s/useinfinitequeryenabled-m576l?file=/pages/index.js

### Steps to reproduce

1. Duplicated the codesandbox example for `useInfiniteQuery`
2. Added line 47 `enabled: false,`
3. Query still executes

### Expected behavior

As the [documentation says](https://react-query.tanstack.com/reference/useInfiniteQuery) the "options for useInfiniteQuery are identical to the useQuery hook" which `useQuery` has the `enabled` option that should work for `useInfiniteQuery` as well.

### How often does this bug happen?

Every time

### Platform

- macOS 11.6.2
- Chrome Version 97.0.4692.71 (Official Build) (x86_64)
- Safari Version 15.2

### react-query version

3.34.7

**Comment by ryb73** [comment]
I seem to be running into this problem — did you find a fix? Was it fixed in a more recent version of react-query?

**Comment by TkDodo** [comment]
@ryb73 please provide a new sandbox, the one in this issue doesn't seem to work anymore. `enabled` generally works the same for infinite query and normal queries. They are both based on `useBaseQuery`, and the part that handles `enabled` is the same code for both ....

**Comment by ryb73** [comment]
I can't be sure because I was only encountering the issue when in an intermediate development state and am not affected by it anymore, but I think my problem was that I was accidentally calling `fetchNextPage`, which seems to invoke the query even when `enabled` = `false`. So while it kind of doesn't make sense to ignore the `enabled` flag, it also doesn't really seem like a big issue to me, since developers shouldn't really be calling `fetch` if they don't want to immediately fetch.
