### ISSUE TITLE
`fetchNextPage`'s `pageParam` is ignored on the first request

### ISSUE THREAD

**Issue by RomanKornev** [tannerlinsley/react-query#3170]
### Describe the bug

Calling `fetchNextPage({ pageParam: 50 })` will not fetch a manually specified page on the first request, if the first request failed or after clearing using `remove()`. It will still fetch the default page from `useInfiniteQuery`.
Either the documentation needs to be updated (currently, it states "`pageParam` allows you to manually specify a page param instead of using `getNextPageParam`") or this issue needs to be fixed.

### Your minimal, reproducible example

https://codesandbox.io/s/jovial-leaf-8tob8?file=/src/index.js

### Steps to reproduce

1. https://codesandbox.io/s/jovial-leaf-8tob8?file=/src/index.js
2. Open Network
3. `useInfiniteQuery` is trying to get page 1 as it should
4. Click the button to jump to page 50
5. `useInfiniteQuery` is still trying to get page 1 even though `pageParam` was manually set to 50

### Expected behavior

As a user, I expected to manually set a `pageParam` in all cases but I'm seeing inconsistent behaviour.

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Version: 96

### react-query version

v3.34.7

### TypeScript version

v4.5.4

**Comment by TkDodo** [comment]
Judging from the code, I think this is the intended behaviour. You can only fetch "more" once you have fetched the first page. We _could_ change this I believe, but what would be the expected behaviour? Should the page with `param: 50` then become the first page? Also, what should happen if you call `fetchNextPage()` without a manual pageParam while the query is in error state? we would need to invoke `getNextPageParam`, which expects a previous page to be passed, which we don't have :/

all in all, I don't think it is "meant" to do `fetchNextPage` while you are in error state. Please feel free to update the docs to reflect that better

**Comment by RomanKornev** [comment]
So what is the intended way to change the "first" page? For example, if a user has scrolled away from the start and we need to refetch only part of the pages, starting from a different point.

**Comment by TkDodo** [comment]
not sure I understand that question. to `refetch` only specific pages, you can pass `refetchPage` to `refetch`:

```
const { refetch } = useInfiniteQuery(...)

refetch({
  refetchPage: (lastPage, index, allPages) => index === 0
})
```

this would only refetch the first page for example.

**Comment by TkDodo** [comment]
any more questions here, or can we close the issue please?

**Comment by RomanKornev** [comment]
Sure, thanks!
