### ISSUE TITLE
queryFn is called twice in Suspense mode

### ISSUE THREAD

**Issue by simoncarpinter** [tannerlinsley/react-query#324]
Per the title, when using `useQuery` with `{ suspense: true }`, the supplied query function will be called twice.

See https://github.com/simoncarpinter/react-query/commit/cc09457c85946c8097334e516ecdd5f35a0a8801 for details, opening a PR now that adds the test.  I haven't yet spotted the actual bug.

**Comment by simoncarpinter** [comment]
It appears to be somewhere in `query.fetch`, maybe?  `handleSuspense` in `useQuery.js` calls `query.refetch`, which calls `query.fetch`, which -- if I'm reading things right -- *should* return the existing promise, and only start a new one if there's nothing preexisting:

```
// Create a new promise for the query cache if necessary
      if (!query.promise) {
        query.promise = (async () => {
```

And yet, if I debug/`console.log` (lazy), `query.promise` is undefined in the initial request (expected) but is *still* undefined in the second request (unexpected) -- despite the fact that debugging *afterwards* shows `query.promise` is set in both cases.

Possibly a race condition?  Or possibly the `query` instance is changing, despite the fact it shouldn't be...

**Comment by simoncarpinter** [comment]
Ah.  Removing `delete query.promise` resolves the issue, but presumably will re-open #216, which is what that line closed.

**Comment by tannerlinsley** [comment]
This is indeed a funky issue. Still thinking here... keep up the info, it's helping.

**Comment by pjshu** [comment]
same problem😂

**Comment by ofer-h** [comment]
Hey @tannerlinsley 
Seems like there is a known issue around this topic as  useState / useMemo ... , are not behaving as expected while inside a suspend comp as it may initializer multiple times.

As I'm not 100% sure this is the same case here I will just share here the issues I refer to  

[useMemo gets called twice with Suspense](https://github.com/facebook/react/issues/14413)
[useState initializer called multiple times with suspense](https://github.com/FormidableLabs/react-ssr-prepass/issues/4
)

**Comment by ofer-h** [comment]
So, I was able to reproduce this thanks to @simoncarpinter fork and the cuse was this line:

https://github.com/tannerlinsley/react-query/blob/8a6ec246deaef9f4a0c1b32298874e3e74dc93c5/src/utils.js#L134
![react-query_utils_js_at_8a6ec246deaef9f4a0c1b32298874e3e74dc93c5_·_tannerlinsley_react-query_·_GitHub](https://user-images.githubusercontent.com/51446758/79624200-d9bdf000-8128-11ea-8528-2cbc5b3721dc.png)

As I'm a bit new to react and js in general, I'm not sure why we throw this Promise in general?

Related open issue - React:
[Triggering suspense with rejected promise causes re-render instead of error boundary](https://github.com/facebook/react/issues/17526).

**Comment by lindskogen** [comment]
I found this answer by Dan the Man, on another github issue that seems to suggest a recommended solution https://github.com/facebook/react/issues/14490#issuecomment-454973512

**Comment by simoncarpinter** [comment]
@ofer-h we need to throw the promise because that's how `Suspense` works :).  If a promise is thrown by a child react component, a parent `Suspense` will catch it and deal with it.

From what I can tell from reading the code, what *should* be happening is that we start fetching (great) and then throw the promise that `refetch` generates -- but what that *should* throw is the original promise, because `refetch` should have that cached and simply toss that upstream.  Instead, it appears that a reference is lost somehow and that we throw a new promise.

From my understanding of those linked tickets, the `useX` stuff getting called twice in `Suspense` mode is interesting... but it doesn't seem to be the root cause here.  I suspect that if we were affected by that design, we should actually see this happen 4 times (maybe? not entirely sure).

@lindskogen that could be useful -- using a ref for storing the `promise` might be the right thing to do.  Good find, if @tannerlinsley doesn't beat me to it, I'll try and hack up a proof-of-concept with that this afternoon.

**Comment by simoncarpinter** [comment]
Legend, thanks Tanner :).  I tried the refs but didn't get very far.

**Comment by Grimones** [comment]
Hi all
Seems to be https://github.com/tannerlinsley/react-query/commit/7d786c7631d75d4cc30d744b4f0fd3c4b67e4c6a created a regression with not deactivating instances in suspense mode

Please check the [codesandbox](https://codesandbox.io/s/xenodochial-tdd-wj0q6?file=/src/index.js)

As you can see with 1.3.0 it creates 2 instance of query. And when you unmount component they are still active. In my project only 1 gets deactivated and the other one stays active, but I was not able to reproduce it here. It creates problem for me because that query is not cached and it should be removed as soon as it gets inactive but it doesn't happen.

If you change react-query to 1.2.9 version the issue is not reproducible. And also you can see in console that query function was called only once. May be it's something wrong with test https://github.com/simoncarpinter/react-query/commit/cc09457c85946c8097334e516ecdd5f35a0a8801
