### ISSUE TITLE
Force re-render after setQueryData call?

### ISSUE THREAD

**Issue by robinvdvleuten** [tannerlinsley/react-query#326]
Whenever I call `setQueryData` directly, nothing re-renders or reflects the cache change. Could it be possible to call `setQueryData` outside of any hook to trigger re-renders where the query key is used?

**Comment by tannerlinsley** [comment]
Feel free to reopen with a reproduction. Thanks!

**Comment by robinvdvleuten** [comment]
@tannerlinsley hmm you are absolutely right! I cannot reproduce it in a small example (https://codesandbox.io/s/confident-glitter-cnqoz)

**Comment by robinvdvleuten** [comment]
OK it seems that I was using an incorrect cache key 🙄

**Comment by TkDodo** [comment]
> I'm facing the same issue. it returns updated data on const updatedData = queryClient.setQueryData but nothing re-renders on the screen. I'm forced to do queryClient.invalidateQueries(); to make it re-render.

then please reproduce it in codesandbox, because it seems like a different problem. `setQueryData` does update the cache, and observers should re-render accordingly.

**Comment by swport** [comment]
@TkDodo it's actually in the middle of a project. i'll try my best to make a codesandbox, to reproduce this issue, as quickly as i can.

**Comment by juxnpxblo** [comment]
for anyone else facing this same issue, if you're using the previous value to calculate the new one, make sure you're not mutating the previous value directly (cause it's wrong) and make sure you're returning a new reference, otherwise observers won't be notified about the changes (this was the reason my code wasn't working)

this won't trigger rerender:

queryClient.setQueryData(['queryKey'], (previousValue) => {
  previousValue = 'newValue';
  return previousValue;
});

**Comment by TkDodo** [comment]
@juxnpxblo do you think we should highlight this somewhere in the docs? I mean it's equivalent to handling `state` in react so I'm not sure why it would be surprising that this _doesn't_  work 🤔

**Comment by juxnpxblo** [comment]
@TkDodo well, looking back now from that perspective - that this is just regular react state management - it seems obvious but I guess for me (and maybe other less experienced devs out there) at that time that was not so clear
so I think yes it'd be good to have this highlighted somewhere in this specific api docs (I mean why not?)

**Comment by runticle** [comment]
I'm having a similar problem. Updating the cache with setQueriesData doesn't seem to notify the component using the data unless the mutation function is declared inside that component..?

Is this expected behaviour, and if so what is best practise for triggering the render? I am trying to move away from using invalidateQuery, and I'd rather not relocate the mutation function and prop drill unless I really have to...

**Comment by TkDodo** [comment]
@runticle not sure what you mean, please show a reproduction

**Comment by runticle** [comment]
ah I apologise, my issue is actually because my query update merely reorders an array.

https://github.com/TanStack/query/issues/5829 

disabling structuralSharing fixes it but I don't really want to do that.. 

Right now I have essentially  
```
const new = [...old]
*sort new*
return new 
```


I originally thought it was related to this guy 
https://stackoverflow.com/a/74114874/21941104

**Comment by runticle** [comment]
Forgive me but isn't this immutable?

```
(oldData) => {
    const newData = { ...oldData }; // Make a shallow copy of oldData

    for (const page of newData.pages) {
        for (const chat of page.chats.nodes) {
            if (chat.id === pushNotification.toId) {
                // Move the chat to the top of the list
                const index = page.chats.nodes.indexOf(chat);
                if (index !== -1) {
                    page.chats.nodes.splice(index, 1);
                    page.chats.nodes.unshift({ ...chat }); // Create a shallow copy of chat
                }

                return newData; // Return the updated data
            }
        }
    }

    return newData; // Return the original data if no changes were made
}

**Comment by TkDodo** [comment]
no, how is this immutable? `{ ...oldData }` makes a shallow copy, but `newData.pages.chats.nodes` still references the same objects / arrays as `oldData`, so when you call mutating methods on them like `splice`, it will also change `oldData`, thus our comparison algo won't see a difference.

If you like to work with splice and unshift, have a look at `immer`.

**Comment by runticle** [comment]
TIL! Thanks I had no idea `{...xyz}` doesn't deep copy nested objects 🤯 

Will use immer :D Have a good weekend!

**Comment by ic-768** [comment]
> no, how is this immutable? `{ ...oldData }` makes a shallow copy, but `newData.pages.chats.nodes` still references the same objects / arrays as `oldData`, so when you call mutating methods on them like `splice`, it will also change `oldData`, thus our comparison algo won't see a difference.
> 
> If you like to work with splice and unshift, have a look at `immer`.

I had this same issue. I didn't realize that `{...oldData}` would cause issues for nested objects. Using immer fixed it.

**Comment by braden-w** [comment]
The fix for me was passing in an updater function to `setQueryData`, not just the raw state. For some reason, I forgot `setQueryData` has the same updater type as `setState` and was passing in the value `{ ... todo, newProperty: true }` instead of `(todo) => ({ ... todo, newProperty: true })` as is best practice.

So not:

```typescript
// todo represents old state in component lifecycle, likely fetched from useQuery
queryClient.setQueryData(['todo', 1], { ... todo, newProperty: true });
```

but

```typescript
queryClient.setQueryData(['todo', 1], (todo) => ({ ... todo, newProperty: true }));
```

In my case, my code had this buried under a layer of helper functions so it was harder to identify at first, but this was the ultimate fix.

**Comment by okinawaa** [comment]
Thanks for knowing me!
