### ISSUE TITLE
Using useInfiniteQuery with server side rendering Next.Js

### ISSUE THREAD

**Issue by igdev116** [tannerlinsley/react-query#3301]
### Describe the bug

I'm using `useInfiniteQuery` with server side rendering Nextjs but when I view page source it doesn't have any content. If I use `useQuery` it's work perfectly

### Steps to reproduce

My code on server side
```js
export const getServerSideProps = () => {
       // ...
      await queryClient.prefetchQuery('products', getProducts);

      return {
            props: {
                  dehydratedState: dehydrate(queryClient),
            },
      };
}
```
If I use `useQuery`, my content has been rendered on the server side then client can get products to display, it's good for SEO
```js
const { data } = useQuery<GetProductsQuery>('products', getProducts); // It's worked!
```
But if I use `useInfiniteQuery`, my content only rendered until the client sends a request to the server to fetch products
```js
const { data, hasNextPage, fetchNextPage } =
      useInfiniteQuery<GetProductsQuery>('products', 
            ({ pageParam = 1 }) => getProducts(pageParam),
            {
                  getNextPageParam: (lastPage) => {
                        return lastPage.nextPage ?? undefined;
                  },
            }
    );
```

### Expected behavior

I think `useInfiniteQuery` doesn't support server side rendering yet 🤔
I don't have no idea to create infinite scrolling with `useQuery`, I hope to see an example repo with it 😅
Thanks for all answers 🍻

### Platform

Browser: Chrome
Windows: 11

### react-query version

 3.34.14

**Comment by TkDodo** [comment]
Please create a codesandbox reproduction.

- you need to use `prefetchInfiniteQuery` instead of `prefetchQuery`
- there is a known nextJs limitation that it cannot serialize `undefined`, which has been reported multiple times
  - https://github.com/tannerlinsley/react-query/issues/1458#issuecomment-1022396964
  - https://github.com/tannerlinsley/react-query/issues/3149
  - https://github.com/tannerlinsley/react-query/issues/1528
  - https://github.com/tannerlinsley/react-query/discussions/3120

**Comment by cross-development** [comment]
Hi! Today I had the same problem with the `useInfiniteQuery` in Next.js SSR. In my case, I used this option - `structuralSharing`. If you pass a function to this prop you can get old and new values. Log the new and old values and you can see why you have `undefined`. So, to solve this problem you should return from this function an object with the next fields:
`{ pageParams: [null], pages: newData.pages }` (or in case you want to pass a page number, instead of null you should put [1] like a first page). The `pageParams` field allows you to pass the first param which doesn't exist on the first request. And newData.pages allows you to keep your infinite scroll working on the client side. 
By the way, if you have a "Show more" button, after getting more data (page 2) you will have the next pageParams: `{ pageParams: [null, 1], pages: newData.pages }` (or `{ pageParams: [1, 2], pages: newData.pages }` in case you passed 1 like the number of the first page).
I hope the solution to this problem will not cause errors in further development))))
