### ISSUE TITLE
React Query V4 Alpha 19 Loading State is True when enabled false

### ISSUE THREAD

**Issue by danbunkr** [tannerlinsley/react-query#3374]
### Describe the bug

When setting the enabled flag to `false` in ReactQuery v4 alpha 19 the query still goes into the loading state.

### Your minimal, reproducible example

https://codesandbox.io/s/intelligent-cray-4gbrg8?file=/src/index.js

### Steps to reproduce

1.) Set React Query NPM version to  "react-query": "v4.0.0-alpha.19"
2.) Set enabled to false on the query
3.) Observe that query goes into loading state still with enabled false.

### Expected behavior

Query should not be loading or execute when enabled false.

### How often does this bug happen?

100% of the time on each render.

### Screenshots or Videos

N/A see Code Sandbox link for reproduction

### Platform

MacOS, Windows
Chrome, Safari, & Firefox

### react-query version

    "react-query": "v4.0.0-alpha.19",

### TypeScript version

N/a: Applies to root level JS

**Comment by TkDodo** [comment]
It goes to loading state because the idle state does not exist anymore. The new fetchStatus will be idle though. See:
- https://react-query-alpha.tanstack.com/guides/queries#fetchstatus
- https://react-query-alpha.tanstack.com/guides/disabling-queries

but I forgot to update the migration guide with this breaking change 🙈. If you want, you can open a PR to the v4 docs?
