### ISSUE TITLE
useInfiniteQuery makes 2 API calls instead of 1

### ISSUE THREAD

**Issue by marija-advania** [tannerlinsley/react-query#3380]
### Describe the bug

useInfiniteQuery makes 2 API calls instead of 1, when using React version 18+

### Your minimal, reproducible example

https://codesandbox.io/s/affectionate-poitras-il78q2

### Steps to reproduce

Look at the network tab or console.

### Expected behavior

It should initially make one API call.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="516" alt="Screenshot 2022-03-10 at 16 49 33" src="https://user-images.githubusercontent.com/98086735/157699579-8ec825eb-78e0-41e5-9d46-e930844c6be4.png">

### Platform

macOS (version 12.1)

### react-query version

3.34.16 (latest)

### TypeScript version

4.4.2

**Comment by TkDodo** [comment]
In strict mode, react fires all effects twice in development mode in react18. This is known as strict effects:
https://github.com/reactwg/react-18/discussions/19

**Comment by jtomaszewski** [comment]
In my case the reason was not react18 (or lack of strictmode), but the fact that I had a function memoized and then debounced using `useMemo` `useDebounced`, which would hold a stale reference to a function that had referenced `isFetchingNextPage` property. After fixing up the function memoizations, I no longer had two requests being sent by react-query.
