### ISSUE TITLE
Clarifications about `useMutation`

### ISSUE THREAD

**Issue by n1ghtmare** [tannerlinsley/react-query#344]
I was hoping someone could clarify something for me. I'm not entirely sure what is the point of `useMutation`, I'm sure I'm missing something.

Is there any difference between the 3 versions below as far as react-query is concerned?  

*v1*
```js
const [mutate] = useMutation(addTodo, {
  onSuccess: () => {
    queryCache.refetchQueries('todos');
    queryCache.refetchQueries('reminders');
  },
});

await mutate(todo);
```

and *v2*
```js
const [mutate] = useMutation(addTodo);

try {
    await mutate(todo);
    queryCache.refetchQueries('todos');
    queryCache.refetchQueries('reminders');
} 
catch {
    // something went wrong
}
```

and *v3*
```js
try {
    await addTodo(todo);
    queryCache.refetchQueries('todos');
    queryCache.refetchQueries('reminders');
}
catch {
    // something went wrong
}
```

Thanks for your help.

**Comment by tannerlinsley** [comment]
`useMutation` is indeed built from similar control flow you have shown here, but it's built this way so that you can be more terse and declarative with your mutation-side effects where you declare your mutation logic instead of having to handle that control flow yourself in a try/catch/finally block. When you see an example like optimistic updates and rollbacks using `onMutate`, `onError` and `onSuccess` and all of the variable mapping that goes on between them, it's more clear that you would not want to write that on your own every time you need it, nor would I expect many to want to have to set up this logic on their own in some type of promise wrapper.

Other useful features beyond this are:
- Automatically ignores side-effects and state changes due to outdated mutations
- Allowing defaults to be set and composed for side-effects via the config provider, useMutation instance and even overridden at the callsite level with the mutate-function overrides
- Support for error boundaries and suspense out of the box
