### ISSUE TITLE
useQuery inside of Next.js getLayout results in QueryClientProvider error

### ISSUE THREAD

**Issue by ryanirilli** [tannerlinsley/react-query#3462]
### Describe the bug

When using [Next.js Layouts feature](https://nextjs.org/docs/basic-features/layouts) and useQuery inside the layout function. an error is thrown 
```
No QueryClient set, use QueryClientProvider to set one
```

Even though I do have one set and is wrapping my getLayout function in `_app.js`

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-nextjs-get-layout-bug-lv00oi?file=/pages/_app.js

### Steps to reproduce

Load the example and see the error

### Expected behavior

As a user, I expect to be able to useQuery inside the getLayout function of Next.js

### How often does this bug happen?

Every time

### Platform

macOS
Chrome Version 99.0.4844.84 (Official Build) (x86_64)

### react-query version

3.34.19

**Comment by TkDodo** [comment]
`getLayout` is a simple function, not a react component. In your example, it is invoked by calling the function - not by instantiating a react component. You have given the function  an upper case starting character - my guess is this is done to silence the linter to complain about invalid hook calls? The hook call is not per se invalid, but since you call the function via `GetLayout()` rather than `<GetLayout>`, it will belong to the parent component. More about this in Kent's article here: https://kentcdodds.com/blog/dont-call-a-react-function-component

The easiest fix is to extract the useQuery call to a separate component, so that it really gets instantiated and rendered underneath the `QueryClient`:

```
function LayoutWithQuery({ children }) {
  const { data } = useTestQuery();
  console.log(data);
  return (
    <div>
      <h1>Layout</h1>
      {children}
    </div>
  );
}

IndexPage.getLayout = function getLayout(page) {
  return <LayoutWithQuery>{page}</LayoutWithQuery>;
};
```

working fork of your example is [here](https://codesandbox.io/s/react-query-nextjs-get-layout-bug-forked-6dsz8n?file=/pages/index.js)
