### ISSUE TITLE
Wrong Types of getNextPageParam and getPreviousPageParam in InfinityQuery 

### ISSUE THREAD

**Issue by pxe-la** [tannerlinsley/react-query#3499]
### Describe the bug

Type defined here
https://github.com/tannerlinsley/react-query/blob/b44c213b39a258486aff719ba87a5f7d8c57fab4/src/core/types.ts#L36

But the data passed to the function has type `(lastPage: TData, allPages: TData[])`
https://github.com/tannerlinsley/react-query/blob/e7a3207f74b27bc112d6ab583831cceac60f94c5/src/core/types.ts#L45

### Your minimal, reproducible example

[TS Playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwLACg5wK4GcCmBJAOwDNgDgYcBFDHKATwBpV0BVXQksi62ugJRxYMAGxhM0cNvmKlyVGvQDyYGMAgEs4gL5wiUCCDgByKDgCGAYxgBaAI4K6RgNypUMOmByTcAyFh70AApmUGYgWHAAvIjMcPa8AFxwWDBQpADmLiharijunt44vhD+DgJColExEmBm6ThJBBggAEa0WegwEDBmwgD6FhAYBDCNzW1QHXBy4UnIEujAACZjre2x6BhQwkkpaQSZG3AEYQ3JqRlT6EQi-ScgZ3uXR0TQANZYqxNTWgDaALqoHIoVCDDTwbBFHB+AJ0KoAClitVCs0KxVKvGCKM0sQgKjUGiSihA5AAPEcpBxZNwHMpVOosKSpOjYViwppMAQ3gQIAB3AgMNHQkqw8oiGAAPnE6HQRni9AA0jhHHAAD7GeV0ABiBCMsQlqAAlFEDRJIVSuPJeEyfMKMUEQuzBcNuXyBUKYWVBOKJYiFnBfiY7UZBcj2f9pTL4Qg4LV6mzDNEAIxwLRzWN1HAJgD8X1oqeNkQl1RlMtMMC2BF0OBgFgAFvCjHWYDAwJ8APTtsxgYAAOnS5DrGBavcGIHbuBC9fbpj85GgwEE2aMcAA1MccLzJHwADIAZXMUHrCaw0aOpfQmqSYfCvc1kYvMrjZ2fCd7XT3FwO8MND8fsdoPpnySIwkwABhDc8C0NKD0HfOscAIeF4VMLBC2LVDewAKywdQfxg-1S3gxDkKWMwenQuAz0Ii9ezosiej-R9gIzeNHRAJiZS0Q0CNLLQ-3mR96hgAA5HAAA8YGCNiUSSeFhDMFJpLOZk7VFb1REFXphGUz4PRFL0KhgAFKME-8wRSOAuh6YQdwgMwlhwJY8AocIqm03Te1MJYMAsHBkMsCxQ0zSjArXVicF7GYsF7YREPSGA60FMDDSuC9gCIKiFKUzN326XoBiGEY4FJKz8ts+zHOc1y0LgctK05RzOCctLS3qqAq2yqTcufcKk1a1MjmBdBUtQIA)

### Steps to reproduce

1. Define types of useInfiniteQuery
2. Define types of getNextPageParam
3. Check TS errors

### Expected behavior

Type of getNextPageParam:
```
export type GetPreviousPageParamFunction<TData = unknown> = (
  firstPage: TData,
  allPages: TData[]
) => unknown
```

### Platform

Browsers

### react-query version

6.5.9

### TypeScript version

4.3.5

**Comment by TkDodo** [comment]
not an issue, you just have the generics wrong. `params` is not a generic you have to provide. I went into details what `TQueryFnData` and `TData` is in this blog post: https://tkdodo.eu/blog/react-query-and-type-script

A fixed version includes either:

- [`useInfiniteQuery<UseReposQueryResult>(...)`](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwLACg5wK4GcCmBJAOwDNgDgYcBFDHKATwBpV0BVXQksi62ugJRxYMAGxhM0cNvmKlyVGvQDyYGMAgEs4gL5wiUCCDgByKDgCGAYxgBaAI4K6RgNypUMOmByTcAyFh70AApmUGYgWHAAvIjMcPa8AFxwWDBQpADmLiharijunt44vhD+DgJColExEmBm6ThJBBggAEa0WegwEDBmwgD6FhAYBDCNzW1QHXBy4UnIEujAACZjre2x6BhQwkkpaQSZG3AEYQ3JqRlT6EQi-ScgZ3uXR0TQANZYqxNTWgDaALqoHIoVCDDTwbBFHB+AJ0KoAClitVCs0KxVKvGCKM0sQgKjUGiSihA5AAPEcpBxZNwHMpVOosKSpOjYViwppMAQ3gQIAB3AgMNHQkqw8oiGAAPnE6HQRni9AA0jhHHAAD7GeV0ABiBCMsQlqAAlFEDRJIVSuPJeEyfMKMfQxaIJYiFnBfiY7UZBcj2f9pTL4Qg4LV6mzDNEAIxwLRzYN1HBhgD8X1o0eNkQl1RlMtMMC2BF0OBgFgAFvCjCWYDAwJ8APS1sxgYAAOnS5BLGBazcGIFruBCpdrpj85GgwEEiaMcAA1MccLzJHwADIAZXMUFLYawgaO2fQmqSPvCzc1-r3MpDZ0vYebXRXFwO8MNZ-PwdofUvSSMEYADF7d2mhoAegt4ljgBDwvCphYOmmbQc2ABWWDqE+QGutmoHgZBSxmD0sFwDu6F7s2JE4T0L7np+cahiEYQUTKWiGmh2ZaC+8znvUMAAHI4AAHjAwQ0SiSTwsIZgpIJOCCr0wiSTBJpZq+9avipAB6ibAXAYIpHAXQ9MIS4QGYSw4EseAUOEVQyXJzamEsGAWDgkGWBY3rxvhLkztRODNjMWDNsI4HpDAJaCj+hpXHuwBEARYkSfGt7dL0AxDCMcCkrpSUGUZJlmRZ8m5vmnImZwpmRdmhVQAWcUCQll5eRG5XRkcwLoBFqBAA)
- `useInfinteQuery(...)` without any generics at all, if your `queryFn` has a proper return type

the second one is preferred imo, but I couldn't get that to work because your `queryFn` returns an object, but `UseReposQueryResult` is supposed to be an Array. I think that's just a mistake in your example, hidden by the fact that `fetch` returns `any`.
