### ISSUE TITLE
Error: No QueryClient set, use QueryClientProvider to set one in ReactQueryDevTools with vite setup

### ISSUE THREAD

**Issue by akharkhonov** [tannerlinsley/react-query#3505]
### Describe the bug

After running `yarn dev', react query throws the following errors: 
<img width="988" alt="image" src="https://user-images.githubusercontent.com/47464417/163370128-301b3642-9fc8-4204-98e4-066978f40ea5.png">

### Your minimal, reproducible example

https://codesandbox.io/s/adoring-shirley-wy0dpd?file=/package.json    
https://github.com/akharkhonov/vite-react-query

### Steps to reproduce

1. Install dependencies `yarn`
2. Run dev mode `yarn dev`
3. Open devttools and see errors

### Expected behavior

As a user, I expected normal behaviour but I'm seeing errors

### How often does this bug happen?

Every time

### Platform

- OS: macOs
- Browser: Chrome
- Version: 100.0.4896.88 (Official Build) (x86_64)

### react-query version

3.34.19

### TypeScript version

4.6.3

**Comment by faradaytrs** [comment]
same here

**Comment by TkDodo** [comment]
thanks for reporting. things work fine when downgrading to `vite: 2.9.1`, so my assumption is that `2.9.2` has a change somewhere that is either unintended, or that we are not compatible with. Can someone experienced with vite help me track it down please?

downgraded, [working sandbox here](https://codesandbox.io/s/recursing-solomon-o5niky?file=/src/ReactQueryContext.tsx)

from our side: the devtools are bundled separately, but they import `from 'react-query'`. We do this so that the devtools pick up the same context that the app uses (otherwise, they wouldn't do anything). However, judging from the screenshot where it says `useQueryClient2`, it seems like there is some duplication going on now. If the devtools bring their own copy of react-query, there won't be a context above them, which would explain the error.

**Comment by akharkhonov** [comment]
@TkDodo thanks for your reply! Indeed, I hadn't thought about downgrading vite to a lower version, I was only playing around with react & react-query versions 😋. As for the duplicates in vite and dev-tools, yes I noticed that too, it was weird for me to see the `2` suffix in almost all variable names, but didn't pay enough attention to it. Also, I tried to debug the vite build in dev mode myself as part of another problem, but to no avail, because vite uses esbuild for dev, and esbuild is written in go

**Comment by TkDodo** [comment]
can we open an issue in `vite` and back link it here maybe? I'm happy to help from react-query side, but I'm afraid I don't know how at the moment. Note that we also had issues with vite in particular before:
- https://github.com/tannerlinsley/react-query/issues/1936

**Comment by akharkhonov** [comment]
@TkDodo since this is already a known problem, feel free to close this issue or mark it as a duplicate
