### ISSUE TITLE
initialData affecting "status" variable?

### ISSUE THREAD

**Issue by mattrothenberg** [tannerlinsley/react-query#355]
Howdy again!

I'm noticing something weird when I use the `initialData` option with `useQuery` in an SSR context. When my component mounts, `status` starts off as "success" which is what I expect. However, when one of my query key changes and my query function fires, `status` remains as "success" which I _don't_ expect. I would expect this variable to cycle through loading, success, and error as it would normally.

https://codesandbox.io/s/relaxed-wilson-rp8dp?file=/src/App.js

I'm fairly new to the land of SSR – perhaps I'm misunderstanding the role of `initialData` in pre-populating a query with data from the server?

**Comment by tannerlinsley** [comment]
`initialData` should correspond to the query key you are sending it. If you change the key and not the initial data, you are simply sending in that same initial data to the next query key.

**Comment by tannerlinsley** [comment]
In your example, you're right, it doesn't make much sense, because your initial data is hard coded. It makes more sense when you have something like `getStaticProps` in Next.js that is supplying the initial data for whatever page you attempting to view, based on a route parameter. When the query key changes, your router parameter would probably also change, and the initial data would also change as well. Without a dynamic SSR example, it's hard to illustrate, and honestly, that's the main situation that `initialData` is used for.
