### ISSUE TITLE
Warning from react-native on android about long setTimeout

### ISSUE THREAD

**Issue by adamjuhasz** [tannerlinsley/react-query#356]
## Warning
When running react-query with react-native on Android the following warning is emitted. I assume there needs to be a smarter timeout strategy with react-native but not sure what the best solution is. 
- Set a lower timeout?
- Use another timeout library that connects to native solution?

**Warning:**
`Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 300000ms)`

## Current Workaround:
Add the following code to suppress the warning
```typescript
import {YellowBox} from 'react-native';

const App = () => {
  //...
  useEffect(() => {
    YellowBox.ignoreWarnings(['Setting a timer']);
  }, []);
  //...
}
```

![image](https://user-images.githubusercontent.com/757940/79399561-8dac5900-7f38-11ea-95e4-2ef3b2ed8dee.png)

**Comment by tannerlinsley** [comment]
Interesting. I honestly didn't know this about React Native. I'll look into some solutions here.

**Comment by tannerlinsley** [comment]
Preliminary searches are showing that this is a long-running issue with timers on android and that the best solution during all of this time has either been
- setting the timers to be within the limits to not set off the warning (you could globally configure the `cacheTime` in React Query to be lower)
- replacing the timer implementation in React Native on Android with a custom timer implementation that works in the background better
- suppressing the warning (as you outlined above)

IMO, suppressing the warning would be fine, since it is just a cache and not a critical operational piece of the app. If the cache doesn't get cleared, then the data will remain in memory until the app is closed and reopened. Not a big deal. And if it does become a big deal, then you have other options.
