### ISSUE TITLE
`error` is an empty object using `throw new Error(error)`

### ISSUE THREAD

**Issue by kaueDM** [tannerlinsley/react-query#3593]
### Describe the bug

When using `throw new Error`, the value of `error` is set as an empty object.

### Your minimal, reproducible example

https://codesandbox.io/s/rq-throw-issue-iyz0xi?file=/src/index.js

### Steps to reproduce

1. Wait for the RQ query to execute
2. The error will be shown as `{}`
3. Go to `line 23` and change it to `throw "Oh snap!"`
4. The error will be shown as `Oh snap!`

### Expected behavior

The `error` property to be set correctly when using `throw new Error(error)`

### How often does this bug happen?

Every time

### Platform

Firefox, 100.0 (64-bit)

### react-query version

3.38.1

**Comment by TkDodo** [comment]
The problem is merely that you cannot json stringify an Error object. This will just yield empty object. You can try this in the console:

```
JSON.stringify(new Error("my message"))
```

<img width="306" alt="Screenshot 2022-05-07 at 19 28 08" src="https://user-images.githubusercontent.com/1021430/167265231-bee53c28-abc5-4f5c-b94d-dff608900799.png">

changing it to:

```
<div>{isError ? `Error: ${error.message}` : ""}</div>
```

just works as expected. working sandbox fork: https://codesandbox.io/s/rq-throw-issue-forked-rz5mfg?file=/src/index.js
