### ISSUE TITLE
Parallel queries from two components

### ISSUE THREAD

**Issue by lishine** [tannerlinsley/react-query#361]
Is it a bug or a feature?
In one component
```
const { status, isFetching } = useQuery('gallery',[variables], fetchGallery, { onSuccess: () => {...} })
```
In another component
```
  const { data: rows = [], ...rest } = useQuery('gallery', undefined, { manual: true })
```

The result: both queries return loading status, do retries and eventually error.
If I remove the second one, first one is loading as it should be.

I try to use here the cache from one component in another

**Comment by tannerlinsley** [comment]
This is intentional. My suggestion:
- Extract your gallery query into a custom hook that can accept optional config. This way its reusable, and you'll never find yourself without the query function for that query.
- Extract your function to a different file that you can import where you use this query
- Use `queryCache.getQueryData` to synchronously access the query's data, which doesn't require a fetcher function to be passed at all.
