### ISSUE TITLE
useQuery runs twice on initial load with React 18

### ISSUE THREAD

**Issue by facu-01** [tannerlinsley/react-query#3633]
### Describe the bug

Using axios, if you pass the signal parameter, the api call runs twice (cancelling the first) on page reload.
I think that is the same bug that: #https://github.com/tannerlinsley/react-query/issues/3492

### Your minimal, reproducible example

https://codesandbox.io/s/funny-sid-odqlqr?file=/src/App.js

### Steps to reproduce

Open the network tab, refresh the Browser output and see two API calls(one cancelled).

### Expected behavior

Only one api call.

### How often does this bug happen?

Every time

### Platform

...

### react-query version

v4.0.0-beta.1

**Comment by TkDodo** [comment]
This is the expected behaviour, or at least, there is not a lot we can do about it. This is related to `strict effects` in react 18, which means you'll only see this behaviour if you use `<StrictMode>`, and only during development. In that mode, react quickly mounts and unmounts every component to stress-test the app and to simulate quick user interaction. So what happens is:
- component mounts, fetches
- component unmounts. Since you only had one observer and you consumed the AbortSignal, the fetch is cancelled.
- component mounts again, another fetch.

If you don't consume the AbortSignal, the second fetch will not fire because the first one is still ongoing. You can read more about this here: https://github.com/facebook/react/issues/24502#issuecomment-1120856043

This is different from #3492, because with InfiniteQueries, we currently always abort fetches even if the AbortSignal is not consumed, which is likely a bug (we're still discussing it on the PR).
