### ISSUE TITLE
toggling enabled with suspense: true uses stale version of queryFn

### ISSUE THREAD

**Issue by iway1** [tannerlinsley/react-query#3650]
### Describe the bug

If you toggle `enabled` from `false` to `true` while having `suspense: true`, query will fetch using the older version of `queryFn`. This is inconsistent with the behavior when `suspense: false` (where it will use the most previously passed version of queryFn). I would imagine we would like useQuery to use the latest `queryFn` at all times?

### Your minimal, reproducible example

https://codesandbox.io/s/quizzical-archimedes-1fu98b?file=/src/App.js

### Steps to reproduce

1. Create useQuery hook with suspense true, and enabled false. 
2. useQuery queryFn should use some state value from the outer functions scope. 
3. Simultaneously change the value and enabled to true
4. Realize that the newest value isn't reflected in the queryFn when it is called.

### Expected behavior

Param in the queryFn should be the same as the param in the hook when `enabled` is toggled from `false` to `true`. Instead, `param` in the queryFn is the previous value of `undefined` which crashes, implying we're using the enclosed value from the previous time the queryFn was defined. Checkout my codesandbox

### How often does this bug happen?

Every time

### Platform

All

### react-query version

3.39.0

**Comment by iway1** [comment]
Also there's a workaround that's pretty easy in case anyone's curious:
```ts

import React, { useRef } from "react";
export type ReferenceValue<T> = React.MutableRefObject<T>
export default function useReferenceValue<T extends any>(value: T): ReferenceValue<T> {
    const ref = useRef<any>(value);
    ref.current = value;
    return ref;
}
```
Then in the query itself make sure to only use the ref instead of an values directly:

```
function useReactQueryBug({ param }) {
  const paramRef = useReferenceValue(param);
  return useQuery(
    ["key"],
    async () => {
      const { property } = paramRef.current;

      return property;
    },
    {
      enabled: !!param,
      suspense: true
    }
  );
}

```

**Comment by TkDodo** [comment]
your issue is that you closure over something (`param`) in the `queryFn` that is _not_ part of the `queryKey`. It is documented that every dependency of your query should be part of the query key to avoid these problems, and also to give you the benefit of caching per params:

- [If your query function depends on a variable, include it in your query key](https://react-query.tanstack.com/guides/query-keys#if-your-query-function-depends-on-a-variable-include-it-in-your-query-key)
- [Treat the query key like a dependency array](https://tkdodo.eu/blog/practical-react-query#treat-the-query-key-like-a-dependency-array)

"fixed" sandbox: https://codesandbox.io/s/stoic-banach-o7dbdv
