### ISSUE TITLE
Bug: unnecessary dependency in refetch useEffect

### ISSUE THREAD

**Issue by liorfrenkel** [tannerlinsley/react-query#425]
Hi,

I have noticed a strange behavior when using useQuery in a component which changes more frequently than the refetchInterval,

**To the point, the useEffect responsible is cleaned up and the time out is re-created before it manages to re-fetch**,

This is the first time I look into the source code of this library so there may be things that I do not know, but I fail to see the purpose of these 2 places in `useBaseQuery.js`:
1. `config.refetchInterval < query.refetchInterval` https://github.com/tannerlinsley/react-query/blob/master/src/useBaseQuery.js#L94 
2. using `query.refetchInterval` in the effect dependencies: https://github.com/tannerlinsley/react-query/blob/master/src/useBaseQuery.js#L111

here is a simple test I made with a fresh-created react app to prove that point, open the console to see that the re-render function is not called:
https://codesandbox.io/s/react-query-refetch-bug-095kd

1. why `config.refetchInterval < query.refetchInterval`? what is the relation between the timeout milliseconds and the setInterval ID ?
2. unless there is a reason to put `query.refetchInterval` in the dependencies array, the solution here would be to remove it from the dependencies.

Thanks a lot!
Lior

**Comment by tannerlinsley** [comment]
1. The `config.refetchInterval` is not the ID. It's the smallest interval currently being used on the query. The check is done to ensure that the smallest interval is used for the entire query and only a single interval is used for the query, not an interval per-useQuery instance. This may change in the future, but for now, this is by design.
2. It's in the dependencies because if you change the interval integer, you'll probably want the actual interval to change too.

There is currently a known bug and PR to fix a case where rerenders cause the interval to reset unnecessarily. https://github.com/tannerlinsley/react-query/pull/404/files We're going to track this issue there.

**Comment by liorfrenkel** [comment]
@tannerlinsley  I was talking about `query.refetchInterval` and not `config.refetchInterval`

**Comment by tannerlinsley** [comment]
Ah, Yes. This is indeed a bug which we're also working on currently.

**Comment by liorfrenkel** [comment]
great!
