### ISSUE TITLE
[RFC] Add useQueries hook

### ISSUE THREAD

**Issue by alexandernanberg** [tannerlinsley/react-query#480]
When you have multiple queries and not running concurrent mode, you can easily create a request waterfall.

```js
const { data: thing } = useQuery('thing', () => fetch(), { suspense: true });
const { data: something } = useQuery('something-else', () => fetch(), { suspense: true });
```

In the example the first query has to finish before the second one runs. I know you could get around this with prefetching but it's not super convenient. So I'd like to propose that we add a `useQueries` hook that would allow you to do something like

```js
const [thing, something] = useQueries(() => {
  const { data: thing } = useQuery('thing', () => fetch())
  const { data: something } = useQuery('something-else', () => fetch())
  return [thing, something]
})
```
 
The idea is stolen from https://github.com/zeit/swr/pull/168/files

**Comment by tannerlinsley** [comment]
A few questions:
- What scenarios does this involve where breaking the queries out into individual components doesn't solve the issue?
- Is this because you *absolutely* need both queries before proceeding and they don't depend on each other?

My gut reaction is that what SWR is doing in this area (or that PR to SWR) is pretty hacky. *If* this is an avenue I decide to go down, I'm going to probably take a more intentional approach to the design instead. But to do that, I want to understand the use-cases and motivations behind it really well.

**Comment by alexandernanberg** [comment]
Gave this some more thought and I think you're right. Prefetching is a better solution and covers more use-cases, like having queries in different components.

And for my specific use-case I can just use `Promise.all` if I don't wanna do a prefetch

```js
const { data: [thing, something] } = useQuery('thing', () => Promise.all([fetchThing(), fetchSomething()], { suspense: true });
```
