### ISSUE TITLE
useFunctionQuery from documentation cause infinite loop

### ISSUE THREAD

**Issue by powah** [tannerlinsley/react-query#81]
I liked the idea for key to use a function itself used for fetching the data because of no need to use strings or additional constants. Tried to use it from documentation and it triggers infinite rapid fetching. A function reference is stable (exported from separate module) so something inside custom hook needs to be memoized? Any guidance how to solve this?

I'm talking about this custom hook:

`function useQuery(functionTuple, options) {
    const [queryFn] = Array.isArray(functionTuple) ? functionTuple : [functionTuple];
    return useReactQuery(functionTuple, queryFn, options);
}`

**Comment by cherniavskii** [comment]
You should stringify your function before using it as query key, since react-query checks if queryKey is a function, invokes it and uses returned value as key - see https://github.com/tannerlinsley/react-query/blob/master/src/index.js#L727.
In your case new Promise instance is used as query key, so new query is created on every render.

IMHO using strings or tuples (as suggested in docs) is much better option, but React Query isn't limited to it and of course you are free to use it as you want.

**Comment by powah** [comment]
It's not a function, a query key is an array of function and variables [queryFn, variables]. Like I mentioned in an issue - that custom hook is take straight from react-query documentation:
```// Heck, you can even make your own custom useQueryHook!

function useFunctionQuery(functionTuple, options) {
  const [queryFn, variables] = Array.isArray(functionTuple)
    ? functionTuple
    : [functionTuple]
  return useQuery(functionTuple, queryFn, options)
}```

**Comment by cherniavskii** [comment]
@powah do you also use custom query key serializer?

**Comment by powah** [comment]
No, do I have to?

**Comment by cherniavskii** [comment]
You're welcome :)
