### ISSUE TITLE
Errors are supressed in onSuccess callbacks

### ISSUE THREAD

**Issue by talolard** [tannerlinsley/react-query#824]
**Describe the bug**
When an exception is raised in onSuccess callbacks, the error is suppressed 

**To Reproduce**
```ts
async function exampleQueryFunction() {
  return "response";
}
const query = useQuery("key", exampleQueryFunction, {
  onSuccess: response => {
    debugger;
    throw new Error("This error should propogate");
  },
  onError: err => {
    console.log(err);
  }
});

```
**Expected behavior**
I expect some indication that there was an error in onSuccess. 
Definitely expect that isError is set to true, but it is not. 
I don't think that onError is the right place to handle this because it corresponds to the query function. 

Maybe a final onAnyError callback that catches any unhandled exception anywhere ? 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Chrome
 - Version: 81.0.4044.138

**Additional context**

**Comment by mustafawm** [comment]
`throwOnError` config flag, _which is available for `useMutate` and `queryCache.prefetchQuery`_ would solve the issue here.

I'm not sure why it's not available for `useQuery` 🤔

**Comment by talolard** [comment]
@mustafawm , not in the way I’d expect. Which is to say that I like having the onerror callback and wouldn’t want to give up on that because of errors in onsuccess. 

Like there needs to be a difference between the error my server returned and something stupid I did on the client after the response .

But perhaps onerror and onsuccess should throw in error ?

**Comment by tannerlinsley** [comment]
What's wrong with this?
```js
const query = useQuery("key", exampleQueryFunction, {
  onSuccess: response => {
    try {
      await possiblyJankySideEffect()
    } catch (err) {
      console.log('My Bad')
    }
  },
  onError: err => {
    console.log(`Server's fault`)
  }
});
```

**Comment by talolard** [comment]
I think that works, maybe just make the docs more explicit about that. 
Happy to give it a shot

**Comment by tannerlinsley** [comment]
Reopen if necessary.

**Comment by guim1993** [comment]
I'm having a similar problem.
The server is returning status 202, as the data is not ready yet.
And since 202 is success status, my idea was to return an error in onSucces, and then use the retry with delay when this happens, until the server responds with 200.
But I haven't found a way to simulate an error when I have a success status.

**Comment by TkDodo** [comment]
you need to return the error from the queryFn:

```
useQuery(
  key,
  async () => {
    const response = await axios.get(..)
    if (response.status === 202) {
      throw new Error("whatever")
    }
    return response.data
  }
)
```

callback functions are not the place to do data transformation!

**Comment by phoenixeliot** [comment]
I think that having to add try/catch or else the error just disappears completely is pretty unexpected and easy to fall into traps around, since normally the default behavior for errors thrown and not caught is to at least run the global onError handler and log it to the console. I basically just want all uncaught errors here to get logged to the console and to Sentry. It's a pain to have to add a try/catch to every useQuery (and have to remember to do so), or risk errors that I just never find out about because they're suppressed completely.

**Comment by TkDodo** [comment]
> I think that having to add try/catch or else the error just disappears completely is pretty unexpected and easy to fall into traps around

I don't understand this. This issue is pretty old, so I'm not sure what exactly you are referring to. To log all errors, you can use the global error handlers on the queryCache:
- https://tanstack.com/query/v4/docs/react/reference/QueryCache#global-callbacks

It would be best if you'd open a new discussion or issue, best with a minimal, reproducible example of what you're struggling with.

**Comment by 55Cancri** [comment]
@phoenixeliot I agree completely, I was _shocked_ today when I learned that my errors in the onSuccess callback were being swallowed. I actually couldn't believe it, I would have expected them to bubble up and trigger the error boundary to display my fallback. I tried setting the `useErrorBoundary` and `onError` props to see if these would run after the error occurred in onSuccess, but nope.

@tannerlinsley I believe errors in the onSuccess should most definitely not be swallowed and silently suppressed like that. I wish errors in the onSuccess would abide by the useErrorBoundary prop and either throw it globally so my error boundary can catch by default, or else return in the error payload.

My use case is this:
```typescript
function useHookToRunInitialQueries() {
     const { storeGlobalState1 } = useGlobalState1()
     const { storeGlobalState2 } = useGlobalState2()
     const { storeGlobalState3 } = useGlobalState3()

     useQuery('/url1', {
           onSucess: (d) => {
                   storeGlobalState1(d)
           }

     useQuery('/url2', {
           onSucess: (d) => {
                   storeGlobalState2(d)
           }

     useQuery('/url3, {
           onSucess: (d) => {
                   storeGlobalState3(d)
           }
}
```
The storeGlobalState functions internally run a zod parse to verify the response is what I expect from the api and if the validation fails, I had been expecting them to bubble up to my error boundary but it wasn't working at all.

**Comment by TkDodo** [comment]
> I was shocked today when I learned that my errors in the onSuccess callback were being swallowed. I actually couldn't believe it, I would have expected them to bubble up and trigger the error boundary to display my fallback

I hope you've recovered from that _shock_.

The reason is quite simple once you understand React Query. `onSuccess` runs on a per-observer basis. If you call `useQuery` with the same key multiple times, `onSuccess` is also executed multiple times. There is only one query in the cache though, so different `onSuccess` "results" (error or no error) would contradict each other. This is also the reason why, unlike useMutation, where each invocation has its own cache entry, we cannot await anything returned from `onSuccess`.

> My use case is this

Sorry to say but this is not a use-case, it's an anti-pattern on multiple levels:

1) React Query is already a global state manager, there shouldn't be a need to sync it to a different state manager. That's state duplication.

2) It will get out-of-sync if you use `staleTime` and switch the queryKey, because `onSuccess` is tied to a fetch happening, which doesn't happen in this case.

3) The zod parsing should happen in the query function. I have a whole blogpost on that topic: https://tkdodo.eu/blog/type-safe-react-query

> Essentially onSuccess is a footgun and an untrusthworthy callback

I tend to agree, it has limited applicability, like animating an element via a ref or syncing something to local component state (which shouldn't be necessary). In your case though, I'm afraid you're just "using it wrong".

**Comment by 55Cancri** [comment]
@TkDodo sucks that it was so easy to use "wrong". It practically an invitation to do go that route (once a query finishes, do this other thing).
And I understand react query has the ability to do global state, but fundamentally it makes queries and users shouldn't be _required_ to change both their query package and global state method to use it. If people just want to use it to make queries, I think that should be allowed, and it does do that better than any other. Maybe updating it's state / cache isn't as ergonomic as other state management solutions or they just simply prefer to use something else?

Either way, thank you for the suggestion to do zod parsing in the query which I suppose is the main issue here as errors are the whole point of zod and I would like them as early as possible. Reluctantly, I will still set state into my favorite global statement solution in the onSuccess (as opposed to say a useeffect that listens for data changes and then updates there), Ill just try to remember to add zero logic above simply calling a setstate function.

Thank you also for quick response and I'll be seeing what else I can learn from your blog.

**Comment by 55Cancri** [comment]
Also for anyone that simply needs an onSuccess callback that throws errors globally and doesn't care too much about the little stuff, here's a simple hook I jury-rigged together this morning. It 100% accommodates my use case but please feel free to extend it anyway you need to. It will run the onSuccess callback the same way and if an error occurs it will propagate to error boundary:

```typescript
// hooks/useQuery.ts
import React from "react";
import axios from 'axios'
import { useQuery, UseQueryOptions } from "@tanstack/react-query";

type QueryOpts<T> = Omit<
  UseQueryOptions<any, T, any, any>,
  "initialData" | "queryFn" | "queryKey"
>;
export default function useAuthorizedQuery<T = any>(
  endpoint: string,
  opts?: QueryOpts<T>
) {
  const { onSuccess, ...restOpts } = opts ?? {};
  const [finalData, setFinalData] = React.useState();
  const { data, isSuccess, ...rest } = useQuery<any, T, any, any>(
    [endpoint],
    () => axios.get(endpoint),
    restOpts
  );

  React.useEffect(() => {
    if (!isSuccess) return;
    const result = onSuccess ? onSuccess(data) : data;
    setFinalData(result);
  }, [isSuccess, data]);

  return { ...rest, isSuccess, data: finalData };
}

// someFile.ts
import { useQuery } from 'hooks/useQuery'

...

useQuery('/url', {
    onSuccess: d => {
         // ...any errors here will bubble up...
    }
})
```
