### ISSUE TITLE
Conditional Retry

### ISSUE THREAD

**Issue by julianwachholz** [tannerlinsley/react-query#84]
I'd like to explore the possibility of adding a conditional retry feature.

One might not want to retry if the server responds with a 404, then we just want to display a "not found" page. But we still want to retry if there's a temporary error somewhere else.

**Comment by nikoskleidis** [comment]
If I understand correctly what you are trying to do, you can use `retry` option as described here:
https://github.com/tannerlinsley/react-query#retries

**Comment by julianwachholz** [comment]
Thanks for your input, I am using this setting but it doesn't allow conditional values as I've explained.

**Comment by nikoskleidis** [comment]
Then I think you should handle the 404 error internally (without throwing an error). You can throw an error only for status codes that you want react-query to retry fetching.

**Comment by julianwachholz** [comment]
You're right, I'm silly. Right now I'm just throwing when `!response.ok`, which might be a bit overzealous.

**Comment by tannerlinsley** [comment]
Let me know if there is any more to discuss here.

**Comment by smozely** [comment]
Don't know if I should raise a new issue or continue the discussion here ... 

The idea for handling the errors internally doesn't work that well for using Suspense and Error boundaries.

What we thinking we want to do is have failed requests be sent up the error boundaries, and there we would have a error boundary that handles just the data being unavailable, and a boundary higher up the stack that handles more fatal things ... like session timeouts, which in our case need to send the user to our login application. And here a session timeout error would be something we don't want to retry on.

In a POC of writing our own lib for handling this type of stuff, we had a magic "NoRetryError" which would wrap a real error, that we would throw to indicate something shouldn't be retried, which worked ... but felt a little gross because it was the only time our fetching stuff needed to know it was being wrapped in our lib. Another thing we considered was adding a magic prop to an Error to indicate not to retry ... but has that same issue of needing to know its being wrapped.
