### ISSUE TITLE
`refetch` function returned by `useQuery` does not behave accordingly to docs

### ISSUE THREAD

**Issue by lgenzelis** [tannerlinsley/react-query#843]
**Describe the bug**
The [docs](https://github.com/tannerlinsley/react-query/blob/master/docs/src/pages/docs/api.md) (line 155) describe the  `refetch` function returned by `useQuery` as having the signature `refetch: Function({ force, throwOnError }) => void`. This doesn't seem to be true, as `refecth` actually does not accept any argument at all.

Moreover, that same section of the docs say that the default behavior of `refetch` is fetching the query only if it is **stale** (which can supposedly be bypassed by passing `{force: true}`). This isn't right either. Calling `refetch`(with no arguments) always refetches de query, disregarding its status.

**Expected behavior**
I'd love to see `refetch` behaving as described in the docs, but if that cannot be easily fixed, it would be necessary to update the docs accordingly. So, `refetch` should be typed as `refetch: () => void` and the description should say that it always refetches the query (stale or not).

**Additional context**
I'm working in React Native, just in case. Still, browsing the source code didn't lead me to the behavior described in the docs.

**Comment by dimagimburg** [comment]
An addition to what you wrote here, there is also some not sync state between docs, types, and implementation.

In implementation:
https://github.com/tannerlinsley/react-query/blob/3545717b95ea4de9837930221c399f40ec3c94cb/src/core/query.ts#L226

`refetch` returns Promise<void>

In docs:
https://react-query.tanstack.com/docs/api#usequery
the signture is ```refetch: Function({ force, throwOnError }) => void```

In `/src/core/types.ts`:
https://github.com/tannerlinsley/react-query/blob/3545717b95ea4de9837930221c399f40ec3c94cb/src/core/types.ts#L109

In `/types/index.d.ts`:
https://github.com/tannerlinsley/react-query/blob/3545717b95ea4de9837930221c399f40ec3c94cb/types/index.d.ts#L288

so 4 places and 4 different APIs.

I needed the `refetch: ({ throwOnError }?: { throwOnError?: boolean }) => Promise<TResult>` because I needed to do something with the refetched data imediatly after refetch, which is what my IDE suggested to me, and got error because promise returned `undefined`

**Comment by tannerlinsley** [comment]
New types have been released that should clear this up.
