### ISSUE TITLE
useQuery not catching/handling the error when throwing error from mocked API in tests

### ISSUE THREAD

**Issue by sbjovanovski** [tannerlinsley/react-query#859]
**Describe the bug**
I am using useQuery to fetch data from API. When I run the application in the browser, if the backend throws error, the error is properly handled by useQuery and displayed on the screen. 

But when I am trying to do the same thing via testing, once I throw an error from the test itself, even tho my function is throwing the error properly, useQuery is not handling the error and it's constantly in loading state.

### Codesandbox example
https://codesandbox.io/s/cool-glitter-0vvki?file=/src/App.test.js

**Expected behavior**
Expected `isError` to be true when throwing error from the tests.

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina]
 - Browser: [Chrome]
 - Version: [e.g. 22]

**Comment by mether** [comment]
I think I had the same issue with constant loading states and I believe this was due to the fact that [by default react-query retries 3 times on error](https://react-query.tanstack.com/docs/guides/important-defaults), leaving `status === 'loading'` and `error === null` until it fails on the third attempt

Try setting `retry: false` in your `useQuery` options e.g. `const { ... } = useQuery(["toDo"], getToDo, { ..., retry: false });`

If that addresses the problem in your tests, you can create a [custom renderer](https://testing-library.com/docs/react-testing-library/setup#custom-render) for your tests and use the [ReactQueryConfigProvider](https://react-query.tanstack.com/docs/api#reactqueryconfigprovider) to set `retry: false` for consistent tests without having to disable it for your end users

Hope that helps!

P.S. I tried to fork your example but there seems to be some errors in there and I didn't have time to address them.

**Comment by tannerlinsley** [comment]
Yep. Make sure you are accounting for `retry` or setting it to `0`.

**Comment by narthur** [comment]
Since I think the API has changed recently and `ReactQueryConfigProvider` is no longer a thing, here is the helper function I'm using to set `retry` to `false` in my tests without it:

```
export function renderWithQueryProvider(ui: ReactElement) {
    const client = new QueryClient({
        defaultOptions: {
            queries: {
                retry: false
            }
        }
    })
    return render(<QueryClientProvider client={client}>{ui}</QueryClientProvider>)
}
```

**Comment by cmacdonnacha** [comment]
Hey guys,

I ran into this issue recently where in my `react-testing-library` based test I am checking if an error message was displayed when I failed to make an api request. However, my test is failing because of the way `react-query` will retry 3 times before displaying this message, meaning RTL's timeout kicks in and says the text was not found. By adding `retry: false` in my test setup it fixes this issue and everything passes.

```
const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
      },
    },
  });
```
  
However I am weary that I am not testing exactly what the user experiences and was wondering if this is a problem. Am I overthinking it?

**Comment by TkDodo** [comment]
since this is react-quey internal logic, which you likely don't need to / want to test, I would also turn it off in the tests. It's a "common" gotcha to run into timeouts here because of the default retries and the exponential backoff. I do the exact same thin in my tests 👍

**Comment by cmacdonnacha** [comment]
Excellent, thanks for the reassurance @TkDodo 👍

**Comment by chawax** [comment]
> I think I had the same issue with constant loading states and I believe this was due to the fact that [by default react-query retries 3 times on error](https://react-query.tanstack.com/docs/guides/important-defaults), leaving `status === 'loading'` and `error === null` until it fails on the third attempt
> 
> Try setting `retry: false` in your `useQuery` options e.g. `const { ... } = useQuery(["toDo"], getToDo, { ..., retry: false });`
> 
> If that addresses the problem in your tests, you can create a [custom renderer](https://testing-library.com/docs/react-testing-library/setup#custom-render) for your tests and use the [ReactQueryConfigProvider](https://react-query.tanstack.com/docs/api#reactqueryconfigprovider) to set `retry: false` for consistent tests without having to disable it for your end users
> 
> Hope that helps!
> 
> P.S. I tried to fork your example but there seems to be some errors in there and I didn't have time to address them.

Obviously ! I had this problem for hours ! Thanks a lot, you saved my day !

**Comment by jacobtani** [comment]
Thank you so much I have been looking for a solution for this for days
