### ISSUE TITLE
useQuery's onSuccess execs more than one times

### ISSUE THREAD

**Issue by anc95** [tannerlinsley/react-query#936]
**Describe the bug**
useQuery's onSuccess execs more than one times

**To Reproduce**
I made a small demo on codesanbox, which I expect that the "success" on print once, but got two
https://codesandbox.io/s/react-query-onsuccess-wsiff

and on the other hand, swr works as expect
https://codesandbox.io/s/swr-onsuccess-nc5q0?file=/src/App.js

**Expected behavior**
expected that the onSuccess function exec only once

**ScreenShoots**
![image](https://user-images.githubusercontent.com/13167934/91516866-227b8600-e91f-11ea-95c5-e36bf0c89da9.png)

**Comment by boschni** [comment]
Hi @anc95! I think this is correct behaviour. Otherwise, if the hook is used in multiple components, which of them should be called? Or what if you need to execute some code in each component when the query succeeds? Or if you need to execute different code in each component? If you have some code which should only execute once, there should only be one hook with a callback.

**Comment by tannerlinsley** [comment]
Or, you can even put your global "onSuccess" logic right inside your query function, thus it will get deduped and only run once every time the data is actually updated.

**Comment by anc95** [comment]
> Or, you can even put your global "onSuccess" logic right inside your query function, thus it will get deduped and only run once every time the data is actually updated.

ok it should works fine. Thx

**Comment by andresgutgon** [comment]
This behaviour was very surprising to me. I would have expected one `useQuery.onSuccess` to be triggered only once. 
But is triggered the number of times that `useQuery` with that `queryQuery` is present in the UI at that moment.


Thanks for the solution thought @tannerlinsley !

**Comment by TkDodo** [comment]
you can also use the global onSuccess handler on the queryCache:

https://react-query.tanstack.com/reference/QueryCache#global-callbacks

**Comment by andresgutgon** [comment]
In our case was only for 2 keys. I want to trigger an event with our event system only for those 2 keys. So what I did was to trigger it on a `.then` callback on our `fetchFn`

**Comment by andresgutgon** [comment]
Thanks for sharing @Subalee . In my case I will not try to fight react-query . I prefer to handle it before all `onSuccess` callbacks are triggered and do my thing there. 
Not saying neither is the best solution, it was in my case I think : )

**Comment by christianalares** [comment]
I stumbled upon this challenge as well but not for the onSuccess callback, but for the onError callback. I needed to run this callback only once, and not for every consumer of the query. I couldn't handle the "onError"-functionality directly in the queryFn since that won't care about the retries so I came up with this workaround using ref as flag:

https://codesandbox.io/s/react-query-onsuccess-forked-7eeuwt?file=/src/App.js

**Comment by TkDodo** [comment]
@christianalares use the global onError callback of the query cache then?

https://tanstack.com/query/v4/docs/reference/QueryCache#global-callbacks

**Comment by christianalares** [comment]
> @christianalares use the global onError callback of the query cache then?
> 
> https://tanstack.com/query/v4/docs/reference/QueryCache#global-callbacks

Oh, of course, that’s a good idea. Is is also possible to check which query that failed in the global onError?

**Comment by TkDodo** [comment]
sure, the queryKey is passed to it.
