### ISSUE TITLE
Add Option to disable caching

### ISSUE THREAD

**Issue by e102** [tannerlinsley/react-query#99]
One issue I've had is that when writing tests, it's easy to run into problems caused by react-query's caching. It would be good to have an option to disable caching wholesale.

**Comment by nikoskleidis** [comment]
As stated in the docs you can play with cacheTime option
> If and when a query is no longer being used, it becomes inactive and by default is cached in the background for 5 minutes. This time can be configured using the cacheTime option at both the global and query-level.

By setting **cacheTime** to 0 in the options, you can disable caching in a specific query but by setting this to the react-query's provider, you can disable caching for every query

**Comment by darekdesu** [comment]
@tannerlinsley I don't want to open separate new issue but rather to elaborate on this one.

I faced similar situation - I use react-query in my React components and MSW (Mock Service Worker) and Jest for testing. I have observed leaking cache from react-query between tests. That is because of the the react-query documentation where you can find:
```
Set cacheTime to Infinity with Jest
cacheTime is set to 5 minutes by default. It means that the cache garbage collector timer will be triggered every 5 minutes. If you use Jest, you can set the cacheTime to Infinity to prevent "Jest did not exit one second after the test run completed" error message.


```
Source: https://react-query.tanstack.com/guides/testing#set-cachetime-to-infinity-with-jest

It is misleading and should be replaced with suggestion to always set `cacheTime: 0` alongside `retry: false` and newer ever use `cacheTime: Infinite`.

**Comment by ruangustavo** [comment]
In case anyone is using Tanstack Query in version 5, the `cacheTime` property has been renamed to `gcTime` :)

https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5#rename-cachetime-to-gctime

**Comment by reza-sdo** [comment]
> In case anyone is using Tanstack Query in version 5, the `cacheTime` property has been renamed to `gcTime` :)
> 
> https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5#rename-cachetime-to-gctime


Gc time work when there isn't any observer to that query
